### ISSUE TITLE
"Copy" output format

### ISSUE THREAD

**Issue by landroni** [flacon/flacon#10]
Please allow the users to do only splitting, without any encoding. 

Now if I have a FLAC file and simply want to split it using a CUE, I have to select FLAC output format, and Flacon would then extract the FLAC files and re-encode them into FLAC. 

It would be much nicer if a "Copy" output format were selectable, which would result in Flacon splitting and extracting the files *without* doing any unnecessary encoding.

**Comment by SokoloffA** [comment]
Unfortunately, it is not possible. Audio files have a complex structure and cannot simply be cut into several parts. Even if the input and output files have the same format, the program will have to convert compressed audio data to uncompressed RAW, and then encode them in separate files.
