### ISSUE TITLE
ERROR: invalid WAVEFORMATEXTENSIBLE chunk with size 16

### ISSUE THREAD

**Issue by Mc-Seam** [flacon/flacon#100]
Flacon 5.4.0, Debian testing.

При попытке разрезать на части 24-битный файл (sample rate любой) после распаковки первого файла процесс останавливается с ошибкой, текст ошибки разный (см. ниже):

*Если выходной файл - flac:*

Ошибка кодирования:
-: ERROR: invalid WAVEFORMATEXTENSIBLE chunk with size 16

(если запускать flacon из терминала, то в терминале следующее:
Encoder command: /usr/bin/flac --force --silent --compression-level-5 --tag artist=Argo --tag album=Svet --tag 'title=Мир Пробуждается Во Мне' --tag albumartist=Argo --tag tracknumber=1 --tag totaltracks=6 --tag tracktotal=6 --tag disc=1 --tag discnumber=1 --tag disctotal=1 - -o '/home/maksim/500GB/OUTPUT/Argo -  - Svet/flacon_b2017a5d-7fd7-4c96-8fd2-63868c1431f2-01.encoded.flac' 
Ошибка кодирования:-: ERROR: invalid WAVEFORMATEXTENSIBLE chunk with size 16

*Выходной файл - ogg:*

Ошибка кодирования:
ERROR: Extended WAV format header invalid (too small)
ОШИБКА: Входной файл "(stdin)" в не поддерживаемом формате

*Выходной файл - mp3:*

Ошибка кодирования:
Unsupported data format: 0xFFFFFFFE
Can't init infile '-'

*Выходной файл - wv:*

Ошибка кодирования:
'-' is an unsupported .WAV format!            (первый символ в строке - дефис без кавычек)                    

(Других кодировщиков нет).

Входной файл - 24-битный flac (sample rate может быть разный, 24/48, 24/96, 24/192).

16-битные файлы режутся на ура в любой формат.

В какой момент (или после чего) появилась ошибка точно не скажу, последние пару месяцев ничего не резал, до этого все работало. Версия flacon была 5.0.0. Удалил, установил новую, ошибка осталась. 

Версии программ:

flacon - 5.4.0 (на 5.0.0 - то же самое)
flac - 1.3.3
wv - 5.1.0
lame - 3.100
система - Debian testing, 64-bit

Если нужны еще какие-то данные дополнительно - скажите.

![Снимок экрана_2019-09-17_14-41-13](https://user-images.githubusercontent.com/54420796/65038719-44236d80-d959-11e9-8b35-4dda83f59179.png)

**Comment by Mc-Seam** [comment]
Добавлю:

Если в качестве выходного формата поставить WAV, т.е. просто распаковка, то получается не совсем хороший wav. Например, soxi на него ругается следующими словами (выходной файл - 01.wav):

$ soxi 01.wav 
soxi FAIL formats: can't open input file `01.wav': WAVE file fmt chunk is too short

$ soxi -t 01.wav 
soxi FAIL formats: can't open input file `01.wav': WAVE file fmt chunk is too short

$ soxi -t -V5 01.wav 
soxi INFO formats: detected file format type `wav'
soxi DBUG wav: Searching for 66 6d 74 20
soxi DBUG wav: WAV Chunk fmt 
soxi FAIL formats: can't open input file `01.wav': WAVE file fmt chunk is too short

Получившийся wav не открывается, например, Audacity, не проигрывается mpv и т.д.

**Comment by SokoloffA** [comment]
Первое, проверь место на дисках, и на диске с выходными файлами, и если в настройках указана временная директория, то и в ней.

Проверь flac, запусти ```flac -d "Argo - 1981-Svet.flac"```, и проверь soxi полученный WAV файл. 

Пришли мне свой конфиг, он лежит в ~/.config/flacon/.  Можешь переименовать его в flacon.conf.bak, программа при запуске пересоздаст его по новой.

Еще интересно посмотреть на шапку битого WAV-а 
```
head -c 40960 BAD_AUDIO.wav | gzip > bad_audio.gz
```

**Comment by Mc-Seam** [comment]
Места на дисках навалом.

На исходных файлах flac -t выдает ОК, flac -d выдает нормальный, играемый wav-файл. У меня, собственно, был невысказанный вопрос - чем распаковывает файлы flacon.

------flacon.conf---------
[General]
Resample_SampleRate=0

[Aac]
Bitrate=256
Quality=100
UseQuality=true

[ConfigureDialog]
Height=638
Width=674

[Cover]
Mode=Scale
Size=500

[Encoder]
ThreadCount=8
TmpDir=/tmp

[Flac]
Compression=5
ReplayGain=Disable

[Inet]
CDDBHost=freedb.freedb.org

[MainWindow]
Height=787
Splitter=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\x80\0\0\x1\0\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
TrackView=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\a\0\0\0\0\0\0\0\x3\0\0\0\x4\0\0\0\x1\0\0\0\x2\0\0\0\x5\0\0\0\x6\0\0\0\a\0\0\0\0\0\0\0\x3\0\0\0\x4\0\0\0\x1\0\0\0\x2\0\0\0\x5\0\0\0\x6\0\0\0\a \0\0\0\x1\0\0\0\x5\0\0\0\x64\0\0\x4\x62\0\0\0\a\x1\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\a\0\0\0\xc8\0\0\0\x1\0\0\0\0\0\0\0\x91\0\0\0\x1\0\0\0\0\0\0\0y\0\0\0\x1\0\0\0\0\0\0\0\x42\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\x1\xea\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\0\0\0\x64)
Width=1521

[Misc]
LastDirectory=/home/maksim/Netshares/SS20/1/CAM/\xa9 1979 Rockets - Plasteroid (AT-Onkyo)

[Mp3]
Bitrate=320
Preset=cbrKbps
Quality=4
ReplayGain=Disable

[Ogg]
MaxBitrate=@Invalid()
MinBitrate=@Invalid()
NormBitrate=@Invalid()
Quality=7
ReplayGain=Disable
UseQuality=true

[Opus]
Bitrate=96
BitrateType=VBR

[OutFiles]
Directory=~/500GB/OUTPUT
DirectoryHistory=~/500GB/OUTPUT
Format=WAV
Pattern=%a - {%y} - %A/%n - %t
PatternHistory=%a - {%y} - %A/%n - %t, %a -{ %y }- %A/%n - %t, %a - { %y } - %A/%n - %t, %a -{ %y } - %A/%n - %t

[PerTrackCue]
Create=true
FileName=%a-%A.cue
Pregap=Extract

[Programs]
faac=
flac=/usr/bin/flac
lame=/usr/bin/lame
mac=/usr/bin/mac
metaflac=/usr/bin/metaflac
mp3gain=
oggenc=/usr/bin/oggenc
opusenc=
sox=/usr/bin/sox
ttaenc=
vorbisgain=
wavpack=/usr/bin/wavpack
wvgain=/usr/bin/wvgain
wvunpack=/usr/bin/wvunpack

[Resample]
BitsPerSample=0

[Tags]
DefaultCodepage=UTF-8

[WV]
Compression=1
ReplayGain=Disable

---------закончился flacon.conf---------

 $flac -d '/Argo - 1981-Svet.flac' 

flac 1.3.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

Argo - 1981-Svet.flac: done         
$ soxi '/Argo - 1981-Svet.wav' 

Input File     : '/Argo - 1981-Svet.wav'
Channels       : 2
Sample Rate    : 96000
Precision      : 24-bit
Duration       : 00:38:32.40 = 221990400 samples ~ 173430 CDDA sectors
File Size      : 1.33G
Bit Rate       : 4.61M
Sample Encoding: 24-bit Signed Integer PCM

$ soxi -t -V5 '/Argo - 1981-Svet.wav' 
soxi INFO formats: detected file format type `wav'
soxi DBUG wav: Searching for 66 6d 74 20
soxi DBUG wav: WAV Chunk fmt 
soxi INFO wav: EXTENSIBLE
soxi DBUG wav: Searching for 64 61 74 61
soxi DBUG wav: WAV Chunk data
soxi DBUG wav: Reading Wave file: Microsoft PCM format, 2 channels, 96000 samp/sec
soxi DBUG wav:         576000 byte/sec, 6 block align, 24 bits/samp, 1331942400 data bytes
soxi DBUG wav:         221990400 Samps/chans
soxi DBUG wav: Searching for 4c 49 53 54
wav




[bad_audio.gz](https://github.com/flacon/flacon/files/3622773/bad_audio.gz)

**Comment by SokoloffA** [comment]
> чем распаковывает файлы flacon
FLAC-и [flac-ом и распаковывает](https://github.com/flacon/flacon/blob/master/formats/flac.cpp#L40), вызывает 
```
flac -c -d -s fileName.flac - |  читает выхлоп с STDIN-а
```

Похоже бага, и у меня 24x94 битый получается.

**Comment by SokoloffA** [comment]
Да, баг.  Flac между 1.32 и 1.33 стал возвращать немного другой WAV. Завтра починю.

**Comment by Mc-Seam** [comment]
> Да, баг. Flac между 1.32 и 1.33 стал возвращать немного другой WAV. Завтра починю.

Офигеть ! Как такое может быть ?

С другой стороны, я сейчас скачал какой-то 24-битный APE - с ним все работает, пилится и играет.

**Comment by SokoloffA** [comment]
Проблема возникает только если входной файл это FLAC. Flacon запускает flac для декодирования файла и считывает WAV данные. Но этот WAV для всего входного файла, а мне нужен WAV только для одного трека, поэтому я беру только кусок, и еще надо поменять заголовок WAV-а. По крайней мере надо менять длину файла (она указывается в  заголовке WAV-а). Измененный WAV я или сохраняю (если выходной формат WAV) или скармливаю кодировщику.

В [заголовке WAV-а](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html) есть поле **wFormatTag** оно описывает формат. 
В версии 1.32 и для SD и для HD flac возвращал **0001  WAVE_FORMAT_PCM**, а теперь для HD стал возвращать **FFFE WAVE_FORMAT_EXTENSIBLE**. Я копирую это поле в выходной WAV, но EXTENSIBLE требует еще полей в заголовке, а их я не заполнял. Вот и получается битый WAV на выходе.

Т.е. проблема у меня, но стала актуальной после изменений в flac.

**Comment by SokoloffA** [comment]
Задачка оказалась чуть сложнее, чем я думал. Надеюсь на выходных починю и сделаю релиз.
 
Чтоб тебе не ждать фикса, можешь сделать следующее, перегони исходный файл в WAV, а потом в другой формат, например в APE. И разбей во флаконе.
```
flac -d "Argo - 1981-Svet.flac"
mac "Argo - 1981-Svet.wav" "Argo - 1981-Svet.ape" -c1000
flacon "Argo - 1981-Svet.ape"
```

**Comment by SokoloffA** [comment]
I fixed your issue.

**Comment by Mc-Seam** [comment]
Добрый день,

Извинте, всё время забываю написать спасибо. Все  замечательно работает.
