### ISSUE TITLE
Include appdata.xml in build system

### ISSUE THREAD

**Issue by Eonfge** [flacon/flacon#101]
Could you include an appdata.xml in the build?

Right now, package maintainers have to manually add an xml to provide details like age ratings, so it would be beneficial if you could add that to the project.

Here more info:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by Eonfge** [comment]
For Flathub, I currently made this metadata file:
[com.github.Flacon.appdata.xml.txt](https://github.com/flacon/flacon/files/3656975/com.github.Flacon.appdata.xml.txt)

**Comment by SokoloffA** [comment]
As I uderstand, when the user install the program, file /usr/share/minfo/com.github.flacon.metainfo.xml should be installed too.
No problem, but strange to get metainfo file only after the program was installed.

**Comment by Eonfge** [comment]
Not sure how it happens, but when using flathub, it couldn't find the metadata:
https://flathub.org/builds/#/builders/32/builds/8894

Btw, I hope you don't mind that I submitted your app to Flathub. I wanted to start the review process because I'll have less time to contribute starting next week

**Comment by SokoloffA** [comment]
>Not sure how it happens, but when using flathub, it couldn't find the metadata:

I made a mistake, now [it's fixed](https://github.com/flacon/flacon/commit/3f3677531bec50ba35fe990b00b66a1d1a3ec63c). 

>Btw, I hope you don't mind that I submitted your app to Flathub. I wanted to start the review process because I'll have less time to contribute starting next week

I'm glad.

**Comment by SokoloffA** [comment]
How should the file be called com.github.Flacon.**appdata**.xml or 
com.github.Flacon.**metainfo**.xml?

**Comment by Eonfge** [comment]
I still call it `appdata.xml`, but now that I'm reading the documentation again, it's apparently now officially called `metainfo.xml`. [2.2.1](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html) consistently calls it metainfo, and it refers to appdata as valid for legacy compatibility.

So while you're at it, might just as well  call it `metainfo.xml`

**Comment by SokoloffA** [comment]
Also one question:
Should I write my email address in the **<update_contact/>** tag?

**Comment by Eonfge** [comment]
@SokoloffA The update_contact is intended for the person in charge of the metainfo. Since you're now updating it, it should be you. It does feel a bit superfluous in a time of Github, Gitlab, etc
