### ISSUE TITLE
Rename incorrect in issue #101

### ISSUE THREAD

**Issue by Eonfge** [flacon/flacon#102]
I found a small mistake in issue #101, caused by all confusing naming schemes.

When renaming `appdata.xml`, you renamed it to `metadata.xml`
The file should be called: `metainfo.xml`

**Comment by SokoloffA** [comment]
Done

**Comment by Eonfge** [comment]
Found a type as well.
```
  <launchable type="desktop-id">io.github.Flacon.desktop</launchable>
```

should be
```
  <launchable type="desktop-id">com.github.Flacon.desktop</launchable>
```
