### ISSUE TITLE
Correct CMake policy CMP0058 warnings

### ISSUE THREAD

**Issue by scottfurry** [flacon/flacon#104]
When building w/ Ninja, CMake will issue the following warning:
```
CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  This project specifies custom command DEPENDS on files in the build tree
  that are not specified as the OUTPUT or BYPRODUCTS of any
  add_custom_command or add_custom_target:

   translators.info

  For compatibility with versions of CMake that did not have the BYPRODUCTS
  option, CMake is generating phony rules for such files to convince 'ninja'
  to build.

  Project authors should add the missing BYPRODUCTS or OUTPUT options to the
  custom commands that produce these files.
```

Warning appears when a generated file cannot be correctly associated with a build target.
(see [CMake Docs - CMP0058](https://cmake.org/cmake/help/latest/policy/CMP0058.html),  [QTBUG-71354](https://bugreports.qt.io/browse/QTBUG-71354) ).

To correct, suggestion is usage of `add_custom_command` to declare the translators.info file as output of target. (see this [blog post](https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/), [CMake Docs - Build Events](https://cmake.org/cmake/help/latest/command/add_custom_command.html#build-events), [Debian - CMake Policies CMP0058](https://manpages.debian.org/stretch/cmake-data/cmake-policies.7.en.html#CMP0058) ).

Attaching a patch file to correct and silence warning. Patch creates a "translators" target and then assigns the output to a custom command to be executed `PRE_BUILD`. The variable `TRANSLATORS_INFO_FILE` is pulled out of the function `create_translatorsinfo_qrc` to the start of the included file `translations/translatorsinfo.cmake` to be available in global scope. The call to `create_translatorsinfo_qrc` is then wrapped in a `add_custom_command` call with `TRANSLATORS_INFO_FILE` is a byproduct.

Local testing on a Gentoo-based linux found no problems in configure/build with changes in attached patch file.
[flacon-5.5.1-resolve-cmp0058.txt](https://github.com/flacon/flacon/files/3747285/flacon-5.5.1-resolve-cmp0058.txt)

**Comment by SokoloffA** [comment]
It's very strange ninja behavior. The project depends only on the .qrc file, but I should to additional declare .info file. I read your links and it's real so, therefore I added your patch. Many thanks!

**Comment by scottfurry** [comment]
I was trying to update the Gentoo ebuild file (instructions for building - source based distribution) to latest. They were behind a major revision. However, this issue cropped up during the build process. I thought I could do something about it at least.

If the dependency is the qrc file, that may be usable as the "OUTPUT" of the add_custom_command ("OUTPUT" as described in links above - BYPRODUCT would still be translators.info - generated file during pre-build).

HTH. Hopefully less work for a package maintainer. :wink:
