### ISSUE TITLE
Split WavPack files with sample rate greater than 192KHz

### ISSUE THREAD

**Issue by Fef0** [flacon/flacon#109]
Hi, first of all great project!
I'm trying to split some WavPacks with a sample rate of 384Khz but when I import the relative .cue and files, it says that "A maximum sample rate of 192000 Hz is supported by this format. This value will be used for encoding".
I also tried to unpack the WavPack to WAV first, and then edit the .cue accordingly, but the error is the same.
Is possible to keep the original sample rate? 

Thanks in advance!

**Comment by SokoloffA** [comment]
Hi! 
Yes, some time ago I added limit for maximum sample rate. I don't remember for why i did it, perhaps some output format has limitation. But which, I don't remember. 
Now limitation is 192kHz, I'll increase it. 

Somebody know where I can find limits of maximum sample rates and bitrates for following formats? 
* Wav
* Flac
* Aac
* Mp3
* Ogg
* WavPack
* Opus

**Comment by Fef0** [comment]
Hey, I did a research and found those values:
- Wav - Shouldn't have any limit since it is uncompressed
- Flac - 655350 Hz
- Aac - 192000 Hz
- Mp3 - 48000 Hz
- Ogg - 192000 Hz
- WavPack - 16777216 Hz
- Opus - 48000 Hz

I found them here: https://en.wikipedia.org/wiki/Comparison_of_audio_coding_formats#Technical_details

Hope this will help you!

**Comment by Fef0** [comment]
A quick update.
I modified the source a little bit to be able to split those big files anyway.
I added a new field into types.h class SampleRate, line 142, called ```Hz_768000``` with value 768000 and then changed line 60 of outformat.h into ```virtual SampleRate    maxSampleRate() const { return SampleRate::Hz_768000; }```. 
This fixes the issue for now and it's just a quick (and dirty) way.

**Comment by SokoloffA** [comment]
Supports in 6.0.0
