### ISSUE TITLE
Feature: Support for embedded Cue Sheets

### ISSUE THREAD

**Issue by maxmitti** [flacon/flacon#110]
It would be nice to have support for embedded cue sheets.
The only difference to external cue sheets is, that the cue sheet contents are stored in a tag in the audio file instead of in an external file.

**Comment by brainchild0** [comment]
Do embedded cue sheets have a strong use case? 

I experimented with them years ago, but finding poor support in players, realized that external cue sheets was the approach most individuals used for managing their collections.

**Comment by maxmitti** [comment]
I have only really tried MPD and it works fine.
I have already embedded all my cue sheets, however it is easy enough to extract them again, should the need arise.

**Comment by brainchild0** [comment]
It might be helpful to clarify which audio formats you use, have used, have seen supported elsewhere, or would want supported in Flacon.

**Comment by maxmitti** [comment]
I have mostly FLAC and few WavPack files.

**Comment by brainchild0** [comment]
After learning more about embedded cue sheets, I  realize this feature is much more useful than I personally had understood.

For FLAC files, I originally avoided embedded cue sheets because FLAC only allows TOC data, not textual data (e.g. artist, title), in embedded cue sheets. I understood that an external cue sheet was necessary to include the textual metadata in the collection.

However, many applications support inclusion of textual information about individual songs through tags in whole-album FLAC files through the convention appending a track number surrounded by a square brace pair to a tag name.

As such, the title of the  first track is given with the following tag information:

```
TITLE[1]=Rocky Mountain High
```

Flacon could offer full support for song metadata through this convention.

In addition, WavPack supports inclusion  of  textual data in embedded cue sheets.

**Comment by maxmitti** [comment]
Sorry, I just realized that I did not say clearly what I meant.
The embedded cue sheets I encountered and use myself are the contents of the regular external cue-file stored as a tag named `cuesheet` in the flac file. And it is a normal tag, not the specific cuesheet that does not support textual data.

For example it can be embedded as follows:
```
metaflac --set-tag-from-file=cuesheet=album.cue album.flac
```

**Comment by brainchild0** [comment]
Yes, that convention is used too. I have no information about which conventions are understood   by various players applications.

**Comment by maxmitti** [comment]
I know that MPD supports the TOC-only FLAC cue sheet, as well as the cue sheet tag for I mentioned, for FLAC and also for various other file formats.
It also supports the WavPack cue sheets that you have discovered.

However, I am not sure whether it supports the “array style” tags you found:
```
TITLE[1]=Rocky Mountain High
```

**Comment by brainchild0** [comment]
I am not sure either, but MusicBrainz seems to have adopted this convention, as seen in the [Picard](https://picard.musicbrainz.org/) application, so I hope MPD and other popular players follow, if they have not done  already.

**Comment by MountainX** [comment]
> For example it can be embedded as follows:
> ```
> metaflac --set-tag-from-file=cuesheet=album.cue album.flac
> ```
>
> however it is easy enough to extract them again, should the need arise.


Hello. I'm slightly off topic, but what is the process and tool to extract them again? (I'm running Linux, of course.)

**Comment by brainchild0** [comment]
Perhaps open a thread on [HydrogenAudio](https://hydrogenaud.io/) if you have general questions about managing audio files.

**Comment by maxmitti** [comment]
For FLAC you can use `metaflac --show-tag=cuesheet file.flac` (and remove the leading `cuesheet=` from the output).
For others please do your own research.

**Comment by SokoloffA** [comment]
Sorry guys, I've been very busy lately. But I'm not quitting the program, I hope to find time to develop.

**Comment by SokoloffA** [comment]
Guys, I don't quite understand what you mean by MPD support.

1. If you are talking about per-track audio files, why do you need MPD support? Each track contains normal tags metadata for its own track.
2. If you are talking about an non-splitted audio file for the entire album, then what does my program have to do with it?

I only see one usecase for the embedded CUE file. If you have a set of splitted audio and want to get the original audio file for CD burning. Then you can extract the CUE from any track file (metaflac --show-tag=cuesheet) and join tracks together with regaps. Again, what does MPD have to do with it?

Now I am adding support like `metaflac --set-tag-from-file=cuesheet=album.cue` for FLAC format. And I'll see what other formats support a similar option. If you need more, then please give me more information.

**Comment by brainchild0** [comment]
The general request is that the input is a whole-disc audio file with an embedded cue sheet, and the output is one audio file per track.

It is the same as the current operation, except that currently, as I understand, the cue sheet is always a separate file from the audio file.

In the case of FLAC files, embedded cue sheets may appear through the `cuesheet` tag, or directly through embedded cue sheet support in the FLAC format.

Direct support of embedded cue sheets in FLAC does not support text information such as title, artist, date, and so on, which is the reason why some prefer to use the `cuesheet` tag instead.

**Comment by SokoloffA** [comment]
Done in https://github.com/flacon/flacon/commit/68da4e0bd1b52898db33fcbfda17e2e90f2d1e4d

**Comment by maxmitti** [comment]
I just tried 7c3e1d468d3afeb2f1fae1ebe2de86e33e85c6c1. Unfortunately it doesn’t seem to work.

When I choose `Add disc` and select the flac with the `cuesheet` tag set, it says the conversion is not possible because no cue file is set.
I have also tried the flac specific cuesheet with metaflac’s --import-cuesheet-from leading to the same result.

I’ll try to find out what’s happening with the debugger.

**Comment by SokoloffA** [comment]
I misunderstood you, I thought you wanted to embed CUE in output files.

**Comment by maxmitti** [comment]
Oh, I am sorry about that. So I won’t try to debug it anymore.

**Comment by brainchild0** [comment]
Embedded cuesheet for output would make sense in the context of #98, because I think embedding usually applies to the formatting case of the entire album captured in a single audio file.

So, yes, this request is for embedding in input files.

**Comment by maxmitti** [comment]
> So, yes, this request is for embedding in input files.

Yes, but Flacon’s task would be to read the already embedded cue sheet instead of a separate cuesheet file.
Just saying to avoid further confusion by ambiguous choice of words.

I understand that it is more work because so far Flacon didn’t need to read any tags from audio files directly.
Don’t feel compelled to implement it. It would be just a nice to have, at least speaking for myself.

**Comment by SokoloffA** [comment]
Guys, I've added support for the embedded CUE for input  FLAC files. Please note that taglib is now required for the build. 
Commit - https://github.com/flacon/flacon/commit/c37380f35dce8fd987588659622facc11f8c8473

**Comment by maxmitti** [comment]
Very cool. Now it worked first try. Thank you very much!
