### ISSUE TITLE
Flacon install on Raspberry pi

### ISSUE THREAD

**Issue by etiennedemoulin** [flacon/flacon#111]
Hi,
I follow Debian 9 step's to install Flacon on my Raspi, but it doesn't work.
Unless i update my /etc/apt/sources.list file with opensuse repo, i can't find flacon in my packages.

Thank's for all

**Comment by SokoloffA** [comment]
Unfortunately, I build deb packages only for i586 and x86 architectures. So you will have to build the program from the source code, [this document](https://github.com/flacon/flacon/wiki/How-to-build) may be useful for you.
