### ISSUE TITLE
(feature request) flacon appimage

### ISSUE THREAD

**Issue by ghost** [flacon/flacon#112]
please consider adding a linux flacon appimage build.

**Comment by SokoloffA** [comment]
[Flatpak](https://github.com/flacon/flacon/releases/download/v5.5.1/Flacon.flatpak) won't suit you?

**Comment by ghcatt** [comment]
thank you for replying.

at first glance, flatpak and snaps seem similar, but in fact are a different story. see the link for more info: https://github.com/AppImage/AppImageKit/wiki

here is some of the benefits of appimages:

Providing an AppImage for distributing application has, among others, these advantages:

    Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
    One app = one file = super simple for users: just download one AppImage file, make it executable, and run
    No unpacking or installation necessary
    No root needed
    No system libraries changed
    Works out of the box, no installation of runtimes needed
    Optional desktop integration with appimaged
    Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
    Can optionally GPG2-sign your AppImages (inside the file)
    Works on Live ISOs
    Can use the same AppImages when dual-booting multiple distributions
    Can be listed in the AppImageHub central directory of available AppImages
    Can double as a self-extracting compressed archive with the --appimage-extract parameter

**Comment by ivnish** [comment]
+1 for appimage

**Comment by SokoloffA** [comment]
It's happened!

I published [AppImage](https://github.com/flacon/flacon/releases/download/v9.5.1/flacon-9.5.1-x86_64.AppImage) package for the program. Unfortunately, I have no way to check it.  
I will be happy if you try this version

**Comment by lexterror** [comment]
Thank you so much. I also want the Appimage version. Im going to try it out on both PopOs and Kubuntu... I will let you know if it runs ok. Thank you!

**Comment by SokoloffA** [comment]
You can download the latest version in the [releases section.](https://github.com/flacon/flacon/releases/tag/v9.5.1)

**Comment by lexterror** [comment]
It runs without issues on my computers... Thank you!
