### ISSUE TITLE
Clarification needed - preservation of encoding (improvement ?)

### ISSUE THREAD

**Issue by beng7** [flacon/flacon#113]
Hi
Sorry this is not a bug report but just a mere question, to which I could not find any answer so I thought I would ask here;
I have flac files & cue files, the flac files are already encoded to settings that may be different from those set by default in Flacon; my question is, when I get Flacon to cut the flac file into separate songs, are the original encoding settings preserved or are every single song re-encoded to the default flac settings in Flacon ?
If the latter is currently true, it would be nice to have a pass thru option preserving the original encoding as re-encoding lowers the quality)
Thanks in advance for your answer.

**Comment by SokoloffA** [comment]
You're not the first person who [worry about this](https://github.com/flacon/flacon/issues/103). So I added the answer to the [FAQ.](https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions) 

In short is not a problem because the FLAC is a lossless codec. You can compress and decompress into/from this format many times without losing quality.

**Comment by beng7** [comment]
Hi Alexander
Thank you for your prompt answer.
I didn't realise flacon decompressed to wav then re- encoded into flac after splitting the wav. I think the explanation will clarify the point with others too.
Thanks again and thanks for Flacon.
Also I'm thinking, tagging could be improved by allowing capitals at the begining of a song title, not every single word.
Regards
Ben

On February 24, 2020 6:41:12 PM UTC, Alexander Sokolov <notifications@github.com> wrote:
>You're not the first person who [worry about
>this](https://github.com/flacon/flacon/issues/103). So I added the
>answer to the
>[FAQ.](https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions)
>
>
>In short is not a problem because the FLAC is a lossless codec. You can
>compress and decompress into/from this format many times without losing
>quality.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/flacon/flacon/issues/113#issuecomment-590485301

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SokoloffA** [comment]
I don't understand what you mean by tagging could be improved by allowing capitals at the begining of a song title, not every single word. Please explain your idea.
