### ISSUE TITLE
flacon runs seems to work, it shows "OK" after encoding, but no files are output.

### ISSUE THREAD

**Issue by xekon** [flacon/flacon#114]
flacon runs seems to work, it shows "OK" after encoding, but not files are output.

I noticed you can run it from the command line
`flacon .`

and it outputs: Encoding time 17 sec

any chance to have it also print where it stored each file? its definitely not in the same folder as the .cue

there are no new files being generated.

**Comment by SokoloffA** [comment]
Hi, xekon!
The program shows the base directory for output files in the Directory field. If you want to have output files next to input files, leave this field empty.
![flacon1](https://user-images.githubusercontent.com/854935/75619624-9109a200-5b8f-11ea-9c15-a932d3669b02.png)

The full path is shown in the tooltip on the file name. 
![flacon2](https://user-images.githubusercontent.com/854935/75619680-29a02200-5b90-11ea-85df-c82482496a73.png)

When you run a program like: 
``` flacon .```
the dot does not set the output directory, but the directory where the input audio files will be searched.

**Comment by xekon** [comment]
Thank you for the detailed info, going to give this a try within the next couple days. My server had a drive failure and is currently rebuilding the array.
