### ISSUE TITLE
Support ISO images of CD files

### ISSUE THREAD

**Issue by doronbehar** [flacon/flacon#115]
I have an ISO file that's supposed to be a exact copy of a music CD. `file` shows it as:

```
img.iso: UDF filesystem data (version 1.5) '<img>'
```

When I mount it with:

```
sudo mount -o loop /path/to/my-iso-image.iso /mnt/
```

I get the following files in `/mnt`:

```
/mnt/
├── AUDIO_TS
│   ├── ATS_01_0.BUP
│   ├── ATS_01_0.IFO
│   ├── ATS_01_1.AOB
│   ├── ATS_01_2.AOB
│   ├── ATS_01_3.AOB
│   ├── AUDIO_PP.IFO
│   ├── AUDIO_SV.BUP
│   ├── AUDIO_SV.IFO
│   ├── AUDIO_SV.VOB
│   ├── AUDIO_TS.BUP
│   ├── AUDIO_TS.IFO
│   └── AUDIO_TS.VOB
└── VIDEO_TS
    ├── VIDEO_TS.BUP
    ├── VIDEO_TS.IFO
    ├── VIDEO_TS.VOB
    ├── VTS_01_0.BUP
    ├── VTS_01_0.IFO
    ├── VTS_01_1.VOB
    ├── VTS_02_0.BUP
    ├── VTS_02_0.IFO
    └── VTS_02_1.VOB

2 directories, 21 files
```

Last time I checked (don't have access to a windows machine), [foobar2000](https://www.foobar2000.org/) can handle this kind of file, I think via it's DTS input: https://www.foobar2000.org/components/view/foo_input_dts

There's a program that can covert these to a wav file, but without the splitting data - https://github.com/foo86/dcadec .

It would be awesome if flacon would convert these ISOs wav and split them afterwards, as foobar2000 can.

**Comment by ranperry** [comment]
That ISO is of a DVD disc, not CD. You will need to use the following if
you want to extract the audio - http://www.dvdae.com/

**Comment by doronbehar** [comment]
Thanks for replying @ranperry. I don't have windows machine to test that software, but you are right that it is a DVD audio ISO - that's how VLC opens it. VLC should be capable of converting files it can read but when I tried to do that it returned errors I don't know how to handle.

**Comment by ranperry** [comment]
The program runs on Linux, Mac and Windows.

http://www.dvdae.com/download

**Comment by doronbehar** [comment]
I had trouble making it run on NixOS, due to raw_io capabilities / permissions. I've borrowed a Windows machine to do it and it seems to be operating now. Thank you @ranperry !

BTW for the record, with those specific files, I installed on a Windows machine foobar2000 + plugins that enabled me to open those ISO files, but foobar crashed when I clicked "convert".

**Comment by SokoloffA** [comment]
Sorry for long silent, in this crazy time, everything went wrong.

@doronbehar 
Unfortunately, I don 't plan to add support for DVD-Audio.
1. Flacon is a program that cuts an audio file using CUE. In your case, there is no CUE file. 
2. The DVD-Audio has copy protection, I am not ready to fight with corporations now.
