### ISSUE TITLE
disc information missing from opus output

### ISSUE THREAD

**Issue by brainchild0** [flacon/flacon#119]
Following #66,  some support was added for disc information  in output.

Presently, Flacon is generating `.opus` files and a per-track cue sheet, but neither appears to have the accurate disc information.

From the source cue sheet:

```
REM TOTALDISCS 2
REM DISCNUMBER 2
```

From the Ogg metadata in one of the  output audio files:

```
disc            : 1
DISCTOTAL       : 1
```

Also `REM DISCNUMBER` amd `REM TOTALDISC`   are absent from the output cue sheets.

Version is 6.0.0. Platform is Mint Linux 19.3.

**Comment by SokoloffA** [comment]
Done in the master branch.

**Comment by brainchild0** [comment]
I confirm that the Ogg data shows the correct disc number. 

The cue sheet has not data for disc number or disc count.

**Comment by SokoloffA** [comment]
> The cue sheet has no data for disc number or disc count.
Done.

**Comment by brainchild0** [comment]
Confirmed.
