### ISSUE TITLE
Audio file not set

### ISSUE THREAD

**Issue by DDemyanenko** [flacon/flacon#12]
I have problems with flacon 1.0.1 installed on fedora 21 x86_64. 

Opening cue sheet for both ape and flac (didn't try wavpack) gives an error message: "Conversion is not possible. Audio file not set"

![screenshot from 2015-01-25 23_38_24](https://cloud.githubusercontent.com/assets/10708535/5900154/8d1d46d8-a56e-11e4-857e-bf2ba5a9e2cc.png)

**Comment by SokoloffA** [comment]
* Is you have shntool installed?
* What name has your audio file?
* Please, post content of the CUE file.

**Comment by DDemyanenko** [comment]
I'm so sorry I didn't mention it because I am newbie to fedora, used to use ubuntu where everything installed by default. Shntool was missing

**Comment by SokoloffA** [comment]
I think is a bug in the fedora package. It would be good if you open bug report on fedora bug tracker.

**Comment by DDemyanenko** [comment]
Ok, I will. Thanks again
