### ISSUE TITLE
add "scan" item to main menus

### ISSUE THREAD

**Issue by brainchild0** [flacon/flacon#122]
Currently,  *Scan*   is the only function available in the toolbar but not the main menus of the menu bar. 

Adding  an item *Scan for discs* to the *File* menu seems like a simple but appropriate enhancement.

**Comment by SokoloffA** [comment]
Done

**Comment by brainchild0** [comment]
Confirmed *Scan for discs* changed to *Add folder* and added to *File* menu.

I am not attached to the previous label, but I liked that the language indicates recursive traversal, rather than a flat directory listing.

Do you like *Scan folder*?

**Comment by SokoloffA** [comment]
I think the main idea is that we are **adding** a folder. Some audio players have "Add folder" item in the main menu. For example in DeadBeef or [Foobar](https://news.softpedia.com/images/extra/WINDOWS3/large/foobar2000/foobar2000%20file%20menu.png)

**Comment by brainchild0** [comment]
It is not a big difference, and mostly a matter of opinion. To me *adding* in this case does not communicate recursive traversal, but I might think differently if I had never seen the earlier version.

In the case of players, folders are added to the library, which is a collection of folders that are scanned. The user is already aware of the process of scanning a library,  often being presented as an explicitly separate operation form adding a folder to it. 

Flacon, however, presents no separate scanning concept or operation, so  a user  might not not understand the intention of the language. Of course others may not anticipate any such problem.
