### ISSUE TITLE
overall progress indicator

### ISSUE THREAD

**Issue by brainchild0** [flacon/flacon#123]
During encoding operations, the  application state includes the playback time of all tracks, as well as their encoding  progress. Assuming that encoding tracks is much slower than  decoding  them and saving them to temporary targets,  it is easy to approximate the overall progress of the operation. It would be nice to show the user an indicator that includes time, percentage, or both.

**Comment by SokoloffA** [comment]
Unfortunately, this is not possible. The speed of extracting and encoding depends on many factors.

1. Extraction Speed depends on the input format, for example, it will be very fast for WAV, but much slower for a heavy formats.
2. Extraction Speed depends on the disk speed. For example, I often split disks located on a network share, and the result is saved to the local disk. In this case extraction speed is much slower than the encoding speed.
3. The encoding speed depends on the output format. For WAV, it is zero time, the program just renames the temporary file.
4. The end of the extraction does not mean that encoding will start right at this moment. The program has a limit on the threads number. So, the encoder will wait until thread is free.
5. In addition to extracting and encoding, there is also a replaygain calculation. If you select album-gain mode, the first tracks will wait until the last track is encoded before start calc the replaygain.

**Comment by brainchild0** [comment]
I completely agree that computing an exact quantity is impossible, but indicators are not useful because they give exact information. Indicators are useful  because the  information they give to the user is more accurate  than the information that the user otherwise has available.

Currently, when I run a batch job, I estimate the progress by scrolling to the location in the graphical queue where tracks are currently encoding, then estimating the position of the scrollbar. This method is the best available one currently. The result is  crude but not completely inaccurate. Of course translating to an absolute time is only  possible if I have recorded the starting time.

It is easy to conceive of an approach for giving the application support for a progress indicator at least as reliable as the above method. I suggest assuming that   extraction and filtering have negligible cost compared to encoding, that read speed is uniform for all files, and that the number of tracks is high enough so that during most of the operation, the proportion of total audio already extracted is close the proportion that has been encoded.

Then a completely feasible calculation is the following:

1. Sum the play lengths of all tracks.
2. Sum the play lengths of all tracks for which encoding has completed.
3. For each track for which encoding has partially completed, add to the result from (1) the product of the play length and the  proportion of completed encoding.
4. Divide the results of (3) by (1). The result is the  estimated  total  proportion completed.
5. (Subtract 1 from the inverse of the result from (4), and multiply the resulting quantity by the elapsed time. The result is the estimated remaining time.)

The obvious limitation is the one you suggest, that the input is spread across media accessible by very different speeds. Users have always had to live with the reality that network shares are slower to access than local volumes. The same limitation applies to simple transfer operations, though applications often   give progress estimates.  Anticipating such complications is the  responsibility of  the user, not of the application.

Accuracy may be lost due to the  cost of extraction and filtering compared to encoding, but not so much that the progress indicator has no value to the user.

**Comment by SokoloffA** [comment]
I understand your desire to see overall progress, but the progress bar will be very inaccurate.

>I suggest assuming that extraction and filtering have negligible cost compared to encoding

This is not true. The speed of extraction and encoding depends on the input and output formats. Here is an example, I'm splitting a 32bit 192kHz Wavpack into a CD quality FLAC.
https://www.youtube.com/watch?v=sepfYmdmakM&feature=youtu.be

>I suggest assuming that read speed is uniform for all files

This is not true too. The speed depends on the sample rate and bit rate of the audio. User may select audio with different quality.

As I said I understand you. Maybe following solution will suit you? I can add to status bar information about the number of completed tracks and total number of them.

**Comment by brainchild0** [comment]
> I understand your desire to see overall progress, but the progress bar will be very inaccurate.

Yes, it may be inaccurate in many cases, but we must consider how much so, and how much it matters.  Al progress indicators are  somewhat accurate much of the time and greatly inaccurate some of the time.   Generally, it is understood that they   provide no guarantees, and that their accuracy is constrained by whatever uncertainties occur in some type of    operation.

The purpose of the assumptions is not to offer true statements, but rather, useful ones. By considering them as true hypothetically, we may construct a feasible method for calculating progress. As long as the result of applying the method in many cases is much better than guessing, it is adequate for the needs and expectations of a progress indicator.

As other applications include progress indicators despite their limitations, so might  Flacon.

An estimate is better than a guess, and the user is responsible for considering its reliability.

 
> As I said I understand you. Maybe following solution will suit you? I can add to status bar information about the number of completed tracks and total number of them.


Sure, it would help. But this solution appears to me as one that attempts to compensate for the limited accuracy of certain  information by replacing it with other information with even more limited accuracy,

**Comment by SokoloffA** [comment]
OK. I will test and will try to make an indicator of the remaining time in the status bar. 
But not just now, I found a few issues with current code.

**Comment by brainchild0** [comment]
Sure, it would be great to attempt it whenever you are able.

A further thought is that an elegant layout might be to convert the toolbar into a progress panel, such that while an operation is in progress, the main toolbar buttons are, instead of merely disabled, replaced by a progress bar. The *abort* button might then appear next to the progress bar, also shown only when an operation is in progress.

**Comment by SokoloffA** [comment]
I added the overall completion rate. This will be in the next release.

**Comment by SokoloffA** [comment]
Included in release 11.0.0
