### ISSUE TITLE
Opening .wv file. Flacon stops at extracting

### ISSUE THREAD

**Issue by billy170468** [flacon/flacon#124]
Hi all,
I have tried to open a *.wv file, Hit convert. It stops here: https://imgur.com/a/AS7fvG7

Any ideas?
Cheers
Andy

**Comment by SokoloffA** [comment]
Please run the program from console as 
```
flacon --debug
```
and send me the output

**Comment by billy170468** [comment]
andy@Laptop:~$ flacon --debug
Unknown option 'debug'.

Usage: flacon [options] [file]
Flacon extracts individual tracks from one big audio file

Generic options:
  -s --start                Start to convert immediately.
  -c --config <file>        Specify an alternative configuration file.
  -q --quiet                Quiet mode (no output).
  -h, --help                Show help about options
  --version                 Show version information

Arguments:
  file                      CUE or Audio file

ENVIRONMENT
  FLACON_DEBUG_ENCODER      If variable is set, flacon print the encoder
                            program arguments.
  FLACON_DEBUG_GAIN         If variable is set, flacon print the gain
                            program arguments.
andy@Laptop:~$

**Comment by SokoloffA** [comment]
What version of the program do you use? It seems that not the last.
Try the latest version. I fixed some bugs that might be related to your problem.

For older versions, the command is:
```
FLACON_DEBUG_ENCODER=1 flacon
```

**Comment by billy170468** [comment]
Have emailed output of debug to notifications@github
Cheers
Andy

**Comment by SokoloffA** [comment]
notifications@github.com is a fake email. Please send to my email sokoloff.a@gmail.com

**Comment by billy170468** [comment]
Sent

**Comment by SokoloffA** [comment]
You probably don't have the sox program installed.
In any case, this is a my bug, I need to check the programs more carefully. Thanks!

**Comment by billy170468** [comment]
I installed sox,,, and it worked. 
Thank you for all your help
Cheers
Andy

**Comment by SokoloffA** [comment]
I should to improve programs checking. So I open the issue.

**Comment by SokoloffA** [comment]
Reporting about problems was improved in the 7.0.0 release.

Added informative error messages when the program can’t load an audio file:
* The audio file does not exist.
* The audio file may be corrupted or an unsupported audio format.
* Decoder program is not installed.
* Decoder program is installed in the settings but binary file does not exist.
