### ISSUE TITLE
temp file names and locations

### ISSUE THREAD

**Issue by brainchild0** [flacon/flacon#125]
Currently, Flacon places temporary files, representing uncompressed track data, in the same folder as  intended for the target compressed files.

A disadvantage of this approach is that if an operation aborts abnormally, the files are less likely to be noticed and removed, compared to  use of a different strategy.

An alternative  is to place temporary files at the top level of the  target folder. As such, users are more likely  to notice them sooner.  

Also, if good conventions are followed, subsequent  conversion operations on the same target folder may discover and remove orphaned files.  A good convention is including a PID in the file name, based on a fixed-length naming template. If the application discovers that a PID, resolved by a pattern match on the name of a file found in the directory,   is not in the process table, then it should  delete the file, because it may be assumed to be orphaned.

Also, specific cases, such as writing to a network share, give preference to placing temporary files in an external directory. A configuration option might be helpful for use of a system-default or user-specified location.

**Comment by SokoloffA** [comment]
> An alternative is to place temporary files at the top level of the target folder. As such, users are more likely to notice them sooner.

Disks can be mounted to the different mountpoints.  Therefore, we can only guarantee enough space for the target directory. 
Anyway, I will improve the mechanism for deleting temporary files. I have some ideas.

> Also, specific cases, such as writing to a network share, give preference to placing temporary files in an external directory. A configuration option might be helpful for use of a system-default or user-specified location.

This option is already available.
![Снимок экрана 2020-06-15 в 17 58 17](https://user-images.githubusercontent.com/854935/84676301-04b09e80-af36-11ea-96fa-50c543e2143d.png)

**Comment by brainchild0** [comment]
> Disks can be mounted to the different mountpoints. Therefore, we can only guarantee enough space for the target directory.

"The top level of the target folder" means the directory selected by the user. Everything under it is created by Flacon, so they are very unlikely to be mountpoints.

**Comment by SokoloffA** [comment]
>Currently, Flacon places temporary files, representing uncompressed track data, in the same folder as intended for the target compressed files.

In version 6.0.0, garbage removing has been improved. The program saves uncompressed WAV files in a temporary directory and deletes this dir after the conversion is finished or interrupted. 

But I noticed that files like track-0001_03.encoded.flac remain after the conversion was interrupted. This is my mistake, thanks for the kick! I fixed this, now such files are placed in a temporary directory and deleted too.

**Comment by brainchild0** [comment]
I think these are good changes.

A few ideas:

- From [`discpipline.cpp`](https://github.com/flacon/flacon/blob/c5946f3b82fac11d8766e983c5231043f2d44025/converter/discpipline.cpp#L215:L217) and [`track.cpp`](https://github.com/flacon/flacon/blob/c5946f3b82fac11d8766e983c5231043f2d44025/track.cpp#L318:329), it appears that a directory called `flacon` is created inside one of constructed directories for the target tracks. To help the user notice  any  remaining files from a failed operation, it may slightly better if that directory:
   - were directly under the target directory of the entire operation (the UI field *Result Files* / *Directory File*).
   - had a name that clearly indicates temporary files, such as `flacon_tmp` or `tmp.flacon`.
- You might  clear this directory *before* beginning the operation, as well as removing it after, in order to prevent an accumulation in case of successive failed attempts. This strategy of course is a very defensive one.

Also, sorry to be picky, but the [Qt documentation](https://doc.qt.io/qt-5/qdir.html#filePath) suggests that `QDir::filePath()` is the preferred means to construct platform-safe paths, rather than inserting literal `/` characters.

**Comment by SokoloffA** [comment]
> were directly under the target directory of the entire operation (the UI field Result Files / Directory File).

I don't want to move temporary files to the top directory. The user can have a pattern with prefix, like "hd_music/%a/{%y -} %A/%n - %t". And have a large disk mounted to hd_music. Accordingly, there may not be enough space on the disk.  I think it is more correct to make that the program correctly delete temporary files.



> had a name that clearly indicates temporary files, such as flacon_tmp or tmp.flacon.

Done



> You might clear this directory before beginning the operation, as well as removing it after, in order to prevent an accumulation in case of successive failed attempts. This strategy of course is a very defensive one.

This is exactly what the program does.



> Also, sorry to be picky, but the Qt documentation suggests that QDir::filePath() is the preferred means to construct platform-safe paths, rather than inserting literal / characters.

I don't see where documentation suggests to use QDir::filePath(). But I see:

_**QDir::separator()**
You do not need to use this function to build file paths. If you always use "/", Qt will translate your paths to conform to the underlying operating system._
https://doc.qt.io/qt-5/qdir.html#separator

I actually use both QDir::filePath and `/` literal.

**Comment by brainchild0** [comment]
Sorry, I missed the documentation about file paths and the code about clearing the directory, if it already exists, *before* the operation begins.

Regarding the location of the temporary directory, in your example, wouldn't all of the content, temporary and final, be written to the same store, in which `hd_music` is mounted, in both cases? It seems to me that putting the temporary content in the lower directory would never affect which mount receives the data.

**Comment by SokoloffA** [comment]
>code about clearing the directory, if it already exists, before the operation begins.
Each conversion creates a new temporary directory, so we don't need to clean temporary dir.

**Comment by brainchild0** [comment]
My idea is to clean it anyway.

The reason is a fringe case, but it's worth considering.

Suppose there is a problem with completing the operation, such as a bug in the application. Then the user begins an operation. The application creates temporary files, then crashes, leaving the files. The user tries the operation again. The application creates temporary files, then crashes, leaving further temporary files. The user tries the operation again...  Now temporary files from three operations have accumulated, which the user might not even know exist.

By cleaning the directory before creating any files, it is guaranteed that the contents never exceed those created from one operation.

**Comment by SokoloffA** [comment]
This can be done, but not so easily. I need to check not only that the PID in the directory name isn't ours, but also that the program with this PID is not running. A few instances of the program can be running at one time.

I have a different solution. Run a separate process. This process will delete temp directories when the main process is closed (normal or crash).


I'll do it but some later.

**Comment by brainchild0** [comment]
Yes, you would need  to check the process table to allow concurrent operations and clean up after earlier operations. At the moment, the file names have a random or hash string but no PID?

**Comment by SokoloffA** [comment]
I have improved the checks and clearing of temporary files. I hope that fixed the problems.
