### ISSUE TITLE
freedb.org is dead

### ISSUE THREAD

**Issue by tehpeh** [flacon/flacon#126]
CDDB lookups are not working for me today. If it uses freedb.org that domain now redirects to www.magix.com.

Alternatives could be:

- http://www.gnudb.org/howto.php (a drop-in replacement)
- https://musicbrainz.org/ (seems to have a completely different API)

**Comment by SokoloffA** [comment]
I will fix this in the next release.
Right now, you can change CDDB host in the config file.

Linux
-----
Open config file ~/.config/flacon/flacon.conf
Find and replace *CDDBHost=freedb.freedb.org* on *CDDBHost=www.gnudb.org*

MacOS
-------
Open a terminal and run the following command:
```
write com.flacon.flacon Inet.CDDBHost -string www.gnudb.org
```

**Comment by tehpeh** [comment]
Thank you!
