### ISSUE TITLE
Does not build on platforms without 64-bit atomics support

### ISSUE THREAD

**Issue by q66** [flacon/flacon#127]
Since 9c43405994b89760c69d3480aee8805a6937f275, this no longer builds on platforms without hardware support for 64-bit atomics (such as armv6, MIPS, and 32-bit powerpc). While 64-bit atomics can be emulated on these platforms (via libatomic) and standard C++11 atomics work, Qt atomics do not.

Does this really need a 64-bit counter? Seems to me a 32-bit one would suffice just fine.

**Comment by SokoloffA** [comment]
Wow, I didn't know that my program is used on armv6, MIPS, and 32-bit powerpc!
Yes, you are right. I used int64 just in case. 32 bit ought to be enough for anybody :)

**Comment by q66** [comment]
At very least distributions package it; 32-bit ppc has a fully working desktop stack and hardware capable enough to use it, armv6 is still the baseline used by say, Raspbian so it may be used by rpi users. MIPS i dunno

**Comment by SokoloffA** [comment]
I knew that the program works under exotic OS, for example there is a package under OS/2. Now I know about architectures.

It would be great if you checked is the program builds after my fix.

**Comment by q66** [comment]
I already patched this in our distro in the same manner before your fix https://github.com/void-linux/void-packages/commit/54626e4c9b165b6b48b2d8e15f0e197a9f59d657 and it was fine so your fix is also fine

**Comment by SokoloffA** [comment]
So I close the issue.

**Comment by q66** [comment]
yep, thanks

**Comment by SokoloffA** [comment]
Kick me if anything goes wrong.
