### ISSUE TITLE
Not Found Key

### ISSUE THREAD

**Issue by Rainman-tux** [flacon/flacon#129]
root@debian:/home/rain# wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10.0/Release.key -O- | apt-key add -
--2020-07-23 12:34:12--  http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10.0/Release.key
Распознаётся download.opensuse.org (download.opensuse.org)… 195.135.221.134, 2001:67c:2178:8::13
Подключение к download.opensuse.org (download.opensuse.org)|195.135.221.134|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 404 Not Found
2020-07-23 12:34:12 ОШИБКА 404: Not Found.

gpg: не найдено данных формата OpenPGP.

**Comment by RaSla** [comment]
```console
# LC_ALL=C wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10.0/Release.key
--2020-07-23 12:57:37--  http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10.0/Release.key
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-23 12:57:37 ERROR 404: Not Found.
```

**Comment by SokoloffA** [comment]
Fixed the instructions on the [downloads page](https://flacon.github.io/download/). 
Correct URL is http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10/Release.key
