### ISSUE TITLE
Support CUE files with several FILE tags

### ISSUE THREAD

**Issue by hellpe** [flacon/flacon#13]
Some CUE files contain more than one FILE tag (for splitting several FLAC files, for instance). When trying to open these files with Flacon, an error message tells that "These CUE files are not supported yet".

**Comment by SokoloffA** [comment]
This feature was done in the (MultiFile branch)[https://github.com/flacon/flacon/tree/MultiFile].
Please test it, is it work for you. If you have skills, you can build the project from sources:

```
git clone https://github.com/flacon/flacon.git --branch MultiFile 
cd flacon 
mkdir build 
cd build 
cmake ..
make 
sudo make install
```

If you haven't such skill, say me what distro you are use and I try to build program for you.
