### ISSUE TITLE
Resquest: better icons for dark themes

### ISSUE THREAD

**Issue by glaubersm** [flacon/flacon#130]
My screenshot shows flacon 6.1.0 on Arch Linux running KDE Plasma 5.19.4 desktop environment with Breeze Dark theme enabled in System Settings > Global theme. The current icons don't look good with dark themes and consequently the buttons look disabled.

![flacon](https://user-images.githubusercontent.com/15967631/88955092-d383f780-d271-11ea-99da-4b770d212983.png)

**Comment by SokoloffA** [comment]
Done
