### ISSUE TITLE
"Audio File not set"

### ISSUE THREAD

**Issue by guachita** [flacon/flacon#132]
Hi friends I am new on Github. I'm using flacon on Linux Mint since long time and never have problems. Recently I format and install 20 version of Mint and version 6.1.0 of Flacon.
I want to convert different cue+flac files to wav and appears the message "Conversion not possible - Audio File not set". It happens with diferents cue+flac even with one that was converted before formatting my pc. I found this link talking about it https://github.com/flacon/flacon/issues/31 and last post is 

_@Treeant34
Now flacon don't use shntool, so I hope this problem is gone._

It seems not gone certaintly.

**Comment by guachita** [comment]
I found the solution. I installed via flatpak and if I install via ppa it works perfect.

**Comment by SokoloffA** [comment]
Sorry for the long silence, I was offline  these days.
I understand that the question is no longer relevant. I write for those who will face a problem in the future.

Most often, problems occur if the necessary codec programs are not installed. This problem does not occur under Mac, all the necessary codecs are included in the app bundle. Under Linux, the program uses codecs from standard packages.

To make sure that all codecs are installed, open the *Programs* tab in the *Preferences* window. And make sure that all the fields are filled in.
