### ISSUE TITLE
Chinese and Japanese characters output to music information becomes ###

### ISSUE THREAD

**Issue by Lhatna7N0l** [flacon/flacon#133]
It seems flacon can read Chinese and Japanese characters correctly,but unable to write them out to file information.Is there any chance to have it fixed,or perhaps I had got a wrong setting?

![2020-08-24 10-44-01](https://user-images.githubusercontent.com/70121073/90998508-d8309700-e5f6-11ea-84de-9200b89f02c9.png)
![2020-08-24 10-19-34](https://user-images.githubusercontent.com/70121073/90997268-ac5fe200-e5f3-11ea-933e-f6fa8c6c9850.png)
![2020-08-24 10-23-13](https://user-images.githubusercontent.com/70121073/90997359-e8934280-e5f3-11ea-87bb-4491e4039b9f.png)

**Comment by SokoloffA** [comment]
Sorry for the long silence, I was offline these days.

Try to change the "Codepage" in the main window.
![image](https://user-images.githubusercontent.com/854935/92305149-103bc080-ef8d-11ea-9ef2-d0e7224e8c56.png)

If it doesn't help, send me the CUE file.

**Comment by Lhatna7N0l** [comment]
It doesn't work,none of the code works for me.Choosing any code makes things worse,the filename and directory name become abnormal too.

This is the cue file.

[cue.zip](https://github.com/flacon/flacon/files/5179975/cue.zip)

**Comment by SokoloffA** [comment]
While I was silent @HanatoK [added support for code pages for some East Asian languages](https://github.com/flacon/flacon/pull/134).
* Simplified Chinese (GB18030)
* Traditional Chinese (BIG5)
* Japanese (CP932) 

I don't understand anything in Chinese, and I can't check.  But it looks like it's working, do these tags look right?
```
01 - 君色サブリミナル.flac:    comment[0]: artist=幽閉サテライト
01 - 君色サブリミナル.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
01 - 君色サブリミナル.flac:    comment[2]: title=君色サブリミナル
01 - 君色サブリミナル.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

02 - Romantic Children(Club Mix).flac:    comment[0]: artist=Alstroemeria Records
02 - Romantic Children(Club Mix).flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
02 - Romantic Children(Club Mix).flac:    comment[2]: title=Romantic Children(Club Mix)
02 - Romantic Children(Club Mix).flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

03 - Mami Mami Zone.flac:    comment[0]: artist=ALiCE'S EMOTiON
03 - Mami Mami Zone.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
03 - Mami Mami Zone.flac:    comment[2]: title=Mami Mami Zone
03 - Mami Mami Zone.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

04 - 飲酒オンザビール.flac:    comment[0]: artist=IOSYS
04 - 飲酒オンザビール.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
04 - 飲酒オンザビール.flac:    comment[2]: title=飲酒オンザビール
04 - 飲酒オンザビール.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

05 - EastNewSound 幽閉楽祭 2013 スペシャルメドレー（contrivance-有色透明無色透明-Rot in hell !!）.flac:    comment[0]: artist=EastNewSound
05 - EastNewSound 幽閉楽祭 2013 スペシャルメドレー（contrivance-有色透明無色透明-Rot in hell !!）.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
05 - EastNewSound 幽閉楽祭 2013 スペシャルメドレー（contrivance-有色透明無色透明-Rot in hell !!）.flac:    comment[2]: title=EastNewSound 幽閉楽祭 2013 スペシャルメドレー（contrivance/有色透明?無色透明/Rot in hell !!）
05 - EastNewSound 幽閉楽祭 2013 スペシャルメドレー（contrivance-有色透明無色透明-Rot in hell !!）.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

06 - こなぐすり幽閉楽祭 2012　スペシャルメドレー.flac:    comment[0]: artist=こなぐすり
06 - こなぐすり幽閉楽祭 2012　スペシャルメドレー.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
06 - こなぐすり幽閉楽祭 2012　スペシャルメドレー.flac:    comment[2]: title=こなぐすり幽閉楽祭 2012　スペシャルメドレー
06 - こなぐすり幽閉楽祭 2012　スペシャルメドレー.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

07 - ココロノスキマ.flac:    comment[0]: artist=Sound CYCLONE
07 - ココロノスキマ.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
07 - ココロノスキマ.flac:    comment[2]: title=ココロノスキマ
07 - ココロノスキマ.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

08 - florere.flac:    comment[0]: artist=セブンスヘブン　MAXION
08 - florere.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
08 - florere.flac:    comment[2]: title=florere
08 - florere.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

09 - 湖畔夏風邪隊.flac:    comment[0]: artist=東京アクティブNEETs
09 - 湖畔夏風邪隊.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
09 - 湖畔夏風邪隊.flac:    comment[2]: title=湖畔夏風邪隊
09 - 湖畔夏風邪隊.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

10 - 明神変化.flac:    comment[0]: artist=Liz Triangle
10 - 明神変化.flac:    comment[1]: album=幽閉楽祭 ～春ノ宴～
10 - 明神変化.flac:    comment[2]: title=明神変化
10 - 明神変化.flac:    comment[3]: albumartist=幽閉楽祭 ～春ノ宴～

**Comment by Lhatna7N0l** [comment]
Your tags are correct,but my problem still exists.

In the newest version,there is a code which can display normally in flacon itself now,while the message in the output file is still ###.
![1](https://user-images.githubusercontent.com/70121073/92372182-26818200-f12f-11ea-8c12-5050d091e1e3.png)
![2](https://user-images.githubusercontent.com/70121073/92372187-28e3dc00-f12f-11ea-8364-671b82e8da1a.png)
Meanwhile,with cue files automatically recognized as UTF-8 code,the output on the files is messed up too.
![3](https://user-images.githubusercontent.com/70121073/92373589-208ca080-f131-11ea-8d6a-384c193294ec.png)
![4](https://user-images.githubusercontent.com/70121073/92373597-22eefa80-f131-11ea-8c12-ef090bd949af.png)

I don't know whether @HanatoK has the same problem I met. 

In case it matters,my system locale is:
Locale: LANG=zh_CN.UTF-8, LC_CTYPE=zh_CN.UTF-8 (charmap=UTF-8), LANGUAGE=zh_CN:zh (charmap=UTF-8)

The cue+flac files are too big to upload to github(even the smallest CD),if you need them,please leave me an email address.

**Comment by HanatoK** [comment]
@Lhatna7N0l I could not reproduce your issue even without my patch (flacon 6.1.0). Here's my screenshot:
![img](https://i.imgur.com/BiJFZow.png)
so I think this is a different issue with what I have mentioned in PR #134 . It seems the writer does not write those metadata correctly. Could you please try another output format, like OGG?

**Comment by Lhatna7N0l** [comment]
My problem got solved.I had only zh_CN.UTF-8 UTF-8 as my locale before.And it works after I add en_US.UTF-8 UTF-8 to locale.gen and run locale-gen.
It seems the writing part relies on en_US.UTF-8 UTF-8 locale,but it doesn't need english to be the system language.

**Comment by HanatoK** [comment]
@SokoloffA I took a look at `encoder.cpp` and found this line: https://github.com/flacon/flacon/blob/a8c409161699428935bde3896821f34b380f7874/converter/encoder.cpp#L127
Is this related to this issue? What will happen if the users do not have the locale `en_US.UTF-8` installed?

**Comment by SokoloffA** [comment]
@HanatoK 
> Is this related to this issue? What will happen if the users do not have the locale en_US.UTF-8 installed?

Yes is related. Is workaround for MacOS. When you start MacOs application bundle LANG variable don't set. And some codecs (I don't remember which) works incorrectly.

I fixed it, now I set the LANG variable only for MacOS bundle.
