### ISSUE TITLE
Default "compression" parameter in auto-generated config is not used

### ISSUE THREAD

**Issue by AgentMC** [flacon/flacon#137]
Flacon runs on FreeBSD (freenas 11.3 specifically). It couldn't start GUI at all against the vnc, so I had to use commandline. 

I wanted to switch the compression for flac from 5 to 8. However, after I changed the ~/.config/flacon/flacon.config so that the default General section Compression is set to 8, it was not used. I had to dig into your code to understand that it is supposed to take parameter from FLAC/Compression instead. After I added the setting and set it to 8, it worked fine.

Request: the default Compression parameter should either be removed from default config generated or to be used as default in applicable profiles.

**Comment by SokoloffA** [comment]
This was fixed some time ago.
