### ISSUE TITLE
Flatpak version doesn't create output

### ISSUE THREAD

**Issue by Extarys** [flacon/flacon#138]
using iotop I found Flacon was writing to:
```
/run/user/1000/doc$ ls
2c9d28b8  4f442ca8  5f736d97  641432c4  8c928544  922081ea  9da2606f  b8d6ae85  by-app  c26f157f  c6b3820f  ce48fda9  dcedf727
```
This looks like raw cue+flac files.

Output is in /media, standard mounted HDD through fstab. No new files or folder.
Asking flacon to output to where the CUE file is results in "I can't create directory "/run/user/1000/doc/922081ea/Album title. Function not implemented".

Also, drag and dropping a cue file results in File not found error inside Flacon.

The flatpak is pretty much useless and no instruction on the website or the README. I'll reinstall using the repo :)

**Comment by Eonfge** [comment]
Ow, sorry for getting back to you so late. I'm responsible for the Flatpak and by default, Flacon can only access ~/Music and ~/Downloads. To access other locations, you can use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) to assign more directories, or you can do the following

```
flatpak override com.github.Flacon --user --filesystem=/OTHER/LOCATION/WITH/MUSIC
```

**Comment by Extarys** [comment]
Don't worry about it. I couldn't find the right folder and tend to forget about flatpak "security".

Thanks for the command, it will be very useful.

**Comment by Eonfge** [comment]
Security is a double edge blade. The system gets better the whole time, but there are still some hairline fractures. Hope that other applications work better for you next time. For now, no shame in using the repo version
