### ISSUE TITLE
Convert button disabled on Mac

### ISSUE THREAD

**Issue by bdrtsky** [flacon/flacon#139]
I don't see how I can use this app, since Convert button is disabled on my Mac. Is it working on Catalina?

**Comment by SokoloffA** [comment]
Yes the program works on Catalina. 

Click the "Add disk" button. 
![image](https://user-images.githubusercontent.com/854935/98851612-8fef7b00-2467-11eb-8585-4177f1b37269.png)

In the dialog, select an audio file or a CUE file. If everything went well, you will see the name of the CUE file, and below the name of the audio file.
![image](https://user-images.githubusercontent.com/854935/98852273-7ef33980-2468-11eb-9c85-89377b0c439d.png)

If there are problems, you will see an error icon. If there are problems, you will see an error icon. When you hover the mouse, you can read the error in the tooltip.
![image](https://user-images.githubusercontent.com/854935/98853304-fb3a4c80-2469-11eb-92ce-8421dd820ed4.png)

The program tries to automatically find a suitable CUE file for the selected audio file and vice versa. If the names of CUE and audio files are not similar, the program can't match them. In this case, the filename field remains empty (in my example, the program couldn't find the audio). So you will have to select the file manually. Click on the icon next to the corresponding field to select file.
![image](https://user-images.githubusercontent.com/854935/98854635-dc3cba00-246b-11eb-974b-c8f2cb886685.png)


_If problems remain, write an error message here, which is shown in the tooltip._

**Comment by bdrtsky** [comment]
Thank you for this great explanation! Not sure why, but after Big Sur update Flacon started to work, the Convert button is active 😀

**Comment by SokoloffA** [comment]
I'm glad everything works for you. Good luck!
