### ISSUE TITLE
support Qt5

### ISSUE THREAD

**Issue by sl1pkn07** [flacon/flacon#14]
Hi

any future plans to port to Qt5?

greetings

**Comment by SokoloffA** [comment]
You are right, I'll do it.

**Comment by SokoloffA** [comment]
[I ported the program to Qt5](https://github.com/flacon/flacon/commit/afe2338bf8cd6dc41be4c0197f1f0242e4bbb9bd). But this required more changes then I expected. So it requires testing, especially with codepages.

**Comment by danfe** [comment]
Please leave the ability to build against Qt4 if you switch to Qt5 by default one day, thank you.

**Comment by SokoloffA** [comment]
@danfe 
If you have installed only one version of Qt it will be used. In any case, you can specify which version to use:

    cmake -DUSE_QT4=Yes 

or

    cmake -DUSE_QT5=Yes
