### ISSUE TITLE
Add option for ALAC encoding

### ISSUE THREAD

**Issue by appetrosyan** [flacon/flacon#140]
Very much enjoy the spirit of the program, however, for my current workflow, it would be nice to be able to directly convert into ALAC. iTunes doesn't do FLAC, and AAC is included (though lossy, and not always a good choice), so considering that there are multiple good ALAC encoders, I wondered if you would be so kind as to include ALAC encoding?

**Comment by SokoloffA** [comment]
The program uses console programs for encoding. I didn't find an encoder for ALAC, only examples of ffmpeg usage. I don't like ffmpeg, it is good for video, but not for bit-perfect audio. For example:
* https://trac.ffmpeg.org/ticket/2325
* https://trac.ffmpeg.org/ticket/6937

If you know a console encoder for ALAC, tell me.

**Comment by jrregaldie** [comment]
Maybe you can use this:

[https://macosforge.github.io/alac/](https://macosforge.github.io/alac/)

**Comment by SokoloffA** [comment]
@jrregaldie Thanks, I'll try.

**Comment by diogoeichert** [comment]
One more option here:
[https://tmkk.undo.jp/xld/index_e.html](https://tmkk.undo.jp/xld/index_e.html)

**Comment by SokoloffA** [comment]
@diogoeichert 
Thank you, I hope I will find time for improvements.

**Comment by shinra-electric** [comment]
I’d love to see ALAC support too. 

My current workflow is Flacon for splitting, and then XLD for encoding to ALAC. It would be great to just need only one app.

**Comment by diogoeichert** [comment]
Well, you actually can use a single app for that. My current workflow uses XLD only. It can split files and encode them to ALAC in a single step. It also has options to correct file names and folder structures, while getting rid of metadata.

**Comment by SokoloffA** [comment]
OK guys, I will add ALAC support in the next major release.

**Comment by SokoloffA** [comment]
I'm in shock! We have the codec sources, but is there no normal command-line utility for encoding to ALAC+m4a! All I found on the internet is suggestion to use ffmpeg or a  qaac via wine.

The [alacconvert](https://macosforge.github.io/alac/) utility is just an example of calling the library. It has a number of limitations:
1. The output file has the CAF format instead of M4A.
2. It doesn't support saving any tags.

I can write a normal utility for coding ALAC, but this is already a separate and full-fledged project.  I can't believe that no one has done this before me! I don't want to do a monkey job.

**Comment by diogoeichert** [comment]
I'm very surprised about that, too. I'd expect the library call within the app would be the shortest path to add ALAC support or at least that the sample CLI app would be able to do it.

I've opened [a new issue in the ALAC project](https://github.com/macosforge/alac/issues/21).

**Comment by diogoeichert** [comment]
On a side note, [this should be the way XLD handles it](https://sourceforge.net/p/xld/code/HEAD/tree/trunk/XLDAlacOutput/).

**Comment by SokoloffA** [comment]
@diogoeichert 
> On a side note, this should be the way XLD handles it.

I was looking at the XLD code. There are 3 problems here:
1. It is written in Objective-C. I am not a guru in Objective-C, it is  possible to port the code to C/C++, but it will take a lot of work.
2. XLDAlacOutput is not a separate program, but a part of the XLD project. I will have to create a separate utility from it.
3. The situation with the license is unclear. The files contains nonstandard license _"Copyright 2006 tmkk. All rights reserved"_. I.e. it is unclear can I use this code or not.

After some googling, I see several options:
1. To create a new utility using [alacconvert](https://macosforge.github.io/alac/) and [TagLib](https://taglib.org/).
2. To porting [qaac](https://github.com/nu774/qaac) to Linux/MacOs
3. Maybe something else?

**Comment by diogoeichert** [comment]
Objective-C is just vanilla C with messaging capabilities in the preprocessor, so I was hoping the proper call to the ALAC lib would be right there somewhere as a one-liner. Now that I dug deeper in the code I see it does some fairly more complex stuff in [XLDAacOutputTask.m](https://sourceforge.net/p/xld/code/HEAD/tree/trunk/XLDAacOutput/XLDAacOutputTask.m). I'm not so sure it even uses the library from what I've seen so far.

**Comment by SokoloffA** [comment]
**Good news!**

The first version of the [alacenc converter](https://github.com/flacon/alacenc) is working! The program converts files up to 32 bits / 192 kHz.

What else needs to be worked on?
* There is no tag support yet.
* Apple's encoder works in one thread and is not very fast. I plan to use it in multiple threads.

**Comment by SokoloffA** [comment]
Done in 9.0.0
