### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by iavswn** [flacon/flacon#142]
Its not seeing any audio files when I click on "add disk". I got them under /home/iavswn/music/. Contents of folder shows up blank. It not seeing any wav,mp3s, etc.

**Comment by SokoloffA** [comment]
MP3 is not supported as an input format. WAV must be displayed. 
* Which operating system do you use?
* How did you install the program, from packages, from sources or Flatpak?
* Please check the filter in the file selection dialog.
![image](https://user-images.githubusercontent.com/854935/101672660-362ea080-3a67-11eb-90ce-7ecec421cf12.png)

**Comment by cuddawudda** [comment]
Hi, perhaps this error should be made clear to the user!

**Comment by SokoloffA** [comment]
Error handling has been improved in recent versions.
