### ISSUE TITLE
Splitter error: Can't read n bytes

### ISSUE THREAD

**Issue by RealDomar** [flacon/flacon#144]
Flacon isn't able to split the last track of one specific flac file.
Error output in the console is
> Warning: Splitter error for track  15 :  Can't read 15948 bytes
> Error: "Can't read 15948 bytes"

All other tracks worked fine.

I'm using version 6.1.0 from ppa.launchpad.net/flacon/ppa/ubuntu

Is there any detailed log?

**Comment by SokoloffA** [comment]
Sorry for long answer. The program has been seriously improved in version 7.0, try with the new version of the program.

**Comment by SokoloffA** [comment]
I hope the problem has been fixed in new releases. 
Please test the last version of the program, if the error remains,  feel free to open the issue again.
