### ISSUE TITLE
Feature: Support to convert split albuns

### ISSUE THREAD

**Issue by fidalgo** [flacon/flacon#145]
After splitting an album, and get a file per track, I would like to transcode from FLAC to another format (have a separate collection for car use). 
If I try to add a directory with the single files I have an error except I have a CUE file.

So my request is to allow the conversion, even if the CUE file is not present.

**Comment by SokoloffA** [comment]
This functionality was added in version 7.0.0. So now you can work with already split albums. At the same time, Flacon is not just an audio converter, but a splitter, and you still need a CUE file. But if you used the "Create per track CUE sheet" option, then working with a splitted album is no different from the first one.

**Comment by SokoloffA** [comment]
Flacon is not just an audio converter, but a splitter, and you need a CUE file. If you need to change the audio format or meta-information of an individual audio file and you do not have a CUE-file, then you should use another audio converter program.

I am sometimes asked to add audio converter functionality to the program. I don't like the idea of universal programs. Universal programs make all their functions less convenient than specialized programs. But I am ready to think about creating a separate program for it.

But I don't want to write yet another converter, the new program must have a killer feature. Tell me what you are not satisfied with the existing converters, what features you lack, and this may will be the reason for writing a new program.
