### ISSUE TITLE
Flacon refuses to compute replaygain for no good reason

### ISSUE THREAD

**Issue by nbozhenov** [flacon/flacon#146]
When converting a 24/192 flac to 24/48 (using resampling settings), I'm getting this (erroneous) error:
`Conversion is not possible: you can't use 'ReplayGain' for files with sample rates above 48kHz. Metaflac doesn't support such files`

I believe that flacon should check the output sample rate instead of the input one before reporting this error.

Moreover, not all metaflac versions have the same limitations. My metaflac (1.3.3, ubuntu-20.04) says:
`The sample rate must be one of 8, 11.025, 12, 16, 18.9, 22.05, 24,  28,
                 32, 37.8, 44.1, 48, 56, 64, 88.2, 96, 112, 128, 144, 176.4, or 192kHz.`

**Comment by SokoloffA** [comment]
I will do it. It makes sense.

**Comment by SokoloffA** [comment]
Done

**Comment by SokoloffA** [comment]
This is included in release 7.0.0
