### ISSUE TITLE
FILE directive in cue files seems to be ignored

### ISSUE THREAD

**Issue by nbozhenov** [flacon/flacon#147]
It seems that flacon determines the name of an input audio file based on the name of the cue file only, ignoring any FILE directive inside the cue file. It is especially problematic when there are multiple FILE directives. For example, typical vinyl rip would look like this:

```
REM DATE 1996
PERFORMER "ArtistName"
TITLE "AlbumName"

FILE "Side_A.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Track #1"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Track #2"
    INDEX 01 05:04:00

FILE "Side_B.flac" WAVE
  TRACK 03 AUDIO
    TITLE "Track #3"
    INDEX 01 00:00:00
  TRACK 04 AUDIO
    TITLE "Track #4"
    INDEX 01 04:54:15
```

In such a case, the issue cannot be worked around by a simple renaming of the cue file.

**Comment by SokoloffA** [comment]
I apologize for the long silence. I didn't see a notification about your issue maybe Google marked the email as spam.

First of all, in version 7.0.0, the algorithm for disks containing multiple FILE tags was dramatically changed. Please try the new version.

> It seems that flacon determines the name of an input audio file based on the name of the cue file only, ignoring any FILE directive inside the cue file. 

No, it's not. The program uses the following algorithm:

1. If the CUE file contains only one FILE tag, and the directory contains only one audio file, this audio is used.

2. If the number of audio files is equal to the number of FILE tags, then an audio file is searched for each tag based on the content of the tag and, in case of failure, based on the track name.

3. If the CUE file contains only one FILE tag, then we search by the tag, and in case of failure, by the name of the CUE file.

4. Search by tag, and in case of failure, by the CUE file name, adding the suffixes like disk01, side01, etc.

I would really like to know if there are still problems in the new version of the program. If so, send me a CUE and a directory listing with it.

**Comment by SokoloffA** [comment]
It looks like I made a bug, maybe this is your case. 
https://github.com/flacon/flacon/commit/59ae20b2021804fe835f15815a55c362218e6300
