### ISSUE TITLE
Error message "Conversion is not possible. Audio file not set" is not very helpful

### ISSUE THREAD

**Issue by nbozhenov** [flacon/flacon#148]
When I first saw such an error, my first guess was that the audio file is missing or something is wrong with its filename. I had to debug flacon code only to find out that the audio format is not supported (it was f32 wavpack file). It would be helpful to report `InputAudioFile::mErrorString` instead of the generic (and useless) "Audio file not set" message.

**Comment by SokoloffA** [comment]
I'll add a smarter handling of this situation.

**Comment by SokoloffA** [comment]
Done

**Comment by SokoloffA** [comment]
This is included in release 7.0.0
