### ISSUE TITLE
Flacon was added to FreeBSD ports: installation information on download page should be updated

### ISSUE THREAD

**Issue by danfe** [flacon/flacon#15]
Today I've added FreeBSD port: [audio/flacon](http://www.freshports.org/audio/flacon/).  It would be nice if you could add installation information on the downloads page; it should be similar to Rosa (users can install it from the official repositories), only the command is different:

    pkg install flacon

Alternatively, users can install if from ports (build from source):

    cd /usr/ports/audio/flacon && make install clean

**Comment by SokoloffA** [comment]
Done https://github.com/flacon/flacon.github.io/commit/d936486a74c57476061e5d160dbb7f2a7eebe3b0

**Comment by danfe** [comment]
Thanks, much appreciated!

**Comment by SokoloffA** [comment]
Done.
P.S. conntact with me at email sokoloff.a at gmail.com
