### ISSUE TITLE
OpenSuse repo Debian 10 Release.key not found and 9.0 expired?

### ISSUE THREAD

**Issue by RattusSolarus** [flacon/flacon#150]
I've been using the Debian 9.0 repo for a long time and today during update I got:
```
Err:3 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ InRelease        
  The following signatures were invalid: EXPKEYSIG B3E6A0ECC93E441A home:Sokoloff OBS Project <home:Sokoloff@build.opensuse.org>
```
Tried the Debian 10 repo and:
```
# wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10.0/Release.key -O- | apt-key add -
--2021-02-28 19:18:10--  http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10.0/Release.key
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:80... Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-28 19:18:10 ERROR 404: Not Found.
```
apt-key is deprecated but not retired until after Debian 11. I set up a couple of repos using apt-key on Bullseye (11) last week with no problem.

So it seems 9.0 key is expired, and 10.0, when set up exactly as explained on the Downloads page is not found.
I then downloaded Release.key manually and it imported OK but on subsequent apt update got this error:
```
E: The repository 'http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10.0 ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
I can see a "Release" file browsing the repo though. Weird stuff happening.

Thanks for Flacon BTW, I've found it quite useful a number of times.

**Comment by yitahutu** [comment]
the path on download page is wrong, it should be "Debian_10", not "Debian_10.0".
but the downloaded Release.key is still expired...

**Comment by RattusSolarus** [comment]
> the path on download page is wrong, it should be "Debian_10", not "Debian_10.0".
> but the downloaded Release.key is still expired...

100% correct. I updated the path in sources file but key is still expired so not possible to install from repo using apt.
`W: GPG error: http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10 ./ InRelease: The following signatures were invalid: EXPKEYSIG B3E6A0ECC93E441A home:Sokoloff OBS Project <home:Sokoloff@build.opensuse.org>`

**Comment by Thyr-Rex** [comment]
I have the same problem. The keys in "Debian_9.0" and "Debian_10" are still expired.

**Comment by bxrxs** [comment]
I have the same problem...

**Comment by SokoloffA** [comment]
I rebuilt the packages on OBS, please check. Parhaps you need to run 
```
wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0/Release.key -O- | apt-key add -
or
wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10/Release.key -O- | apt-key add -
```

**Comment by RattusSolarus** [comment]
Thank you. Debian 10 repo is now working and packages are updated to the latest versions.
This Flacon version works perfectly in current Debian Sid also.

**Comment by SokoloffA** [comment]
I'm glad. Sorry for long fix.
