### ISSUE TITLE
Ubuntu repo giving error on Hirsute Hippo

### ISSUE THREAD

**Issue by Manichaean** [flacon/flacon#152]
Hi, thank you for the great program. I tried installing it by the Ubuntu repo but it gave some sort of error, maybe related to Hirsute Hippo? It worked when I installed Groovy Gorilla before. Please can you see if you can fix this? Thank you again.

**Comment by SokoloffA** [comment]
Today I plan to release a new version of the program.

**Comment by Manichaean** [comment]
Thank you so much!

**Comment by SokoloffA** [comment]
Have you successfully installed the program? If so, I'll close the issue.

**Comment by Manichaean** [comment]
Yes, thank you. And thank you for an awesome program.

**Comment by SokoloffA** [comment]
I'm glad
