### ISSUE TITLE
[Linux] The Flatpak from flathub does not launch

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [flacon/flacon#153]
### Error Description

When I try to launch the flatpak, I get the following error:

![Bildschirmfoto von 2021-04-25 21-33-31](https://user-images.githubusercontent.com/41188546/116007010-021add00-a60e-11eb-851f-85d9092602ce.png)

Other Qt-based Flatpaks like Audacious or RazerGenie work correctly. All of the mentioned apps where installed from flathub.

### How to reproduce

Click the Icon in the app launcher or start it from the terminal with flatpak run com.github.Flacon.

### Expected Result

The app should open when started with a terminal or with an app launcher.

### System Information

OS: Fedora 34 64bit
Install Method: Flatpak
Desktop: Gnome 40
Session: Wayland

**Comment by SokoloffA** [comment]
This problem is [discussed here](X11 access not being granted flathub/com.github.Flacon#13).
