### ISSUE TITLE
Image copy

### ISSUE THREAD

**Issue by ogardella** [flacon/flacon#155]
I am using Debian Testing and Flacon 7.0.1 installed with Flatpak. When converting audio, the image is not copied to the destination folder.

**Comment by SokoloffA** [comment]
Please send me the Flacon config file  ~/.config/flacon/flacon.conf 
It does not contain any private data

**Comment by ogardella** [comment]
[flacon.zip](https://github.com/flacon/flacon/files/6488204/flacon.zip)

~xxxxxx/.var/app/com.github.Flacon/config/flacon/flacon.conf

**Comment by SokoloffA** [comment]
Sorry, this is my stupid bug. I missed the exclamation mark character.

I will release a new version very soon

**Comment by Linnes16** [comment]
> Sorry, this is my stupid bug. I missed the exclamation mark character.
> 
> I will release a new version very soon

Any idea when this might get patched? This issue is still present, I'm using the 7.0.1 Flatpak version on Pop OS. Otherwise it works great. It just won't write the cover art to the music files.
[flacon.zip](https://github.com/flacon/flacon/files/7070052/flacon.zip)

**Comment by ogardella** [comment]
I downgraded to a version from last year, with which I got the penultimate version that works well with image copying (6.1.0):

flatpak remote-info --log flathub com.github.Flacon

      Commit: 37d517a448d7dea79d1c8adf613f7e69bd11e8166e2c0dad3620cf20b2f8566a
      Asunto: Add category info to the metadata.xml (aa0d23fb)
       Fecha: 2020-12-16 21:29:49 +0000

sudo flatpak update --commit=37d517a448d7dea79d1c8adf613f7e69bd11e8166e2c0dad3620cf20b2f8566a com.github.Flacon

I will temporarily mask it from updating to the latest version until it is fixed:

sudo flatpak mask com.github.Flacon

**Comment by IamDankaO** [comment]
Hello, I'm using Flacon 7.0.1 and Cover is not saved into Files when converting .cue to individual flac files.
I'm enjoying your app, hope to see and update soon.
Good work ant thanks.

**Comment by SokoloffA** [comment]
I was busy and forgot to update the app. I will be good boys and will release a release one of these days.
