### ISSUE TITLE
Add option to delete source file on successful split into separate audio tracks

### ISSUE THREAD

**Issue by audiomuze** [flacon/flacon#157]
I normally unpack files to the folder by specifying "." as the destination.  This keeps trracks, cuesheet, images etc. together in a single folder tree.

After processing a directory tree using flacon users have to go manually delete the source files, one at a time.  It'd be really useful to have the option to have flacon delete the source audio file once a split has been successfully completed.

**Comment by SokoloffA** [comment]
I'm sorry I didn't respond to your previous request. 

I will add such an option. 

But the program can copy the cover (in the original size or with a resize). The program also can create a per track CUE. It may be more convenient for you to set a directory other than "." and store the output files separately from the source files.

**Comment by audiomuze** [comment]
> It may be more convenient for you to set a directory other than "." and store the output files separately from the source files.

Not really, after splitting there's tagging etc. before copying to audio server.

**Comment by ChaosBlades** [comment]
My music management software can't process single file albums so I have to use Flacon. It is already looking in the source folder for the files so I add all the .cue and convert. The problem is the source file is still present and if the source file is the same name as the album and the album has a track with the same name then it can get confused and think the album source file is that track then I have a track that should be 1 track but it is the whole album. So currently I have to go back through and delete all the source files manually. So this feature would be really nice.

**Comment by jej** [comment]
After some hours of flacon usage to split, split, split, I have the same need...

Sometime it's easy to find a common pattern for the cue and flac source files, and search and mass delete them in a filemanager. But sometime the cue/source file names are different in each subfolder. In this case, I have to find all *.cue files and script something that rm these files + the flac source files...

I would except something like this:
- adding the folder(s) to split
- run the splits
- after the batch is finished, a button (in top bar or as a right click action) allows to remove the cue+source files for all directories that are successfully completed. A popup windows list these files (possible to copy/paste these paths) and ask for confirmation before proceeding...

**Comment by audiomuze** [comment]
ya, just processed 40 flac/cue files in a directory tree and now face the task of manually changing directories 40 times, navigating 40x to the flac file that should be deleted and initiating a delete 40x.  Making automating of this a configurable option would greatly reduce effort and risk of deleting the wrong file.

**Comment by audiomuze** [comment]
@SokoloffA is this a planned feature or not going to happen?

**Comment by SokoloffA** [comment]
I promised this, but then I wondered how to make sure that no one would accidentally lose their files.  If I keep the "delete sources after successful compilation" option, someone might forget to uncheck it and lose their files. 

Maybe it would be better to make an item in the main menu "delete source files"?

**Comment by ChaosBlades** [comment]
I think a simple yes/no dialog at the end of conversion asking the user if they are sure they want files to be permanently deleted would be sufficient if moving files to the recycling bin/ trash is not possible.

**Comment by SokoloffA** [comment]
What's wrong with a special menu item?

For example, I often forget to change the tags, as a result I have to recode several times. After user like the result, he can click "Trash Sources for successfully converted disks and Remove from list..." menu item.

**Comment by SokoloffA** [comment]
Those who do not need this feature will not experience any inconvenience

**Comment by SokoloffA** [comment]
Let's start with this option

**Comment by SokoloffA** [comment]
Included in release 11.0.0

**Comment by audiomuze** [comment]
Just upgraded and tried it and wanted to provide the following feedback:

- it's set to remove .cue files also, which is not ideal as I imagine some users would prefer to retain them whilst dumping the source audio file. 
- the popup list that's presented is bulleted but the listed contents isn't sub-bulleted making it hard to read.
- if there's a long list of files that have been split then the popup list is going to run out of screen real estate

There's a lot of real unused estate on the bottom left side of the screen:
![image](https://github.com/flacon/flacon/assets/6852511/c6bb726f-e63a-4ff1-b7f1-50ccf64776cf)

- Rather than hide the option to delete in the File menu, why not include the listing of source files and the option to delete them in the available real estate at bottom left.  If the list is too long add a vertical scrollbar to enable users to browse it. 
- Configure the delete option to require a manual confirmation of the delete  action (but please don't prompt again after making the choice to delete).
- In configuration settings it  might be useful to add a config option as to whether or not to include .cue files when deleting the source audio file
