### ISSUE TITLE
Cannot convert

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [flacon/flacon#158]
Exactly what should I do to convert a .cue file to .flac? The Convert button is grayed out and I cannot figure out what I do wrong. Maybe add a FAQ entry.

**Comment by SokoloffA** [comment]
I updated the FAQ https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions

**Comment by SokoloffA** [comment]
What version of the program are you using? In 7.0, I improved the error messages.
If you still have problems, run the program from the console there you will see additional messages.

**Comment by IHateTheProgrammingClass** [comment]
@SokoloffA I have 7.0.1. I don't know if it's a bug or I just simply don't know how to use the program.

**Comment by SokoloffA** [comment]
Maybe this is a bug, I don't think that you are doing something wrong. I tried to make the use of the program as simple as possible.

You need to have 2 source files, a CUE and an audio file. Just run the program, click "Add disk" and select one of these files in the dialog. If something went wrong, the program will show an error message and mark the disk with a red icon. If you hover your mouse over this icon, you will see a list of problems.

What do you see on the screen? Send me a screenshot of the program.
What operating system do you use?

**Comment by IHateTheProgrammingClass** [comment]
@SokoloffA The audio seems to be the problem I forgot. But I don't know how to add the audio itself? I have an .mka file. It does not seem to be supported, and does not show up in the "Add disc" selection.

**Comment by SokoloffA** [comment]
Unfortunately, MKA is not supported by the program. I tried to find the console decoder program (Flacon use console programs for decoding/encoding) and found nothing but ffmpeg.
