### ISSUE TITLE
Option to Do Custom Encoding

### ISSUE THREAD

**Issue by maya923** [flacon/flacon#160]
Hello!

I just discovered this app on macOS and I do love it! However, would it be possible to have the ability to create custom profiles with custom switches for the codecs? For example, I encode MP3 with LAME in a specific way, and would love to use those switches with this.

Thank you so much!

**Comment by SokoloffA** [comment]
What do you mean by "with a LIMP in a certain way"? 
1. You can select the LAME profile, bitrate and quality on the preferences dialog. 
2. You can [create two or more MP3 presets](https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions#in-some-cases-users-have-multiple-targets-for-example-laptop-phone-and-so-on-and-need-to-use-different-options-for-each-case-especially-with-respect-to-encoding-type-and-rate), after which you can quickly switch between them. 
3. If you are using some settings that the program does not allow to set, write me which ones. If they are useful to other users, I will add them to the preferences dialog. Also I plan to add a custom encoder in which you can use any program with any options.

**Comment by maya923** [comment]
> Also I plan to add a custom encoder in which you can use any program with any options.

This is exactly what I was wondering. Happy to see this will be added, thank you!

**Comment by SokoloffA** [comment]
And yet, what LAME options do you use? Maybe someone is suffering like you.
