### ISSUE TITLE
Support for removing pre-emphasis

### ISSUE THREAD

**Issue by mueslimak3r** [flacon/flacon#161]
https://wiki.hydrogenaud.io/index.php?title=Pre-emphasis

"FLAGS PRE" identified pre-emphasis in a .cue file

**Comment by SokoloffA** [comment]
Thank you, I read the article. How I see the modifications:
If the CUE contains "FLAGS PRE", then pass the sound through "sox deemph" filter. 
Will this option suit you?

**Comment by mueslimak3r** [comment]
Yes, that looks good!

**Comment by SokoloffA** [comment]
Done in https://github.com/flacon/flacon/commit/7c3e1d468d3afeb2f1fae1ebe2de86e33e85c6c1
