### ISSUE TITLE
[macOS] Build instructions for Mac 

### ISSUE THREAD

**Issue by shinra-electric** [flacon/flacon#162]
I'm following the build instructions for Ubuntu and Fedora, assuming that they are similar to Mac, but I'm getting a build error regarding Qt5. 

If the build instructions are different to Linux, can the Wiki be updated? 

I'm using an M1 Mac on Monterey 12.0.1. 

If anyone is interested, the error I'm getting is below. 

>CMake Error at CMakeLists.txt:175 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:
    Qt5Config.cmake
    qt5-config.cmake
  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

Note that I already have qt5 version 5.15.2_1 already installed.

**Comment by shinra-electric** [comment]
For anyone interested in this error, I got past it by getting info on the Qt5 install. It says: 

>This version of Qt on Apple Silicon does not include QtWebEngine
qt@5 is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.
If you need to have qt@5 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc
For compilers to find qt@5 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"
For pkg-config to find qt@5 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"

I ran the export commands above (I'm not sure if they are required) and then ran with the command: 
>cmake .. -DCMAKE_PREFIX_PATH=/opt/homebrew/Cellar/qt@5/5.15.2_1/

The build succeeded with this..

**Comment by SokoloffA** [comment]
You can also use the [makebundle.py](https://github.com/flacon/mac_bundle/blob/master/makebundle.py) script to build an Apple bundle. I didn't have time to polish it, you'll have to change a few variables in lines 262-271.
