### ISSUE TITLE
[macOS] Native Apple Silicon M1 Universal build

### ISSUE THREAD

**Issue by shinra-electric** [flacon/flacon#163]
I've been having trouble trying to build Flacon myself (see #162), so I though I'd ask if there are plans to release a universal  binary for macOS.

**Comment by SokoloffA** [comment]
Yes, I plan to release sources and Linux version today. It took some delay for the translators to have time to do work. 

I wrote a script to build a universal binary for Mac OS. So next version of the program will be universal binary. 
If there are no problems, I will make a release for Mac today or tomorrow.

**Comment by shinra-electric** [comment]
I just tried the new v.8.0 Universal Binary. Unfortunately it just quits straight away. 

![Screenshot 2021-11-14 at 22 35 35](https://user-images.githubusercontent.com/50119606/141701341-af9a2613-5904-4831-b2b0-d947d63f453c.png)

I'm using an M1 Pro with Monterey 12.0.1

**Comment by SokoloffA** [comment]
@shinra-electric I rewrote the build script. I'd be happy if you'd check out the new [dmg image](https://github.com/flacon/flacon_beta/releases/tag/v8.0.0).

**Comment by shinra-electric** [comment]
That link seems to be dead, I get a 404....

**Comment by SokoloffA** [comment]
Sorry, I configured access incorrectly

**Comment by shinra-electric** [comment]
It opens fine, and I used a cue to split a large FLAC file into separate tracks successfully. 

I think you can close this issue 😀
