### ISSUE TITLE
8.1.0 ignores result files directory when splitting, files instead to ../embedded:/mnt/...

### ISSUE THREAD

**Issue by audiomuze** [flacon/flacon#167]
Just updated to 8.1.0 and unpacked a FLAC album with the following settings:
![image](https://user-images.githubusercontent.com/6852511/145706793-0e8b32bf-26a1-4106-9e76-d255ca306090.png)

Instead of unpacking to `/mnt/sdb/flacon/testalb`, flacon unpacked to:
`/mnt/sdb/flacon/embedded:/mnt/sdb/flacon/testalb`

**Comment by SokoloffA** [comment]
I fixed it. I plan to release a new version one of these days.

**Comment by SokoloffA** [comment]
Closed in release 8.2.0
