### ISSUE TITLE
"FLAGS PRE": encoding stalled at 0% if sox is not installed

### ISSUE THREAD

**Issue by jej** [flacon/flacon#168]
Hi,
I have some cue files with "FLAGS PRE". Without sox installed, the extraction is ok but encoding just waits for ever at 0%.
If I remove the FLAGS PRE it works. With FLAGS PRE and sox installed it works too.
I guess this issue is related to issue #161.
Hope it helps.

**Comment by SokoloffA** [comment]
This is my mistake when creating DEB packages. 
The sox is used when changing the sampling rate and/or bit depth. So sox must be present and must be a hard dependency.

1. The MacOS bundle contains sox.
2. The flatpack package contains sox.  @Eonfge is smarter than me.
3. I will fix the DEB package on my PPA.
4. If you use other packages, please kick the maintainers for your distribution.

**Comment by jej** [comment]
I compiled from the git under linux. I did'nt know it was a dependency, until this flag in a cue...
Thanks.

**Comment by SokoloffA** [comment]
Fixed in the flacon_8.2.0-2 on the [PPA](https://launchpad.net/~flacon/+archive/ubuntu/ppa/+packages)

**Comment by Eonfge** [comment]
@SokoloffA Thanks for the honour. Not sure when I configured the sox libs though, so it might have been somebody else's work. Over at Flathub, we share a lot of resources.
