### ISSUE TITLE
repository for ubuntu 15.04 coming soon?

### ISSUE THREAD

**Issue by gchokyong** [flacon/flacon#17]
or should i try to install it from a tar file? If the update to 15.04 hadn't solved so many bugs for me I'd revert back to 14.04 just to use this program. It's indispensable.

**Comment by rompolompo** [comment]
You can safely install the deb file from 14.10

**Comment by gchokyong** [comment]
That's awesome, been googling a few minutes looking for it, I'll keep looking, but so far all i've found is that ppa that doesn't work on 15.04, nothing to directly download the program.

**Comment by gchokyong** [comment]
unless it's that zip file right there...

**Comment by rompolompo** [comment]
https://launchpad.net/~flacon/+archive/ubuntu/ppa/+files/flacon_1.0.1-1utopic_amd64.deb

https://launchpad.net/~flacon/+archive/ubuntu/ppa/+files/flacon_1.0.1-1utopic_i386.deb

Taken from here:

https://launchpad.net/~flacon/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=utopic

**Comment by gchokyong** [comment]
lol thanks for hooking a noob up :)

**Comment by Singtoh** [comment]
Thanks for this as well. I have been looking for this to.

Cheers,

Singtoh

**Comment by gchokyong** [comment]
Oh wait... this:
![screenshot from 2015-05-13 21 50 19](https://cloud.githubusercontent.com/assets/12438199/7625829/26c66b8a-f9ba-11e4-90b9-65ea86a16c16.png)

**Comment by gchokyong** [comment]
It's strange... I think i saw a post somewhere about this issue though, googling now

**Comment by rompolompo** [comment]
The MAC package is available from the same link I posted....

**Comment by gchokyong** [comment]
Thank you sir! Now I can drown myself in lossless audio ecstasy again! 
![screenshot from 2015-05-13 22 01 33](https://cloud.githubusercontent.com/assets/12438199/7625927/f82b13a0-f9bb-11e4-99f6-e6ba852a5f9a.png)

**Comment by gchokyong** [comment]
Also thank you for inadvertently teaching me how to find and install things this way. Cheers!

**Comment by SokoloffA** [comment]
Sorry that you had to wait. Now packages for 15.04 was ready (mac, ttaenc and flacon).

**Comment by gchokyong** [comment]
Wow, that was fast though, now I kinda feel like I was being impatient lol! SokoloffA, I thank you for this great program and your diligence in maintaining it. I use it A LOT. Take care, guys :)

**Comment by SokoloffA** [comment]
You aren't impatient, it's I slowpoke. Ubuntu was released on 23 April, and now 15 May.

**Comment by gchokyong** [comment]
There's just so many of us counting on you ;) your still faster than the
other guys though, i ran an apt upgrade today and their ppa still wasn't
updated after after yours was. i haven't even used that other flac splitter
program, just tried adding the ppa when your wasn't updated... to no avail
