### ISSUE TITLE
Add musicbrainz & discoggs as tag sources.

### ISSUE THREAD

**Issue by alanalvarado** [flacon/flacon#171]
FLACON is great, but I need to use multiple tools for my workflow, would it be possible to get tags from MusicBrainz & Discogs?

**Comment by SokoloffA** [comment]
That sounds reasonable. I think I'll do it.

**Comment by SokoloffA** [comment]
https://github.com/flacon/flacon/commit/56256ea4249b84423ff5725f02724a7eb58d2eb1
