### ISSUE TITLE
Feature Request: Batch Transcode Audio

### ISSUE THREAD

**Issue by alanalvarado** [flacon/flacon#175]
For example I have my library in flac, Then I need some files in Mp3 for my mp3player

It would be nice to be able to batch transcode files.

**Comment by SokoloffA** [comment]
Sorry for long silence.

I answered a similar question in the FAQ. I don't mind writing a new converter program, but there are already such programs for Linux and MacOS. If they don't suit you, describe what you don't like in its. Maybe it will be a killer feature for the new program.

**Comment by SokoloffA** [comment]
I didn't get any feedback, so I'm closing the issue.
