### ISSUE TITLE
Japanese characters turned into ####

### ISSUE THREAD

**Issue by vymague** [flacon/flacon#176]
Version: flacon 8.2.0 from AUR

Same issue with https://github.com/flacon/flacon/issues/133. For what it's worth, I tried to open the attached .cue file in that issue 133 and it says it's not UTF-8 valid.  
I also had the same issue using `cuetag.sh`. https://github.com/svend/cuetools/issues/38 

Title, artist, album name, etc. of my files are in Japanese. They show up fine in flacon. But when I split the .wav or .flac file with the .cue file, the output metadata only has #### (number sign, hash, pound sign).  

I haven't tried reproducing the problem with other Asian languages like Chinese or Korean. 

My default locale is `en_US.UTF-8`. 

List of enabled locale (`locale -a`):

```
C
en_US.utf8
ja_JP.utf8
POSIX
zh_CN.utf8
zh_TW.utf8
```

The problematic .cue file:
[problematic.cue.zip](https://github.com/flacon/flacon/files/8233482/problematic.cue.zip)

Any idea?  

edit: In the case of cuetools, someone figured out why it happens on Arch. https://github.com/svend/cuetools/issues/38#issuecomment-1083559011
Should also be the cause for the problem with flacon on Arch.

**Comment by frantic1048** [comment]
I did a git bisect from 6.1.0-1 to the latest 8.3.0-1 with https://aur.archlinux.org/packages/flacon on the latest Arch Linux(2022-03-25), and every version has the same issue.

- [Update to 8.3.0-1](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=flacon&id=3ade55b76e4516b6270472cca4dd2d92fdec0e26) <- 2022-03-20
- [Update to 6.1.0-1](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=flacon&id=7fe5861387edde18396f78b843acb3ec44cebef4) <- 2020-06-27

According to my memory, I didn't meet this issue 2 months ago(I do not split tracks/upgrade my system very often, this is a rough estimate.).

We may have to check the versions of libs used by flacon during recent months to locate the culprit.

**Comment by frantic1048** [comment]
I noticed flacon's debug log shows CLI usage like `/usr/bin/flac ...... --tag 'album=some album title' ...... -o encoded.flac`.So I tried to use flac individually to encode metadata and found some interesting results.

Assume we want to write `album` metadata field with content `Tokimeki Poporon♪ ときめきポポロン♪` (intentionally mixing Japanese, English and symbols for demonstration) into a FLAC file.

# Create a sample file

> Using any existing FLAC file is also ok, this section is for convenient testing.

Create a FLAC sample with 10 seconds(the `-t 10` option) of silence:

```sh
❯ ffmpeg -f lavfi -i anullsrc=r=48000:cl=2 -t 10 test.flac
```

# Encoding with flac (issue happens)

```elvish
❯ flac -f --tag='album=Tokimeki Poporon♪ ときめきポポロン♪' -o encoded.flac sample.flac

flac 1.3.4
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

sample.flac: WARNING, replacing tags from input FLAC file with those given on the command-line
sample.flac: wrote 7871334 bytes, ratio=1.000
```

```elvish
❯ ffprobe -i encoded.flac
ffprobe version n5.0 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, flac, from 'encoded.flac':
  Metadata:
    album           : Tokimeki Poporon### ###########################
  Duration: 00:01:32.85, start: 0.000000, bitrate: 678 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```

# Encoding with flac --no-utf8-convert (no issue)

```elvsh
❯ flac -f --no-utf8-convert --tag='album=Tokimeki Poporon♪ ときめきポポロン♪' -o encoded.flac sample.flac

flac 1.3.4
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

sample.flac: WARNING, replacing tags from input FLAC file with those given on the command-line
sample.flac: wrote 7871334 bytes, ratio=1.000
```

```elvish
❯ ffprobe -i encoded.flac
ffprobe version n5.0 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, flac, from 'encoded.flac':
  Metadata:
    album           : Tokimeki Poporon♪ ときめきポポロン♪
  Duration: 00:01:32.85, start: 0.000000, bitrate: 678 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```

# Info

_Platform_: Arch Linux x86_64 (2022-03-25)

_flac_: 1.3.4-2

_Locale_(I'm not sure if this issue is related to locale environment variables):

```
❯ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by vymague** [comment]
Thanks a lot for the sleuthing.

**Comment by frantic1048** [comment]
following https://github.com/flacon/flacon/issues/176#issuecomment-1078955451

# Encode with flac and CHARSET=UTF-8 (no issue)

```elvish
❯ env CHARSET=UTF-8 flac -f --tag='album=Tokimeki Poporon♪ ときめきポポロン♪' -o encoded.flac sample.flac

flac 1.3.4
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

sample.flac: WARNING, replacing tags from input FLAC file with those given on the command-line
sample.flac: wrote 7871334 bytes, ratio=1.000
```

```elvish
❯ ffprobe -i encoded.flac
ffprobe version n5.0 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, flac, from 'encoded.flac':
  Metadata:
    album           : Tokimeki Poporon♪ ときめきポポロン♪
  Duration: 00:01:32.85, start: 0.000000, bitrate: 678 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```

I *guess* the `#` marks is coming from https://github.com/xiph/flac/blob/1.3.4/src/share/utf8/utf8.c#L192-L195 . Have to leave now. I may attach more finding later.

**Comment by frantic1048** [comment]
We may use `--no-utf8-convert` option in `flacencoder` as long as we can ensure what we passed to `flac` is always utf-8 stuff. After some search I did not found direct way to ensure this. :cry:

**Comment by vymague** [comment]
Thanks a lot, @frantic1048. I honestly didn't even expect an explanation why this happens. Or even a fix. Just wanted to write the issue somewhere.

**Comment by frantic1048** [comment]
I found flac has a `--tag-from-file` option which allows us to specify tag value from a file, it is relatively easier to write tag content with utf-8 in a text file and use `--tag-from-file` to pass it to flac. This method introduces more temporal files, but allows us to safely use `--no-utf8-convert` option to workaround this issue.

Otherwise, we may find ways to directly use libflac(instead of calling CLI version of flac with QProcess), to have confidential control over the text encoding we communicate with flac. It would likely involve significant work around encoder https://github.com/flacon/flacon/blob/v8.3.0/converter/encoder.cpp

`--tag-from-file` man page:  https://man.archlinux.org/man/extra/flac/flac.1.en#tag_from_file=

@vymague You're welcome, I'm also a user of flacon and love it, and try as I can to help this issue be resolved.

**Comment by vymague** [comment]
Thanks a lot. I'll give it a try this weekend.

**Comment by Nouside** [comment]
There was the same problem with Cyrillic. There were # instead of text. The patch installed and now writes normally. Thanks!

**Comment by vymague** [comment]
Just tried it. Seems to work as expected. Thanks a lot.

**Comment by vymague** [comment]
Someone on the cuetools thread figured out why the issue is observed on Arch. https://github.com/svend/cuetools/issues/38#issuecomment-1083559011

He has reported the issue on xiph's github. https://github.com/xiph/flac/issues/308

**Comment by SokoloffA** [comment]
Guys, the solution with temporary files is not very elegant. I found another approach, use TagLib for tagging.

Could you test the new version of the program from the ["issue-176" branch](https://github.com/flacon/flacon/tree/issue-176).
