### ISSUE TITLE
Disable. warn about, or replace gnudb.org

### ISSUE THREAD

**Issue by Eonfge** [flacon/flacon#179]
Due to some geopolitical kerfuffle,.. the people behind GnuDB has decided to damage the music collections of users who's IP address happens to flag as Russian. The damage is, as far as I have understood, just limited to metadata but restoring it could be really time consuming.

![l3d1ehjkx9191](https://user-images.githubusercontent.com/33983090/169957072-09e3fe78-448f-4c36-b63a-59105c2fdaea.jpg)

### The problem

The technical problem is of course, that [IP Geolocations are very unreliable outside of the US](https://www.arin.net/blog/2018/06/11/ip-geolocation-the-good-the-bad-the-frustrating/). People from neighbouring countries like Georgia and Kazakhstan could easily show up as Russian. 

It would therefore be good to deploy counter-measures, and to warn users that gundb.org might (accurate or not) target your music meta-data.

### People to warn
- Those in one of the many Russian time zones
- Those who have their display language on Russian
  - Optional, you might want to warn everybody using cyrillic

### Mitigations
On Flathub, I could temporarily block network access to Flacon: This would stop Flacon connecting to the mischievous database. I can't make it geolocation sensitive though... so blocking the network access of Flacon will impact all users.

### Other projects
Other projects are also affected, like Asunder, Fre:ac and Picard.

**Comment by SokoloffA** [comment]
I have been planning to abandon freeDB/GnuDB for a long time. 

They created a lot of problems.
1. They have an outdated database in which there are no new releases.
2. They are unreliable, suddenly freedb stopped working. Periodically Gnu DB does not response.
3. The problem with Unicode, freedb has a unicode version, but all the disks I saw were converted from the non-unicode version incorrectly.
4. It looks like GnuDB has removed support for URL ~cddb/cddb.cgi URL. In other words, GnuDB does not work in the Flacon for some time, and no one has opened the issue about it, i.e. no one really uses it.

Apparently it's time to throw out any CDDB reincarnations and replace them with MusicBrainz/Discogs.

Right now we can:
1. Display a warning to everyone, regardless of the language and IP address.
2. I can hide the button for everyone.
3. Do nothing, the feature is not working now.

**Comment by Eonfge** [comment]
Hide the button for now. If it's broken, it's better to mask the functionality until you've implemented an alternative.

**Comment by SokoloffA** [comment]
I added support for MusicBrainz and Discogs.
