### ISSUE TITLE
Qt scaling artifacts

### ISSUE THREAD

**Issue by fn-ix** [flacon/flacon#182]
With the global display scale set to 150% on X11, some of the icons in Flacon pixelate when scaled:
![Screenshot_20220725_152808](https://user-images.githubusercontent.com/16854594/180777660-4ce0b8bc-583d-463c-b9af-f368cdc6a822.png)

There should be a [quick fix](https://techbase.kde.org/Development/Tutorials/Graphics/HiDPI) for this issue.

**Comment by SokoloffA** [comment]
I will fix it soon

**Comment by SokoloffA** [comment]
Done in the 9.2.0 release
