### ISSUE TITLE
Embed Cover Art to Individual Tracks not Working

### ISSUE THREAD

**Issue by giardn** [flacon/flacon#183]
Hello,

I'm using flacon 8.3.0 with "Embed cover image in output files" checked, but the cover art isn't embedded into the individual files. I do get another copy of the art file in the working directory. No other issues with the program.

uname -a
Linux xxxx 5.18.14-1-siduction-amd64 #1 SMP PREEMPT_DYNAMIC siduction 5.18-14 (2022-07-23) x86_64 GNU/Linux

apt source list file
deb http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10 ./

Thanks for a great program, much appreciated.

**Comment by SokoloffA** [comment]
I have updated packages for Debian 10 & 11, please update to the 9.1.0 version. In 9x I rewrote tagging.

I apologize for my slowness in releasing Debian!

**Comment by giardn** [comment]
Thanks very much, confirmed it is now working!

**Comment by SokoloffA** [comment]
I'm glad!
