### ISSUE TITLE
Stuck at "Encoding 0%"

### ISSUE THREAD

**Issue by VeryOriginalNonsense** [flacon/flacon#184]
Hi,

When I try to convert a CD from APE or FLAC to individual tracks from a CUE I'm getting stuck on encoding for ~1/10 of the CDs I try to convert (to FLAC). It gets stuck at 0%. I'm getting a warning message in the CLI: "QIODevice::write (QProcess, "deemphasis"): device not open" for every track.

Version is 9.1.0; running Fedora 35 & got it from `dnf`. (CPU = Ryzen 7 5800x)

I tried to troubleshoot it, but since I'm not a Qt dev, that message is nonsensical to me. I have looked into permissions, filenames & possible missing dependencies, but I don't know what to look for.

**Comment by SokoloffA** [comment]
Sorry for the long silence, for some reason I didn't get a notification about a new issue.

Run the program in console with the --debug parameter. Something like:
```
flacon --debug 2>&1 | tee issue_184.log
```
And send me logs

**Comment by VeryOriginalNonsense** [comment]
No worries.

Logs: [issue_184.log](https://github.com/flacon/flacon/files/9498118/issue_184.log)

I generated logs by trying to convert just one of the problematic ones, containing three tracks.

**Comment by SokoloffA** [comment]
Thanks. But it looks like you ran the program without --debug key.
Also, please send me the problematic CUE file.

**Comment by VeryOriginalNonsense** [comment]
I'm using the debug flag, but I'm indeed not noticing anything at debug-level. I tried a couple of ways to get something to show up, but I end up with the same logs every time. Nothing useful other than the "deemphasis" thing. Am I not supposed to see something in the logs at debug level at this point?

This is the command I'm running & then I start conversion in the GUI:
```sh
FLACON_DEBUG=1 flacon --debug ./Klaus\ Schulze\ -\ Dune\ Deluxe\ Edition.flac.cue 2>&1 | tee issue_184.log
```

[Here](https://github.com/flacon/flacon/files/9499201/Klaus.Schulze.-.Dune.Deluxe.Edition.flac.cue.txt) is the CUE file however.

**Comment by SokoloffA** [comment]
I installed Fedora 35 in a virtual machine and was able to repeat your case. I hope I know the reason. You don't have the sox program installed. Just install it through dnf.

But I'm leaving this issue open because:
1. The program should notify the user that he does not have enough program. There are such checks, but for some reason they did not work
2. If external program can't work, the flacon should show error message instead printing endless messages to the log.
