### ISSUE TITLE
[FR] Transcode single image + cue sheets from one lossless format into another.

### ISSUE THREAD

**Issue by EldarAgalarov** [flacon/flacon#185]
Privet ;) I suggest to add a feature that converts one single image + cue sheet into another. For example many images are encoded with WavPack codec. I want to transcode these images using FLAC codec. Updated CUE sheet should be created with new image file name and extension.

Original example:
image.wv
image.cue with FILE image.wv WAVE

Transcoded example:
image.flac
image.cue - copy of original cue sheet with only one change - updated FILE property:
FILE "image.flac" WAVE

So Flacon will have both modes:

- Convert and cut one image into separate tracks;
- Convert from one image into another.

**Comment by SokoloffA** [comment]
Your question somewhat resembles the [question from the FAQ](https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions#i-dont-need-to-split-the-audio-i-just-want-to-change-the-audio-format-and-tags-in-the-existing-audio-file).

On the other hand, your offer has more to do with the main functionality of the program. I'll think about how I can implement your proposal without complicating the main program workflow (I passionately wish to keep the program easy to use for standard users).

By the way, you don't have to change the FILE tag in the CUE. Many CUE files that I have seen have the wrong value of the FILE tag. Therefore, most players have smart algorithm for search a pair of audio and CUE files.
