### ISSUE TITLE
Convertation error with two or more audio files

### ISSUE THREAD

**Issue by SkiF12** [flacon/flacon#186]
OS: Elementary OS 6
Flacon version: 9.1.0

I tried to convert an album that separated in two audio files and got error "I can't read: the audio file may be corrupted or an unsupported audio format". It doesn't depend on audio format(flac, wav, wv, etc), if you have more than one file it won't convert.
CUE looks like this:

        FILE "filename Side A.flac" WAVE
          TRACK 01 AUDIO
            TITLE "title"
            INDEX 01 00:00:00
         ...
        TRACK 06 AUDIO
            TITLE "title"
            INDEX 01 18:37:32
        FILE "filename Side B.flac" WAVE
          TRACK 07 AUDIO
            TITLE "title"
            INDEX 01 00:00:00
        ...

But if you make two cue files for each audio file and convert them one by one, it will work and you'll get full album. It would be great if Flacon could work with multiple audio files.

**Comment by SokoloffA** [comment]
The Flacon can work with multiple audio files. It looks like a bug.

1. You are using a fairly old version, but in 9.2 and 9.3, the algorithm associated with opening the file did not change. 
2. Are you using the version from packages or Flatpack?
3. Please, run the program from the console with the --debug parameter and send me output.
4. Send me the full CUE file
5. Send me the full list of files in the directory with Audio & CUE

**Comment by SkiF12** [comment]
I used flatpak. Flacon Version 9.3.0 doesn't work too. 
Debug log: https://pastebin.com/WJtisXgm
CUE: https://pastebin.com/vi2wShfQ 
File tree: https://pastebin.com/mMf6ZPQz

**Comment by SkiF12** [comment]
Thanks very much, confirmed it is working in 9.4.0.
