### ISSUE TITLE
Flacon for Debian 11 / bullseye

### ISSUE THREAD

**Issue by beng7** [flacon/flacon#187]
Hi there
Any chance you could update the instructions for Debian 11 / bullseye please?
Elternatively provide a .deb please?
thanks a lot

"Debian 10

echo "deb http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10 ./" > /etc/apt/sources.list.d/flacon.list
wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_10/Release.key -O- | apt-key add -
apt-get update
apt-get install flacon"

**Comment by SokoloffA** [comment]
I am already provide  .deb package for Debian 11. I just forgot to update the instructions. You will make me happy if you install the program following the instructions for testing.

### Debian 11

    echo "deb http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11 ./" > /etc/apt/sources.list.d/flacon.list
    wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key -O- | apt-key add -
    apt-get update
    apt-get install flacon

**Comment by beng7** [comment]
Hi again Alexander 

here is my feedback so far 
(i am running BunsenLabs Beryllium (bullseye)) 

I got a "permission denied" on the echo command so I added the line manually in my source.list.d 


I got this on the wget command: 
~$ wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key -O- | apt-key add - 
--2022-10-06 20:17:24-- http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key 
Resolving download.opensuse.org (download.opensuse.org)... 2001:67c:2178:8::13, 195.135.221.134 
Connecting to download.opensuse.org (download.opensuse.org)|2001:67c:2178:8::13|:80... Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)). 
E: This command can only be used by root. 
connected. 
HTTP request sent, awaiting response... 200 OK 
Length: 1101 (1.1K) [application/x-download] 
Saving to: ‘STDOUT’ 

- 0%[ ] 0 --.-KB/s in 0s 


Cannot write to ‘-’ (Broken pipe). 

--> working on it 


will keep you posted 
b 


----- Original Message -----

**Comment by beng7** [comment]
Hi again Alexander 


I managed to get flacon installed. 


From my investigation (see links provided), the 1st 2 commands should be re-written as: 


echo "deb http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11 ./" > /etc/apt/sources.list.d/flacon.list 
> 
echo "deb http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11 ./" | sudo tee /etc/apt/sources.list.d/flacon.list > /dev/null 
(from https://github.com/cozy/cozy-docs/issues/146) 



and 
wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key -O- | apt-key add - 

> 

wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key -O- | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/flacon.gpg 
(from https://itsfoss.com/apt-key-deprecated/) 


both tested and worked 
I hope this helps 

Thanks a lot for your work on Flacon! 
ben 


----- Original Message -----

**Comment by SokoloffA** [comment]
The **sudo** is installed by default in Ubuntu, unfortunately in Debian isn't so. Therefore, the instructions say _"Open up a terminal and input these commands as root"_. But I guess you're right and I'll change the instructions.

And why did you replace ```apt-key add -``` with ```gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/flacon.gpg```? 
Why do you use sudo is clear to me, but why do you use gpg? The following command doesn't work?

```
wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key -O- | sudo apt-key add -
```

**Comment by giardn** [comment]
To SokoloffA,

I realize this is closed but it makes sense to put this here. The reason for --dearmor is:

W: http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/./InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

Not sure about other distros but this is a thing for Debian.

Regards,
Nathan

**Comment by SokoloffA** [comment]
OBS return the [file](http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key) as ASCII.
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.5 (GNU/Linux)
...
-----END PGP PUBLIC KEY BLOCK-----
```

So, if I am not mistaken, the line of the manual should look like this:
```
wget -qO- http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key | sudo tee /etc/apt/trusted.gpg.d/flacon.asc
```

Is this correct?

**Comment by giardn** [comment]
I tested the above in Debian and it worked for me, I don't get the apt-key deprecation error. I don't personally use sudo so I ran it as root.

**Comment by giardn** [comment]
A follow-on to my last post, the website previously linked by beng7 https://itsfoss.com/apt-key-deprecated/ says to test the key with 

`file repo-key.gpg`

and if the output is like ‘PGP public key block’, it is armored file and needs to be converted to binary.

so that's why it needs to be 

`wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_11/Release.key -O- | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/flacon.gpg`

Hope this helps.
Nathan

**Comment by giardn** [comment]
That's great, thank you!
