### ISSUE TITLE
Cue sheet generation errors.

### ISSUE THREAD

**Issue by jbnicar** [flacon/flacon#189]
Cue sheets are produced without index values or wildly inaccurate ones.

**Comment by SokoloffA** [comment]
Unfortunately, you didn't give any information.  But I think I know what the misunderstanding is:
The indexes in the new CUE file are considered relative to the audio files that are being tracked, so they are almost always zero. This CUE file is needed to join per-track audio to the large one for album. 

I specifically double-checked, the indexes are calculated correctly.

We have CUE file:
```
REM GENRE "Modern Rock"
REM DATE 2011
REM DISCID 12345678
REM COMMENT "ExactAudioCopy v0.95b4"
PERFORMER "Test for flacon"
TITLE "Short file"
FILE "short.wav" WAVE
  TRACK 01 AUDIO
    TITLE "Short track 1"
    INDEX 00 00:00:00
    INDEX 01 00:00:33
  TRACK 02 AUDIO
    TITLE "Short track 2"
    INDEX 01 00:46:00
  TRACK 03 AUDIO
    TITLE "Short track 3"
    INDEX 00 01:22:22
    INDEX 01 01:25:10
  TRACK 04 AUDIO
    TITLE "Short track 4"
    INDEX 00 02:39:54
    INDEX 01 02:41:05
```

Generating an audio album duration 3 min
```sox  -r 44100 -n -b 16 -c 2 -R source.wav synth 180```

Running flacon. Select the FLAC format, make sure that the option *"Create a per track CUE: write to a file"* is enabled.
Splitting source.wav

Joining tracks into one file *joined.wav*
```shntool join -O always -o wav PATH_TO_MUSIC_DIR/"2011 - Short file"/*.flac```

We check that the file bitwise matches the original one:
```shntool hash  source.wav joined.wav```

I have the hashes matched.

**Comment by jbnicar** [comment]
I apologize for not giving you much information. I'm going to split an actual CD and compare the new cue to the original one. I became aware of this problem because a program I use to verify against AccurateRip spits out an error about Flacon's generated cue files.

**Comment by SokoloffA** [comment]
I didn't get any feedback and can't reproduce the problem. I think there was a confusion with relative and absolute time in the indices.
