### ISSUE TITLE
Document how to compile

### ISSUE THREAD

**Issue by jacek99** [flacon/flacon#19]
Hi, could you document in the readme how can this be compiled and what dependencies are required?

I am trying to install this on Fedora 22 where there is no RPM for it, so need to compile from scratch.

The usual ./configure / make / make install does not seem to work here....

**Comment by SokoloffA** [comment]
First,  you can try to use RPM spec from the [packages repository](https://github.com/flacon/packages), alternatively you can try [SPEC for ROSALinux](https://abf.rosalinux.ru/sokoloff/flacon)

Second, I think ["How to build" document](https://github.com/flacon/flacon/wiki/How-to-build) will helpful for you.
