### ISSUE TITLE
Artist field editing jumping behaviour

### ISSUE THREAD

**Issue by msdobrescu** [flacon/flacon#191]
Editing the artist field is difficult due to the fact that the caret moves at the end of the content almost at any key stroke.
For example, trying to correct a character, if it is deleted, the caret jumps at the end and must be positioned again in order to type the new character.

**Comment by SokoloffA** [comment]
I confirm that this is a bug. I'll fix it this weekend. And I'll post a beta version with a few changes.
Are you using the Linux or macOS version? I'll let you know when the beta version is ready.

**Comment by msdobrescu** [comment]
For the sake of readability, I repeat :D. I use a Gentoo-based Linux, MocaccinoOS.

**Comment by SokoloffA** [comment]
I found a number of issues with the new functionality from the beta version. Therefore, I have published bug fixes in a stable codebase. Your problem is fixed in [flacon 9.5.1](https://github.com/flacon/flacon/releases/tag/v9.5.1)
