### ISSUE TITLE
KDE Neon compilation error

### ISSUE THREAD

**Issue by Blad3forc3** [flacon/flacon#192]
I'm getting this error while compiling on KDE Neon 22.04

[100%] Linking CXX executable flacon
/usr/bin/ld: /usr/local/lib/libtag.a(tzlib.cpp.o): undefined reference to symbol 'inflateEnd'
/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/flacon.dir/build.make:1873: flacon] Error 1
make[1]: *** [CMakeFiles/Makefile2:131: CMakeFiles/flacon.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by SokoloffA** [comment]
I found this [post on stackoverflow](https://stackoverflow.com/questions/42215679/error-linking-taglib-to-qt) . 
Please try in converter/CMakeLists.txt replace the line 
```
target_link_libraries(${PROJECT_NAME} PRIVATE ${LIBRARIES} ${QT_LIBRARIES} Qt5::Widgets)
```
 with 
```
target_link_libraries(${PROJECT_NAME} PRIVATE ${LIBRARIES} ${QT_LIBRARIES} Qt5::Widgets "z")
```
add  "z" at end. 

And let me know about the result, if it works, I'll add this fix.

**Comment by Blad3forc3** [comment]
Yes that works, thanks very much
