### ISSUE TITLE
File .cue does not exist (Linux Mint Cinnamon 21)

### ISSUE THREAD

**Issue by sergiozar** [flacon/flacon#193]
In my recent installation of LMC 21 I installed the Flatpack from the App Manager but I tried to split two or three flac albums and it didn't work, saying the file does not exists. Initially I controlled the syntax of the .cue file but all seems ok so I uninstalled the flatpack and installed it from the ubuntu repo. After that, the sames .cue file, with this version of flatpack, was working fine.
I hope this issue its not a replica and I'm sorry for my poor english.

**Comment by SokoloffA** [comment]
It's definitely related to Flatpack, you're not the only one facing this problem.
You have several options:
1. [Manually select both audio and CUE files](https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions#i-add-the-file-but-convert-button-is-not-active).
2.  [Add to Flatpack read permissions for all files](https://github.com/flacon/flacon/issues/188).
3. If I'm not mistaken, the LMC is based on Ubuntu. [So you can install a normal deb package](https://flacon.github.io/download/#ubuntu).

**Comment by SokoloffA** [comment]
I published [AppImage](https://github.com/flacon/flacon/releases/download/v9.5.1/flacon-9.5.1-x86_64.AppImage) package for the program. Unfortunately, I have no way to check it.  If you're interested, you can try using AppImage instead of Flatpack.

**Comment by sergiozar** [comment]
Thank You for your response. 
I uninstalled the flatpack a few minutes after your first response. 
Since I don't have seen a "download" button in the download page for the Appimage (https://flacon.github.io/download/) (and I know it's because I don't understand well how Github works...) I used the Ubuntu repo with success.
I see that Your link for the Appimage work, but wouldn't be better to have a button for download it?
Thank you for Your work and Your responses.

**Comment by SokoloffA** [comment]
@sergiozar 
> I uninstalled the flatpack a few minutes after your first response.

Did you have any problems with the non flatpack version?

>Since I don't have seen a "download" button in the download page

Of course I'll add a link, but as I said, I don't have the opportunity to check AppImage right now (I can't even start a virtual machine, because only Apple M1 are available to me). Therefore, we can say that this is a beta version of the package. The code itself is similar to the stable 5.9.1.

**Comment by sergiozar** [comment]
No, the version of the Ubuntu repo at the moment run very well, without any problem, for what I can see.
Now I understand why there isn't a public link to download the Appimage, thank You.

**Comment by SokoloffA** [comment]
I'm glad! So I close the issue
