### ISSUE TITLE
List Gentoo-build on the website

### ISSUE THREAD

**Issue by rndxelement** [flacon/flacon#195]
Greetings, 

flacon is available for the Gentoo GNU/Linux distribution.
It can be installed via `emerge --ask media-sound/flacon`.
The current set of supported versions is listed [here](https://packages.gentoo.org/packages/media-sound/flacon).
Maybe Gentoo could be added to the website. Thanks.

**Comment by SokoloffA** [comment]
OK, I'll add Gentoo section

**Comment by rndxelement** [comment]
Thanks!

**Comment by SokoloffA** [comment]
Done

**Comment by rndxelement** [comment]
Thanks :)
