### ISSUE TITLE
Position of the main window was not saved

### ISSUE THREAD

**Issue by mkll** [flacon/flacon#198]
After upgrading from version 9.5.x to 10.0.0, the program stopped saving the position of the main window.

(macOS 11.4 Big Sur)

**Comment by mkll** [comment]
Hmm, some settings doesn't saved too, e.g. output directory.

**Comment by mkll** [comment]
So I reverted to 9.5.1, it helped, the program works fine.

**Comment by SokoloffA** [comment]
I added saveing and loading of the main window position.  I checked it out on:
* macOS 13.2 Ventura
* Fedora with XWindow

As I understand the position will [not work in Wayland](https://bugreports.qt.io/browse/QTBUG-110119)

> Hmm, some settings are not saved too, eg. output directory

I'm working on it.

**Comment by SokoloffA** [comment]
Included in release 11.0.0
