### ISSUE TITLE
Invalid data included in the output flac audio file.

### ISSUE THREAD

**Issue by Revincx** [flacon/flacon#199]
The output flac files sometimes includes invalid data, although most of media players can decode it anyway, but chromium could not play the flac file: 

![image](https://user-images.githubusercontent.com/25524750/231936009-9328fb5b-6973-4812-9f17-b449c36e2bd1.png)

Use `ffmpeg -err_detect explode -i splitted.flac out.wav` to detect error :

```
  built with gcc 12.2.1 (GCC) 20230201
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[flac @ 0x56322892cf40] Could not read mimetype from an attached picture.
[flac @ 0x56322892cf40] Error parsing attached picture.
splitted.flac: Invalid data found when processing input
```

The problem can be easily resolved by repack the splitted flac file using ffmpeg:

```bash
ffmpeg -i splitted.flac -c copy splitted_repack.flac
```

The splitted_repack.flac has no errors and can be played by chromium correctly.

**Comment by SokoloffA** [comment]
It seems to be related to the embedded cover.  I haven't been able to reproduce the problem yet.
Please send me the full output of the `metaflac --list` command for the problematic file. Or better yet, send me a such problematic file.

**Comment by Revincx** [comment]
> It seems to be related to the embedded cover. I haven't been able to reproduce the problem yet. Please send me the full output of the `metaflac --list` command for the problematic file. Or better yet, send me a such problematic file.

The output of `metaflac --list` is attached [here](https://github.com/flacon/flacon/files/11233111/metaflac.txt). As the track audio files are too large, I uploaded them to OneDrive, please [click here to download](https://rua23-my.sharepoint.com/:f:/g/personal/i_revincx_icu/Ek5RVAdKSURGmDmriPrHLIQBnEod7gc8lky5_DMtVpMgJg?e=Kney01) if you need. The problematic flac files are under `Splitted FLACs` folder.

**Comment by Revincx** [comment]
@SokoloffA It seems that the cause of this problem is that flacon not set the MIME type of the cover image. When I manually set the MIME type of the cover image to `image/jpeg`, it works.

**Comment by Revincx** [comment]
Tried to build the latest master branch, the issue had been fixed. 😥

I'm sorry for the inconvenience.
