### ISSUE TITLE
Os/2

### ISSUE THREAD

**Issue by TeLLie** [flacon/flacon#20]
Hello

I poorted Flacon to OS/2 using Qt 4.7.2 Gcc 4.9.2 and cmake 3.3.0

But when i try to run the test i get:

H:\flacon-1.0.1\build\tests>flacon_test.exe
********\* Start testing of TestFlacon *********
Config: Using QTest library 4.7.3, Qt 4.7.3
FAIL!  : TestFlacon::initTestCase() Program "shntool.exe" not found.
   Loc: [H:/flacon-1.0.1/tests/testflacon.cpp(74)]
FAIL!  : TestFlacon::initTestCase() Program "avconv.exe/ffmpeg.exe" not found.
   Loc: [H:/flacon-1.0.1/tests/testflacon.cpp(84)]
PASS   : TestFlacon::cleanupTestCase()
Totals: 1 passed, 2 failed, 0 skipped
********\* Finished testing of TestFlacon *********

Also i see this behavior in the gui flacon..
Os2 starts it's progs through a .exe like shntool.exe

I change in the testflacon.cpp
QString shntool = settings->findProgram("shntool"); 
to
QString shntool = settings->findProgram("shntool.exe");

But it still don't notice the shntool.exe i have in path.

Any idea how to fix this ??

**Comment by SokoloffA** [comment]
I added DEF_BINARY_EXT variable in the CMake file. CMake automatically detects OS, and if it is OS/2 then assign ".exe". I hope it should to help.

**Comment by TeLLie** [comment]
Hello,

Thankz for helping me in here :)
But i download the master branch and compile it, but ....

H:\flacon-master\build\tests>flacon_test.exe
********* Start testing of TestFlacon *********
Config: Using QTest library 4.7.3, Qt 4.7.3
FAIL!  : TestFlacon::initTestCase() Program "shntool" not found.
   Loc: [H:/flacon-master/tests/testflacon.cpp(74)]
FAIL!  : TestFlacon::initTestCase() Program "avconv/ffmpeg" not found.
   Loc: [H:/flacon-master/tests/testflacon.cpp(84)]
PASS   : TestFlacon::cleanupTestCase()
Totals: 1 passed, 2 failed, 0 skipped
********* Finished testing of TestFlacon *********

Seems not to help...

**Comment by TeLLie** [comment]
Hi
Also when i load a wav or flac file notting seems to work, when i add flac file notting happens it seems..

see http://imagizer.imageshack.com/img673/5525/A7qiWk.png

**Comment by rompolompo** [comment]
You need to specify a cue file.

**Comment by SokoloffA** [comment]
This is related with your previous problem. The flacon used shntool for
detecting supported audio files

среда, 2 сентября 2015 г. пользователь TeLLie написал:

> Hi
> Also when i load a wav or flac file notting seems to work, when i add flac
> file notting happens it seems..
>
> see http://imagizer.imageshack.com/img673/5525/A7qiWk.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flacon/flacon/issues/20#issuecomment-137217024>.
>


-- 
Best regards,
Alexander.

**Comment by SokoloffA** [comment]
> But i download the master branch and compile it, but ....

You should rebuild the program from scratch - remove all built files and run cmake and make again.
If this not help, add following line at the end of CMakeLists.txt and show me output of cmake.

    message(STATUS "CMAKE_SYSTEM_NAME:'${CMAKE_SYSTEM_NAME}'")

**Comment by TeLLie** [comment]
Hello,

On  3-09-15 13:32, Alexander Sokolov wrote:
>     But i download the master branch and compile it, but ....
>
> You should rebuild the program from scratch - remove all built files and
> run cmake and make again.
> If this not help, add following line at the end of CMakeLists.txt and
> show me output of cmake.

I tried again with cmake and make

This is output from cmake...

http://pastebin.com/kh1Fg051
>
> |message(STATUS "CMAKE_SYSTEM_NAME:'${CMAKE_SYSTEM_NAME}'")
> |


>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flacon/flacon/issues/20#issuecomment-137412776>.
>

-- 
With kind regards from the Netherlands,
                     Elbert & Nicole Pol

**Comment by SokoloffA** [comment]
I create OS2 baranch with debuging output. Please build it an show me a output of cmake and flacon_test

**Comment by SokoloffA** [comment]
And also, is shntool in PATH variabled directory?

**Comment by TeLLie** [comment]
Yes i have shntool.exe in path

**Comment by TeLLie** [comment]
Ok i build os2 package..
It's looking for wrong file name ...

See this output from the test

********* Start testing of TestFlacon *********
Config: Using QTest library 4.7.3, Qt 4.7.3
QDEBUG : TestFlacon::initTestCase() QString Settings::findProgram(const QString&) const ----------------------------- 
QDEBUG : TestFlacon::initTestCase() Paths: ("C", "\usr\libexec\bin;C", "\USR\SBIN;C", "\USR\BIN;c", "\usr\lib\qt4\bin;c", "\extras\bin;C", "\MPTN\BIN;C", "\IBMCOM;C", "\TCPIP\BIN;C", "\ECS\BIN;C", "\EMX\BIN;C", "\IBMGSK50\BIN;C", "\IBMGSK40\BIN;C", "\IBMGSK\BIN;C", "\OS2;C", "\OS2\SYSTEM;C", "\OS2\INSTALL;C", "\;C", "\OS2\MDOS;C", "\OS2\APPS;C", "\PROGRAMS\OPENJDK6\BIN;C", "\MMOS2\FREEDB;C", "\MMOS2;C", "\MMOS2\MMPLAYER;C", "\PROGRAMS\4OS2;E", "\NDFS;C", "\OS2TK45\som\common;C", "\OS2TK45\som\bin;C", "\OS2TK45\bin;C", "\TOOLS\dfsee\bin;e", "\WATCOM\BINP;e", "\WATCOM\BINW;") 
QDEBUG : TestFlacon::initTestCase() * File: "C/mp3gain.exe" 
QDEBUG : TestFlacon::initTestCase()   - exists: false 
QDEBUG : TestFlacon::initTestCase()   - isExecutable: false 
QDEBUG : TestFlacon::initTestCase() * File: "/usr/libexec/bin;C/mp3gain.exe" 
QDEBUG : TestFlacon::initTestCase()   - exists: false 
QDEBUG : TestFlacon::initTestCase()   - isExecutable: false 
QDEBUG : TestFlacon::initTestCase() * File: "/USR/SBIN;C/mp3gain.exe" 
QDEBUG : TestFlacon::initTestCase()   - exists: false 
QDEBUG : TestFlacon::initTestCase()   - isExecutable: false 
QDEBUG : TestFlacon::initTestCase() * File: "/USR/BIN;c/mp3gain.exe" 
QDEBUG : TestFlacon::initTestCase()   - exists: false 
QDEBUG : TestFlacon::initTestCase()   - isExecutable: false 
QDEBUG : TestFlacon::initTestCase() * File: "/usr/lib/qt4/bin;c/mp3gain.exe" 
QDEBUG : TestFlacon::initTestCase()   - exists: false 
QDEBUG : TestFlacon::initTestCase()   - isExecutable: false 
QDEBUG : TestFlacon::initTestCase() * File: "/extras/bin;C/mp3gain.exe" 

It should be like
QDEBUG : TestFlacon::initTestCase() * File: "/extras/bin;C/mp3gain.exe" 
should be
QDEBUG : TestFlacon::initTestCase() * File: "c:/extras/bin/mp3gain.exe" 

Here is full output:
pastebin.com/WNMQSkyP

**Comment by SokoloffA** [comment]
Please, try new version from OS2 branch

**Comment by TeLLie** [comment]
I try new build and compile it, but now i get:

Scanning dependencies of target flacon
Scanning dependencies of target flacon_test
[ 42%] Building CXX object CMakeFiles/flacon.dir/tagset.cpp.obj
Syntax error: Unterminated quoted string
make[2]: *** [CMakeFiles/flacon.dir/tagset.cpp.obj] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 42%] Building CXX object CMakeFiles/flacon.dir/main.cpp.obj
[ 43%] Building CXX object CMakeFiles/flacon.dir/disk.cpp.obj
Syntax error: Unterminated quoted string
make[2]: *** [CMakeFiles/flacon.dir/main.cpp.obj] Error 2
Syntax error: Unterminated quoted string
make[2]: *** [CMakeFiles/flacon.dir/disk.cpp.obj] Error 2
[ 43%] Building CXX object CMakeFiles/flacon.dir/project.cpp.obj
Syntax error: Unterminated quoted string
make[2]: *** [CMakeFiles/flacon.dir/project.cpp.obj] Error 2
make[1]: *** [CMakeFiles/flacon.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object tests/CMakeFiles/flacon_test.dir/testflacon.cpp.obj
[ 44%] Building CXX object tests/CMakeFiles/flacon_test.dir/__/tagset.cpp.obj
[ 45%] Building CXX object tests/CMakeFiles/flacon_test.dir/__/disk.cpp.obj
Syntax error: Unterminated quoted string
[ 45%] Building CXX object tests/CMakeFiles/flacon_test.dir/__/project.cpp.obj
make[2]: *** [tests/CMakeFiles/flacon_test.dir/testflacon.cpp.obj] Error 2
Syntax error: Unterminated quoted string
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [tests/CMakeFiles/flacon_test.dir/__/tagset.cpp.obj] Error 2
Syntax error: Unterminated quoted string
[ 46%] Building CXX object tests/CMakeFiles/flacon_test.dir/__/settings.cpp.obj
make[2]: *** [tests/CMakeFiles/flacon_test.dir/__/disk.cpp.obj] Error 2
Syntax error: Unterminated quoted string
make[2]: *** [tests/CMakeFiles/flacon_test.dir/__/project.cpp.obj] Error 2
Syntax error: Unterminated quoted string
make[2]: *** [tests/CMakeFiles/flacon_test.dir/__/settings.cpp.obj] Error 2
make[1]: *** [tests/CMakeFiles/flacon_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by SokoloffA** [comment]
Oh, sorry! Try new version from OS2 branch

**Comment by TeLLie** [comment]
Ok, now it;s building :)

pastebin.com/ehBjvkmR

**Comment by SokoloffA** [comment]
And work?

**Comment by TeLLie** [comment]
Yes it finds now all the exe stuff in de extras/bin :)
Have to test more with the cue file etc..

**Comment by TeLLie** [comment]
Ok i have load a cue file and the i see:
File <b>K:/Mp3/SnowiesFlacCollectie2375920133ScreensSN/Fallen Empires.cue</b> contains several FILE tags.<br>These CUE files are not supported yet."
Where to find a proper cue file ?

**Comment by SokoloffA** [comment]
Yes CUE files with several FILE tags not supported now. https://github.com/flacon/flacon/issues/13
I can't find free lossless music in the internet. But some bad guys use torrents for download files, only for testing sure.

**Comment by TeLLie** [comment]
Ok i found a cue file, see http://imagizer.imageshack.com/img912/8981/MI6oNH.png

But how to convert now and get info from database CDDB ?

I'm a bit confused in here, but that could be just me :)

**Comment by SokoloffA** [comment]
As you can see, the program could not find the audio file for this CUE (yellow triangle icon) . For  converting you need a pair of CUE and audio file. Every CUE-file has FILE tag that contains the name of the audio file. Unfortunately often this tag has incorrect filename. So the program tries to find the name of the audio file empirically. After that the program starts shntool to make sure that the file format is supported.
So, there may be several reasons:
  1. The audio file is missing or its name is not similar to the name of the CUE file. You can click an small button with ellipsis ad select audio by hand.
  2. The program incorrectly identifies the file type, perhaps because of an error in the program.

Send me at mail (sokoloff.a AT gmail.com) this CUE and the list of files in the directory.
