### ISSUE TITLE
feature request: add a "convert selected" icon

### ISSUE THREAD

**Issue by Uhter** [flacon/flacon#206]
Hi everybody,

First of all, thank you all devs for this open source software.
It would be great if − beside of "Convert" icon − there was another icon: "Convert selected".

For now, we have to go _Menu File > Converted selected_ or execute _Ctrl+Shift+W_ (that I always forget). I think a dedicated icon would be useful and more intuitive. What do you think about it?

![tmpFLACON](https://github.com/flacon/flacon/assets/7294071/7963591e-afb8-4f66-a90e-a70491fac9d2)

**Comment by SokoloffA** [comment]
Two buttons is too much. I added a drop-down menu on the button with the last selection remembered.

https://youtu.be/aXoIcHE3r2A

**Comment by Uhter** [comment]
It will be a good improvement. In the next release?

**Comment by SokoloffA** [comment]
I've already added that to the code.
This will go in the next release.
If you want to get it now, you can use the [development AppImage](https://github.com/flacon/flacon/suites/13535546905/artifacts/744402886).

**Comment by Uhter** [comment]
You handled it. Thank you very much ;)
