### ISSUE TITLE
Support multiple dot extensions (in other words, support matching audio filenames)

### ISSUE THREAD

**Issue by jbn-github** [flacon/flacon#21]
flacon 1.2.0 doesn't like multiple dot extensions on audio filenames (such as `something.ape.flac`) instead preferring the ultimate dot extension only (`something.flac`). Multiple dot extensions fail even if the cuesheet lists the proper filename with the multiple dot extensions (`FILE "something.ape.flac" WAVE`).

I see great value in looking up other files when the filename mentioned in a FILE line is not found; that's a huge convenience to have flacon locate the probable audio file. But I'm not sure why a perfectly matching filename in a FILE line should ever fail to work. This strikes me as a bug.

**Comment by SokoloffA** [comment]
Hm, can't reproduce this. Please send me CUE and listing of directory.

**Comment by jbn-github** [comment]
Alexander Sokolov wrote:
> Hm, can't reproduce this. Please send me CUE and listing of directory.

I've attached a cuesheet. Here's a directory listing:

$ ls 'Dufay - Music for St Anthony of Padua - Andrew Kirkman. The Binchois 
Consort'
Andrew Kirkman_ The Binchois Consort - Dufay_ Music for St Anthony of 
Padua.flac
cover.png
Andrew Kirkman_ The Binchois Consort - Dufay_ Music for St Anthony of Padua.cue

There are 3 files: the cuesheet, an audio file in FLAC format, and a cover 
PNG image.

If you place an audio file with the proper name in this directory and open 
that directory in flacon, flacon reads the cuesheet and finds the audio 
file without problem. Everything proceeds normally and works.

If you quit flacon, then rename the audio file to end in ".ape.flac" 
instead of ".flac" and make the corresponding adjustment to the cuesheet in 
the FILE line then open the folder in flacon again (just as before) flacon 
will not find the cuesheet, not list the tracks, and you'll get a mostly 
empty flacon window. You could manually select the cuesheet using the small 
down-arrow button to pick the cuesheet, but you shouldn't have to do that. 
flacon should see that the cuesheet points to the file with its proper name 
-- a name that happens to have two dot extensions, but that should be 
irrelevant (in my opinion).

Renaming the audio file and changing the cuesheet's FILE line again back to 
ending in only ".flac" (removing the ".ape") and re-opening the directory 
in flacon again will restore a working cuesheet + audio file.

**Comment by SokoloffA** [comment]
Aha, confirm. I'll fix it soon.

**Comment by SokoloffA** [comment]
I hope this patch should work
