### ISSUE TITLE
Delete source dialogue exceeds screen size

### ISSUE THREAD

**Issue by audiomuze** [flacon/flacon#211]
![image](https://github.com/flacon/flacon/assets/6852511/c39240e2-f3e2-44b3-9f40-c0bbae79865b)

As you can see the action dialogue disappears and the list isn't scrollable.

The presentation of the list can also be improved for readability.

**Comment by SokoloffA** [comment]
Done. If you wish, you can test the program with the [AppImage version of the program](https://github.com/flacon/flacon/suites/16133580738/artifacts/921160575).

**Comment by SokoloffA** [comment]
Fixed in 11.3.
