### ISSUE TITLE
Patterns matching must be case sensitive

### ISSUE THREAD

**Issue by msdobrescu** [flacon/flacon#214]
Adding a pattern like %A - %a/%n - %t would save it to patterns history.
Then, it is impossible to keep and use one like %a - %A/%n - %t, because the moment the user leaves the edit box this is matched against the existing one and that is found and set back to %A - %a/%n - %t.
The user must delete one pattern in order to use the other, so the pattern search in the history must be case sensitive to avoid it.

**Comment by SokoloffA** [comment]
Done

**Comment by SokoloffA** [comment]
You'll make me happy if you test the fix. To do this, you can use the [AppImage version of the program](https://github.com/flacon/flacon/actions/runs/6175880273).

**Comment by msdobrescu** [comment]
It looks it works, but crashes like crazy - apparently when displaying a tooltip.

**Comment by SokoloffA** [comment]
I made a different solution. Please check if the program stopped crashing. [AppImage](https://github.com/flacon/flacon/suites/16246032104/artifacts/927745076)

**Comment by msdobrescu** [comment]
This one did not crash. But it does not have a default pattern selection and when I set it it losses it when moving to a different control.

**Comment by SokoloffA** [comment]
I'm already ashamed to write, but I did it once again:)
I tested, now it works correctly (I hope). [AppImage](https://github.com/flacon/flacon/suites/16295287904/artifacts/930446938)

**Comment by SokoloffA** [comment]
Fixed in 11.3.

**Comment by msdobrescu** [comment]
Sorry, man,  I could not find the time to test lately.
