### ISSUE TITLE
Directory/pattern preferences in audio profiles don't save

### ISSUE THREAD

**Issue by Nekotekina** [flacon/flacon#215]
![image](https://github.com/flacon/flacon/assets/6028184/d9acf210-3311-4e62-a836-7ea517a7e5d8)
After applying directory or pattern settings, it does not appear on the next startup.
I once erased them completely.
Ubuntu 22.04, AppImage version 11.2.0
![image](https://github.com/flacon/flacon/assets/6028184/ee3852a2-66b7-4a8f-bcf0-0110b14c0a78)

**Comment by SokoloffA** [comment]
Done

**Comment by SokoloffA** [comment]
You'll make me happy if you test the fix. To do this, you can use the [AppImage version of the program](https://github.com/flacon/flacon/actions/runs/6175880273).

**Comment by Nekotekina** [comment]
Yes, seems to work, thank you!

**Comment by SokoloffA** [comment]
Fixed in 11.3.
