### ISSUE TITLE
DeEmphasis results in error when trying to split a file

### ISSUE THREAD

**Issue by esatsana** [flacon/flacon#218]
When trying to split a flac file, if the .cue file contains "FLAGS PRE",
Flacon gives the following error: 

The '--type' program crashes with an error: execvp: No such file or directory

And yes, Sox is installed:
$ which sox
/bin/sox

$ LC_ALL=C flacon --debug
2023.09.19 16:07:09.746 CEST [21933] default: info: Start flacon  11.2.0  + git  makepkg   aa3c55945e4b73cf008473a634544b8c871364cf
2023.09.19 16:07:14.759 CEST [21933] SearchAudioFiles: debug: Search audio for "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).cue"
2023.09.19 16:07:14.759 CEST [21933] SearchAudioFiles: debug: fullPath= "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).cue"
2023.09.19 16:07:14.759 CEST [21933] SearchAudioFiles: debug: Audio files= ("")
2023.09.19 16:07:14.759 CEST [21933] AudioFileMatcher: debug: mFileTags = ("Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac")
2023.09.19 16:07:14.759 CEST [21933] AudioFileMatcher: debug: mAllAudioFiles:  "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:14.759 CEST [21933] AudioFileMatcher: debug: Return trivial: QMap(("Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac", ("/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac")))
2023.09.19 16:07:14.759 CEST [21933] SearchAudioFiles: debug:  * 0  test audio file  "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:14.759 CEST [21933] InputAudioFile: debug: load "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:14.768 CEST [21933] InputAudioFile: debug: Audio is loaded: format = "FLAC" mDuration = 3459600 mCdQuality = true mSampleRate = 44100 mBitsPerSample = 16
2023.09.19 16:07:14.768 CEST [21933] SearchAudioFiles: debug: set audio "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.473 CEST [21933] Converter: debug: Start converter: 1 
 ID:      FLAC 
 Format:  FLAC 
 Name:    Flac 
 Valid:   true 

2023.09.19 16:07:18.473 CEST [21933] Converter: debug: Temp dir = ""
2023.09.19 16:07:18.473 CEST [21933] Converter: debug: Threads count 8
2023.09.19 16:07:18.473 CEST [21933] DiscPipeline: debug: Create tmp dir "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.474 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.475 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.475 CEST [21933] DiscPipeline: debug: Create directory for output files "/home/olivier/test"
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   track index:  0
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_01.wav"
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   *  "00:00:00" : "05:17:45"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   track index:  1
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_02.wav"
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   *  "05:17:45" : "08:41:70"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   track index:  2
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_03.wav"
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   *  "08:41:70" : "10:02:32"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   track index:  3
2023.09.19 16:07:18.475 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_04.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "10:02:32" : "12:03:07"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  4
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_05.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "12:03:07" : "16:45:45"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  5
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_06.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "16:45:45" : "20:31:32"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  6
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_07.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "20:31:32" : "22:27:45"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  7
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_08.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "22:27:45" : "22:49:70"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  8
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_09.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "22:49:70" : "25:18:07"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  9
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_10.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "25:18:07" : "32:09:20"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  10
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_11.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "32:09:20" : "34:35:45"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  11
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_12.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "34:35:45" : "38:08:45"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  12
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_13.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "38:08:45" : "40:03:45"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  13
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_14.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "40:03:45" : "44:23:27"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   track index:  14
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_15.wav"
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.476 CEST [21950] Splitter: debug:   *  "44:23:27" : "45:55:45"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   track index:  15
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_16.wav"
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   *  "45:55:45" : "47:58:32"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   track index:  16
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_17.wav"
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   *  "47:58:32" : "53:15:07"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug: Spliter job _________________________
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   track index:  17
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   outFileName:  "/home/olivier/test/tmp.USpEqZ/track-0001_18.wav"
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   isPregap:     false
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   chunks:    
2023.09.19 16:07:18.477 CEST [21950] Splitter: debug:   *  "53:15:07" : "00:00:00"  file "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"
2023.09.19 16:07:18.484 CEST [21950] Splitter: debug: extract:  "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"  [ "00:00:00" : "05:17:45" ] OUT: "/home/olivier/test/tmp.USpEqZ/track-0001_01.wav"
2023.09.19 16:07:18.906 CEST [21950] Splitter: debug: Splitter trackReady:  Track { trackNum: 1 trackCount:18 diskId:"EB0D8312" Artist:"London Symphony Orchestra, Per Dreier" Album:"Edvard Grieg: Peer Gynt (Disc 1)" Title:"PEER GYNT, Complete Music for Ibsen's Dramatic Poem - 1. Prelude, Act 1 (orchestra)"} "/home/olivier/test/tmp.USpEqZ/track-0001_01.wav"
2023.09.19 16:07:18.906 CEST [21950] Splitter: debug: extract:  "/home/olivier/test/Grieg - Peer Gynt - LSO, Per Dreier (Disc 1).flac"  [ "05:17:45" : "08:41:70" ] OUT: "/home/olivier/test/tmp.USpEqZ/track-0001_02.wav"
2023.09.19 16:07:18.907 CEST [21953] Encoder: debug: Start encoder: "/bin/flac --force --silent --compression-level-8 - -o /home/olivier/test/tmp.USpEqZ/track-0001_01.encoded.flac"
2023.09.19 16:07:18.907 CEST [21953] Encoder: debug: Input audio: bitsPerSample = 16  sampleRate = 44100
2023.09.19 16:07:18.907 CEST [21953] Encoder: debug: Required:    bitsPerSample = 16  sampleRate = 44100
2023.09.19 16:07:18.907 CEST [21953] Encoder: debug: Resampling is not required
2023.09.19 16:07:18.907 CEST [21953] Encoder: debug: Start deEmphasis: "--type wav - --type wav - deemph"
2023.09.19 16:07:18.910 CEST [21953] ExtProgram: warning: ERROR
2023.09.19 16:07:18.910 CEST [21953] ExtProgram: warning: "deemphasis: The '--type' program crashes"
2023.09.19 16:07:18.910 CEST [21953] ExtProgram: warning: Program with args: "--type wav - --type wav - deemph"
2023.09.19 16:07:18.910 CEST [21953] ExtProgram: warning: Error: QProcess::FailedToStart
2023.09.19 16:07:18.910 CEST [21953] ExtProgram: warning: Error string: "execvp: No such file or directory"
2023.09.19 16:07:18.911 CEST [21953] ExtProgram: warning: Stderr: ............
2023.09.19 16:07:18.911 CEST [21953] ExtProgram: warning: ""
2023.09.19 16:07:18.911 CEST [21953] ExtProgram: warning: ....................
2023.09.19 16:07:18.927 CEST [21933] default: critical: "Track 1. Encoder error:The '--type' program crashes with an error: execvp: No such file or directory"

OS is Arch Linux

**Comment by SokoloffA** [comment]
To solve the problem, you need to install the **sox** program.

In the next version, Flacon will always check the sox and report problems with it.

**Comment by SokoloffA** [comment]
Duplicate #209

**Comment by esatsana** [comment]
As I mentionned, Sox _is_ installed.

**Comment by SokoloffA** [comment]
Sorry I didn't notice the sox was installed. 

* How did you install the program, AppImage, from source, or standard packages?
* Check sox settings in "main menu"-> prefrences->programs.
* Send me your config (~/.config/flacon/flacon.conf)

**Comment by esatsana** [comment]
-  At first, I used a version built from Arch User repository, for DSD support. I have replaced this version with the regular package from Arch Linux.

- sox settings is just /bin/sox

- flacon.conf attached as flacon.conf.txt

[flacon.conf.txt](https://github.com/flacon/flacon/files/12677466/flacon.conf.txt)

**Comment by SokoloffA** [comment]
This is my bug, now I fixed it. I will release a new fixed version soon. 

If you want, you can test the [AppImage](https://github.com/flacon/flacon/suites/16420308457/artifacts/938253350) version just now.

**Comment by esatsana** [comment]
I built from git and ran a quick test, and it works very well.

**Comment by SokoloffA** [comment]
Fixed in 11.3.
