### ISSUE TITLE
Pattern stuck at %a - %A/%n - %t

### ISSUE THREAD

**Issue by rompolompo** [flacon/flacon#22]
No matter how I change it. The pattern always reverts to "%a - %A/%n - %t"

Ways to recreate:

1. Choose a different pattern
2. Hit "Tab"

Or:

1. Choose a different pattern
2. Hit "Start Conversion Process"

Flacon 1.2.0 / Ubuntu 15.04

**Comment by SokoloffA** [comment]
Sorry, I can't reproduce. Send me your config file (~/.config/flacon/flacon.conf), maybe it'll help me.

**Comment by rompolompo** [comment]
After upgrading to Ubuntu 15.10 the problem is no more.
