### ISSUE TITLE
split tracks without recoding

### ISSUE THREAD

**Issue by Damians0** [flacon/flacon#224]
Good morning, I tried to use flacon linux but I realized that when the program divides a large flac of an entire audio CD into separate flacs, the program carries out an encoding-recoding of the data stream, it doesn't just divide the tracks. On Windows I use Mediaval Cue Splitter which splits the flac file without carrying out any recoding. Is it possible to do it in flacon too?

**Comment by SokoloffA** [comment]
I don't use Mediaval Cue Splitter, but I'm sure it works similarly, extracting plain audio data and then encoding it again. 
Why it works this way and why it's not a problem - I've described in this [issue](https://github.com/flacon/flacon/issues/103#issuecomment-543838432), and in the [HOW-TO](https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions#i-have-flac-wavpack-and-ape-files-after-the-split-of-a-given-track-from-the-big-file-there-is-another-process-of-encoding-which-i-fear-re-encodes-the-audio-file-im-afraid-re-encoding-lowers-the-quality).
