### ISSUE TITLE
Order of TITLE and INDEX in generated cue sheet.

### ISSUE THREAD

**Issue by pasaran** [flacon/flacon#225]
I'm splitting big flac file into several tracks with option "Create per track CUE sheet".
This is an example of generated cue sheet:
```
PERFORMER "The Beatles"
TITLE "Abbey Road"

FILE "01 - Come Together.flac" WAVE
  TRACK 01 AUDIO
    INDEX 01 00:00:00
    TITLE "Come Together"

FILE "02 - Something.flac" WAVE
  TRACK 02 AUDIO
    INDEX 01 00:00:00
    TITLE "Something"

...
```

Then I open this cue sheet in Cog player and first track doesn't have a title. Second track has title of the first track etc.
If I manually change order of `INDEX` and `TITLE` everything is fine.

I tried to find a specification of cue format. There are many of them and not one of them describe the order of commands in cue file. But all examples always have `INDEX` as the last command in `TRACK` section.
And then I found this document: [INDEX command](https://www.gnu.org/software/ccd2cue/manual/html_node/INDEX-_0028CUE-Command_0029.html#INDEX-_0028CUE-Command_0029) — it's very detailed and it describes order of commands. According to it `INDEX` should be after `TITLE`. I've no idea is true or not tbh.

So maybe it's bug in Cog — some other players play this cue sheet just fine.
Or maybe it's a bug in Flacon and Cog just uses more strict spec of cue sheets than other players.
I don't really know.

**Comment by SokoloffA** [comment]
Thanks for digging deep into the problem!

CUE looks simple, but it's quite a confusing thing. There is also a non-trivial dependence between [FILE and INDEX tags](https://wiki.hydrogenaud.io/index.php?title=EAC_and_Cue_Sheets). 

I changed the tag order, now the tag order corresponds to the CUE file created by CUETools. I hope my changes don't break issue #172. I need some time to test non-trivial situations.

**Comment by SokoloffA** [comment]
Thanks for digging deep into the problem!

CUE looks simple, but it's quite a confusing thing. There is also a non-trivial dependence between [FILE and INDEX tags](https://wiki.hydrogenaud.io/index.php?title=EAC_and_Cue_Sheets). 

I changed the tag order, now the tag order corresponds to the CUE file created by CUETools. I hope my changes don't break issue #172. I need some time to test non-trivial situations.

**Comment by SokoloffA** [comment]
Publisher in Release 11.4.0
