### ISSUE TITLE
Application Ignores Disc Number when performing overlapping check

### ISSUE THREAD

**Issue by scottfurry** [flacon/flacon#226]
Platform: Gentoo Linux x86_64
App version: 11.3.0
Qt: 5.15.13

Processing a four disc set. No matter if DISCNUMBER is set in the cue sheet or that disc tag is set in a flac file, flacon will report an error with overlapping track numbers with a multi-disc situation.

- Have verified correct cue sheet.
- Disc number is picked up correctly by flacon.
- Track naming pattern is correct and has been used successfully prior.
- Changes to disc tags via flacon dialog "Edit all tags..." (i.e. manually setting disc number and disc total) does not correct overlap error - reparsing does not appear to be conducted.
- Error has not been encountered before this usage.
![flacon_error](https://github.com/flacon/flacon/assets/6686571/8a9d69a4-5bdb-48e2-8fb6-5ca199747283)

**Comment by SokoloffA** [comment]
I think I know what the problem is:
After conversion, the files from 4 disks will be saved in one directory. For disks 2-4 you didn't set "Start number", so the output directory will be a mess of files like:
```
   01 - Desdemona.flac             <- from disk 4
   01 - He's Got No Love.flac      <- from disk 3
   01 - Sweets for My Sweet.flac   <- from disk 1
   01 - This Empty Place.flac      <- from disk 2
   02 - Rosalie.flac               <- from disk 1
   ...
```
It's probably not what you want.

### How to fix it
There are 2 ways to solve the problem. 

In the first case you need to set correct **"Start number"**, as a result you will get files like:
```
   01 - Sweets for My Sweet.flac   <- from disk 1
   02 - Rosalie.flac               <- from disk 1
   ...
   34 - This Empty Place.flac      <- from disk 2
   ...
   66 - He's Got No Love.flac      <- from disk 3
   ...
   98 - Desdemona.flac             <- from disk 4
   ...
```

If you want to store tracks by disks, you need to tweak the **"Pattern"**, add `%d` as a directory part.  For example the `%a/{%y - }%A{/disk-%d}/%n - %t` template is quite smart.
* For multi-disk albums it will create a directory like `Artist/YEAR - ALBUM/disk-1/01 - TRACK`.
* For single-disk albums, it will create a directory like `Artist/YEAR - ALBUM/01 - TRACK`.

**Comment by scottfurry** [comment]
As stated in original post, ensuring the naming **"Pattern"** is correct has no effect. Flacon will still report an overlap error and not allow conversion. Correct disc number/total discs tags have been set. Overlap check appears to fail to consider disc number.

**Comment by SokoloffA** [comment]
The disk number must be in the directory, i.e. `%d.%n - %t` won't work, but `%d/%n - %t` will clear the errors. 

Perhaps I need to improve the checks and allow paths with disk number in the filename.

**Comment by SokoloffA** [comment]
What pattern are you using?

**Comment by scottfurry** [comment]
Pattern:
`%a/{%y - }%A/{%d-}%n - %t`

Overlap check appears to ignore this. I went so far as to remove the braces ('{}') to force the issue but still no success.

**Comment by scottfurry** [comment]
This problem seems new. I had never encountered this problem on previous usage (maybe pre-11.3.0?).

**Comment by SokoloffA** [comment]
Thanks for your issue!  I found two problems in my code:
1. Small one, the {%d/} template isn't handled correctly.
2. The overlap check does not take into account the disk number.

How can you convert a disk right now:
1. Convert disks one at a time.
2. Or use a pattern like `%a/{%y - }%A{/%d}/{%d-}%n - %t` and then copy the files into one directory

**Comment by scottfurry** [comment]
\o/ - crowd goes wild!
I've already _manually_ converted the discs, one at a time. But I'll be sure to check things when the fix is pushed through.

Thanks for sorting this out.

**Comment by SokoloffA** [comment]
I changed the check, now the program checks that tracks from different discs are not mixed.
If you are interested, you can check the new version using the [AppImage](https://github.com/flacon/flacon/actions/runs/8860211921/artifacts/1453356144).

**Comment by scottfurry** [comment]
Recommend an increment in release numbering(i.e. point release) so downstream distributions can pick up the change.
I'll try the appimage to test.

**Comment by SokoloffA** [comment]
> Recommend an increment in release numbering

This is not a release yet, this is a "nightly build".
A new release will be coming soon. The user messages have changed, and I'm giving the translators time to translate them. 
Maybe I'll have time to add something else.

**Comment by SokoloffA** [comment]
Publisher in Release 11.4.0
