### ISSUE TITLE
Fedora,flacon

### ISSUE THREAD

**Issue by region51** [flacon/flacon#23]
*Привет, если что, то я сделал пакеты для пользователей Fedora на copr'e [link](https://copr.fedoraproject.org/coprs/region51/flacon/)*.

**Comment by SokoloffA** [comment]
Здорово! Спасибо! 
Пожалуйста глянь, инструкция на https://flacon.github.io/download/ верная?

**Comment by region51** [comment]
*@SokoloffA да все верно, программу проверил лично http://imgur.com/a/6ywvs, работает на ура, так что благодарю за Flacon.*

**Comment by SokoloffA** [comment]
Ну тогда закрываю.

**Comment by region51** [comment]
@SokoloffA привет, так как copr я удалил, то если не сложно поменяй у себя ссылки на что-то такое

flacon packages can be installed from russianfedora-free repo or directly from [koji](http://koji.russianfedora.pro/koji/packageinfo?packageID=18)

Install repo:

`su -c 'dnf install --nogpgcheck http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm'`

Install flacon:

`dnf install flacon`

**Comment by SokoloffA** [comment]
Страницу я обновил.
Я немного поменял текст, сделал его в стиле остальных. И еще я
отформатировал команду, чтоб не ломала верстку страницы, проверь пожалуйста.

2016-01-31 14:23 GMT+03:00 Maxim Orlov <notifications@github.com>:

> @SokoloffA <https://github.com/SokoloffA> привет, так как copr я удалил,
> то если не сложно поменяй у себя ссылки на что-то такое
>
> flacon packages can be installed from russianfedora-free repo or directly
> from koji <http://koji.russianfedora.pro/koji/packageinfo?packageID=18>
>
> Install repo:
>
> su -c 'dnf install --nogpgcheck
> http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm
> http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm
> '
>
> Install flacon:
>
> dnf install flacon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flacon/flacon/issues/23#issuecomment-177470884>.
>



-- 
Best regards,
Alexander.

**Comment by region51** [comment]
@SokoloffA сойдет.
