### ISSUE TITLE
Missing CFBundleName and CFBundleDisplayName in Info.plist

### ISSUE THREAD

**Issue by cdwmhcc** [flacon/flacon#230]
## Overview
It has been observed that the Info.plist file currently lacks the `CFBundleName` and `CFBundleDisplayName` keys. These keys are crucial for defining the application's name as it appears in the Finder and other system contexts, such as the application switcher.

## Expected Behavior
The Info.plist file should include both CFBundleName and CFBundleDisplayName keys with appropriate values that define the application's name. This is important not only for user experience but also for adherence to Apple's guidelines for macOS applications.

## Suggested Fix
A potential fix would be to ensure that the Info.plist file of the Flacon Mac application includes:

`CFBundleName` set to "Flacon"
`CFBundleDisplayName` set to "Flacon"
These changes should align the application with macOS system standards and improve user recognition and interaction.

**Comment by SokoloffA** [comment]
Many thanks!
