### ISSUE TITLE
Can't As Extract Whole CD, File Branch Keep Listing DVD/CD Player

### ISSUE THREAD

**Issue by schmidtp72** [flacon/flacon#235]
When I try and Add Disc, select "Audio CD" as device it comes up with listings such as - CDA, FLAC, Full CD etc. If you select Full CD and open it shows the CD/DVD players, selecting and click open, it will give the option of the CD title .FLAC and .WAV. However clicking Open again and it just goes back to the CD/DVD listing again. Clicking on the CD/DVD again does nothing.

I'm running this program under Fedora 40 KDE and installed through the Discover store.

**Comment by SokoloffA** [comment]
If I understand you correctly, you have a physical CDAudio disk and you want to get the tracks as files. Unfortunately Flacon is not designed for this, the program processes already ripped disk images.

You need to look for an audio ripper program. I don't use them, so I can't recommend one for you. 
* https://sourceforge.net/directory/cd-ripping/linux/
* https://wiki.archlinux.org/title/Rip_Audio_CDs

If I've misunderstood you, don't hesitate to reopen the bug.
