### ISSUE TITLE
v1.2.0:: I can't parse "Splitting

### ISSUE THREAD

**Issue by Jheengut** [flacon/flacon#24]
Hi, following http://kde-apps.org/content/show.php?content=113388&forumpage=6, the comment apropos `I can't parse "Splitting` , the issue is still pertinent in version 1.2.0.

---

Leaving the Temporary directory in Settings=>Preferences=>General configuration, empty , the  `I can't parse "Splitting` is logged in the console. 
Inputting /tmp solves the issue. :+1:
## 

flacon --version
flacon 1.2.0
Copyright (c) 2013 Alexander Sokolov
   https://github.com/flacon/flacon
# 

using slackware 14.1 built from sbopkg

**Comment by SokoloffA** [comment]
I need some more information
1. Your $HOME $USER environment vars
2. Show me your flacon.conf ~/.config/flacon/flacon.conf
