### ISSUE TITLE
APE -> AAC : faac invalid options error

### ISSUE THREAD

**Issue by Excali78** [flacon/flacon#26]
When cue splitting APE files followed by AAC encoder, I get an error from the FAAC 1.28 encoder (see snapshot herejoined).
With other encoder, I don't meet any problem.
Any clue ?
Today I worked around by encoding losslessly in FLAC and then encoding in AAC with Soundconverter.

![erreur flacon](https://cloud.githubusercontent.com/assets/15855429/11168286/169b832e-8b89-11e5-9b73-8880c54a0e3c.png)

**Comment by SokoloffA** [comment]
I'm using faac 1.28 too. Flacon run faac like:

```
cat INPUT_FILE.wav | /usr/bin/faac -w -q 100 --artist 'Artist tag' --title 'Track title' --genre 'Rock' --album 'Albub name' --track 3/4 --year 2015 --comment 'ExactAudioCopy v0.95b4' -o 'output file name.m4a' -
```
try this in command line.

**Comment by Excali78** [comment]
I created an INPUT_FILE.wav from a FLAC one, it plays good.
The results of the command line are joined in the new screen snapshot and
gives the same
 error :(

When I tried the help option, it returns :
====================================================================
thierry@thierry-Aspire-X3810 ~/Musique/Samson Francois $ /usr/bin/faac
--help
Freeware Advanced Audio Coder
FAAC 1.28

Usage: /usr/bin/faac [options] infiles ...
Options:
  -q <quality>    Set quantizer quality.
  -b <bitrate>    Set average bitrate to x kbps. (ABR, lower quality mode)
  -c <freq>    Set the bandwidth in Hz. (default=automatic)
  -o X        Set output file to X (only for one input file)
  -r        Use RAW AAC output file.
  -P        Raw PCM input mode (default 44100Hz 16bit stereo).
  -R        Raw PCM input rate.
  -B        Raw PCM input sample size (8, 16 (default), 24 or 32bits).
  -C        Raw PCM input channels.
  -X        Raw PCM swap input bytes
  -I <C,LF>    Input channel config, default is 3,4 (Center third, LF
fourth)


*MP4 specific options:  MP4 support unavailable.*

Documentation:
  --license    Show the FAAC license.
  --help    Show this abbreviated help.
  --long-help    Show complete help.

  More tips can be found in the audiocoding.com Knowledge Base at
  <http://www.audiocoding.com/wiki/>
==========================================================

I wonder why MP4 support is unavailable ?

Thierry

2015-11-15 11:57 GMT+01:00 Alexander Sokolov <notifications@github.com>:

**Comment by Excali78** [comment]
the explanation is there :
http://askubuntu.com/questions/382703/why-doesnt-the-faac-package-support-mp4

I tried to force the packet version in Synaptic but the only available
version is 1.28-6 :(

Now we know the responsable !

Anyway, thank you for your answer.

Thierry

2015-11-15 18:26 GMT+01:00 Thierry Bur <bur.thierry@gmail.com>:

**Comment by SokoloffA** [comment]
Maybe this will help you - https://help.ubuntu.com/community/RestrictedFormats#Audio
What is the problem with 1.28-6
