### ISSUE TITLE
[RFC] Package for Arch Linux

### ISSUE THREAD

**Issue by BorislavSabev** [flacon/flacon#27]
Hello.

Could you provide a package for Arch Linux?
Sure one could install form sources but a package should be great.
Flacon is a super-handy piece of software and it should be available.

The standard is pretty straight-forward [you can see it here](https://wiki.archlinux.org/index.php/Arch_packaging_standards).

I can help with some info if required.

**Comment by SokoloffA** [comment]
The Flacon is present in the [AUR](https://aur.archlinux.org/packages/flacon/). There are problems with the PKGBUILD?

If PKGBUILD is fine you can contact with the ArchLinux core team. As I know, only they can add package from AUR to into main repository.
