### ISSUE TITLE
Possible FLAC file size issue

### ISSUE THREAD

**Issue by ginsterbusch** [flacon/flacon#29]
After having too much fun fiddling around with mp3splt / flacsplt, I decided to see if there was anything else less tedious around, so I proceeded with a fresh install of flacon 1.2 out of the PPA repository.

Sadly, even after editing around in my cue file, the program continued showing me the same error as seen in the screenshot for issue #12. So I went to `apt-get build-dep flacon`, `cmake` and `checkinstall` - put a hearty "same procedure as every year, Miss Sophie" in here somewhere - and got it all nicely built and working.

Or not.

When trying to use above mentioned cue file (again), flacon displayed the very same error. But by selecting another audio file (approx 3.5 GB), it seemingly worked. Which doesnt help me much. I just want my bloody last show split in two fancyful files. The others dont need no splitting (headache). Selecting my original file (approx 7 GB), I get the following happy error message:

![auswahl_046](https://cloud.githubusercontent.com/assets/1675226/12211080/12cf272c-b65f-11e5-9c73-2eeb89a4540b.png)

Even after switching to other CUE files (that work perfectly well in mp3splt and play out decently in audio players like Clementine, too), still with FLAC, it didnt want to work. Fiddling around a bit, after selecting the third bigger sized file (3+ GB), flacon suddenly crashed.

That's just with FLAC, but then, I don't use MP3 or Ogg Vorbis for recording, so I can't verify it for the rest.

OS: Linux Mint 17.2 = Ubuntu 14.04 LTS / x86_64
Tested releases: 1.2.0 (from PPA), current master (commit 09d0af4)
Installed flac version: 1.3.0
CUE file: https://gist.github.com/ginsterbusch/cd6209ae3b8544afe8b5

**Comment by SokoloffA** [comment]
I think is a bug in the shntool. For checking run following command with your 7GB file:
```shninfo djc_[2015-12-24][19:00:03]_01.flac```

**Comment by SokoloffA** [comment]
Now flacon don't use shntool, so I hope this problem is gone.

**Comment by ginsterbusch** [comment]
I haven't tested further. I just converted it to WAV / PCM format, and split it using Audacity. Case closed.
Oh, and flacon removed.

**Comment by SokoloffA** [comment]
>Oh, and flacon removed.

Very sad :)
