### ISSUE TITLE
".cue + .flac" file pairs not properly detected

### ISSUE THREAD

**Issue by GitHorst** [flacon/flacon#31]
When when loading a cue file (from cue + flac "pair") into flacon I get the error "Conversion not possible - Audio File not set". Flacon does not properly detect the corresponding flac file (the field is empty, I can manually load the flac file).
And on the other hand, when I drag the flac file into the program, it does not select the proper cue file but the first one in the folder (with many cues and flacs).
I have been using flacon for years now (great program -- thanks! :)) and did not (knowingly) change anything recently (for sure did not remove any packages). That is to say: Everything used to work ;)

What should I try? Thanks for your help!

**Comment by SokoloffA** [comment]
Please get me some more information. 

- name of CUE file
- name of Audio file
- show content of CUE

**Comment by GitHorst** [comment]
ok, as an example: the first cue file in the folder is: "3 Doors Down - (2000) The Better Life.cue", the corresponding flac file is: "3 Doors Down - (2000) The Better Life.flac". The 3rd cue file is "Bush - (1996) Razorblade Suitcase.cue" and the flac "Bush - (1996) Razorblade Suitcase.flac".

This is the content of the 3rd cue file:

`REM Cue file written by K3b 2.0.2
REM DATE "1996"
PERFORMER "Bush"
TITLE "Razorblade Suitcase"
FILE "Bush - (1996) Razorblade Suitcase.flac" FLAC
  TRACK 01 AUDIO
    PERFORMER "Bush"
    TITLE "Personal Holloway"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PERFORMER "Bush"
    TITLE "Greedy Fly"
    INDEX 01 03:24:25
  TRACK 03 AUDIO
    PERFORMER "Bush"
    TITLE "Swallowed"
    INDEX 01 07:53:70
  TRACK 04 AUDIO
    PERFORMER "Bush"
    TITLE "Insect Kin"
    INDEX 01 12:44:60
  TRACK 05 AUDIO
    PERFORMER "Bush"
    TITLE "Cold Contagious"
    INDEX 01 17:11:02
  TRACK 06 AUDIO
    PERFORMER "Bush"
    TITLE "A Tendency to Start Fires"
    INDEX 01 23:10:62
  TRACK 07 AUDIO
    PERFORMER "Bush"
    TITLE "Mouth"
    INDEX 01 27:15:47
  TRACK 08 AUDIO
    PERFORMER "Bush"
    TITLE "Straight No Chaser"
    INDEX 01 33:00:15
  TRACK 09 AUDIO
    PERFORMER "Bush"
    TITLE "History"
    INDEX 01 37:00:25
  TRACK 10 AUDIO
    PERFORMER "Bush"
    TITLE "Synapse"
    INDEX 01 41:37:17
  TRACK 11 AUDIO
    PERFORMER "Bush"
    TITLE "Communicator"
    INDEX 01 46:27:32
  TRACK 12 AUDIO
    PERFORMER "Bush"
    TITLE "Bonedriven"
    INDEX 01 50:50:30
  TRACK 13 AUDIO
    PERFORMER "Bush"
    TITLE "Distant Voices"
    INDEX 01 55:22:37`

**Comment by SokoloffA** [comment]
I was able to reproduce the bug. I'll fix it soon.

**Comment by GitHorst** [comment]
Great -- thanks! Looking forward & thanks for efforts with this nice program! =)

**Comment by GitHorst** [comment]
is there any information on when this will make it into the ppa? thanks again!

**Comment by Treeant34** [comment]
I am having the same issue with Flacon 2.1.0 on Lubuntu 14.04 LTS; however, I cannot split a Wavpack file and cue combo.

Name of cue file: Sting - 57TH & 9TH [at MasterDisk US].cue
Name of audio file: Sting - 57TH & 9TH [at MasterDisk US].wv

Content of cue:

REM GENRE Rock, Pop
REM DATE 11 Nov 2016
REM BAZAR_VinylRiP
REM LABEL A&M Records - B0025617-01
 PERFORMER "Sting"
 TITLE "57TH & 9TH [at MasterDisk US]"
 FILE "Sting - 57TH & 9TH [at MasterDisk US].wv" WAVE
 TRACK 01 AUDIO
   TITLE "I Can't Stop Thinking About You"
   PERFORMER "Sting"
   INDEX 01 00:00:00
 TRACK 02 AUDIO
   TITLE "50,000"
   PERFORMER "Sting"
   INDEX 01 03:31:00
 TRACK 03 AUDIO
   TITLE "Down, Down, Down"
   PERFORMER "Sting"
   INDEX 01 08:15:00
 TRACK 04 AUDIO
   TITLE "One Fine Day"
   PERFORMER "Sting"
   INDEX 01 12:03:00
 TRACK 05 AUDIO
   TITLE "Pretty Young Soldier"
   PERFORMER "Sting"
   INDEX 01 15:32:00
 TRACK 06 AUDIO
   TITLE "Petrol Head"
   PERFORMER "Sting"
   INDEX 01 18:38:00
 TRACK 07 AUDIO
   TITLE "Heading South On The Great North Road"
   PERFORMER "Sting"
   INDEX 01 22:10:00
 TRACK 08 AUDIO
   TITLE "If You Can't Love Me"
   PERFORMER "Sting"
   INDEX 01 25:28:00
 TRACK 09 AUDIO
   TITLE "Inshallah"
   PERFORMER "Sting"
   INDEX 01 30:04:00
 TRACK 10 AUDIO
   TITLE "The Empty Chair"
   PERFORMER "Sting"
   INDEX 01 34:59:00

Help?

**Comment by SokoloffA** [comment]
@Treeant34 
I think, your problem in the shntool. This is known issue (issue #6, issue #29) For checking run following command
```
shninfo "Sting - 57TH & 9TH [at MasterDisk US].wv"
```
You can download fixed version from my Dropbox https://dl.dropboxusercontent.com/u/19734259/shntool

**Comment by SokoloffA** [comment]
@GitHorst 
This on PPA from December 2016.

@Treeant34 
Now flacon don't use shntool, so I hope this problem is gone.
