### ISSUE TITLE
Home directory (~) not respected

### ISSUE THREAD

**Issue by sebaro** [flacon/flacon#32]
Version 2.0.1, Qt-5.6.1

When selecting the home directory as destination, the tilde is treated as a directory name and created in the CUE file source directory:

So instead of "/home/user/Artist/Album" it converts in "/cuedirectory/~/Artist/Album...".

**Comment by SokoloffA** [comment]
I fixed this bug https://github.com/flacon/flacon/commit/fabc1341325e8b25d4808781154f91caa87c0697
I plan make the release soon.
