### ISSUE TITLE
If the .cue file has only one track, Flacon doesn't know what to do

### ISSUE THREAD

**Issue by rmunn** [flacon/flacon#34]
I have a set of .tta and .cue files representing different albums from the same artist. Most of them are albums with multiple tracks, like you'd expect, but one of them is a "single" -- an album consisting of only one track. So its .cue file looks like this:

```
REM GENRE Rock
REM DATE 2009
REM DISCID 12345678
REM COMMENT "ExactAudioCopy v0.99pb4"
PERFORMER "Artist Name"
TITLE "Single Album"
FILE "Single Album.tta" WAVE
  TRACK 01 AUDIO
    TITLE "Title of the single"
    PERFORMER "Artist Name"
    INDEX 01 00:00:00
```

I loaded all these albums into Flacon to split them into FLAC files. Most of them split just fine, but the single album produced the error message "error: no split points given -- nothing to do". This is not what I would have expected would happen. I would have expected that the multi-track albums get split into multiple FLAC files, and the single-track album gets converted into a single FLAC file, and tagged and organized just like the others.

**Comment by SokoloffA** [comment]
Flacon use shntool for splitting. This is message from the shntool. But I agree, this is unexpected behavior, and we should something do with it. I think how I can fix or workarounded it.

**Comment by SokoloffA** [comment]
Now flacon don't use shntool, I wrote your own splitter. Now the program successfully converts this CUE file.
