### ISSUE TITLE
flacon doesn't recognize when external tools are removed

### ISSUE THREAD

**Issue by Coacher** [flacon/flacon#35]
Hello.

I have flacon 2.1.0. If an external tool, e.g. lame, was removed, flacon still remembers the old path and shows MP3 category in preferences. Clicking 'Rescan' button doesn't help.

flacon should reflect the fact that an external tool was removed and hide the relevant category in preferences and forget the previous path to the tool. Otherwise flacon gives user an impression that using the removed tool is still possible, which is not.

Please fix.

**Comment by SokoloffA** [comment]
Agree

**Comment by Coacher** [comment]
Hello again.

Do you have any ETA for this one?

**Comment by SokoloffA** [comment]
Done
