### ISSUE TITLE
Cuesheet misidentification when flacon loads folder

### ISSUE THREAD

**Issue by jbn-github** [flacon/flacon#38]
I'm on Debian GNU/Linux 64-bit i686 running flacon 2.1.0.

I've got a folder with two FLAC files and two cuesheets:

```
folder/
   a.flac
   a.cue
   b.flac
   b.cue
```

- If I load a.cue into flacon, flacon properly identifies which FLAC file to load and shows me the tracks.
- If I load b.cue into flacon, flacon properly identifies which FLAC file to load and shows me the tracks.
- If I load the folder into flacon, flacon shows me the following:

one of the albums (let's call this album 2):
- shows up with the cuesheet of album 1
- shows up with the audio file of album 2

the other album (let's call this album 1):
- shows up with the cuesheet of album 1
- shows up with the audio of album 1

One of the albums is shorter than the other, but already you can see the problem -- when loading recursively, flacon doesn't load the appropriate audio file from the cuesheet.

Workarounds (tested and untested):
- I can manually make album 2 use album 2's cuesheet and things load correctly
- I can also use the File->Add file... menu choice to load multiple cuesheets from the same folder and things load correctly
- I could probably also not store more than 1 cuesheet/audio pair per folder and avoid this problem too

But I thought you'd like to know about this issue on recursive loading.

Thanks for flacon, it's quite a considerable timesaver and very useful.

**Comment by SokoloffA** [comment]
I reproduced it. I'll fix it.
