### ISSUE TITLE
Building on Mint 18 fails

### ISSUE THREAD

**Issue by albertaparicio** [flacon/flacon#39]
I am using Linux Mint 18 Cinnamon x64.

I am trying to compile Flacon 2.1.1, but when I run "$ cmake .." as indicated in the wiki, The output is:

$ cmake ..
CMake Error at CMakeLists.txt:241 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/flacon/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/flacon/build/CMakeFiles/CMakeError.log".

Which is the required library to build Flacon?

Thank you very much

**Comment by SokoloffA** [comment]
Sorry for the late response.

As I know, LinuxMint is based on Ubuntu. So most likely you want the package [qttools5-dev-tools](http://packages.ubuntu.com/search?suite=yakkety&arch=any&mode=exactfilename&searchon=contents&keywords=Qt5LinguistToolsConfig.cmake). 

Also for build you need
  * cmake
  * libuchardet-dev


Runtime depends:
* shntool
* flac
* mac or monkeys-audio (you can download it from my [ppa]( https://launchpad.net/~flacon/+archive/ubuntu/ppa) or build from [sources](https://github.com/flacon/flacon.third-party/tree/master/mac)  )


Recommended packages:
* vorbis-tools
* wavpack
* lame
* vorbisgain
* mp3gain
* ttaenc
* faac
* opus-tools

**Comment by albertaparicio** [comment]
Thank you Alexander, I have now been able to build Flacon.

I have noticed, however, that the icons in Flacon are no longer the ones from my Cinnamon's theme. Do you think it has something to do with using Qt5 instead of Qt4?

The program works fine, I am just wondering.

Thank you for your time and for this great program.

Cheers!

**Comment by SokoloffA** [comment]
Thanks
Here can be 2 problems
1. Function [QIcon::themeName](http://doc.qt.io/qt-5/qicon.html#themeName) is not working properly and accordingly [Project::getIcon](https://github.com/flacon/flacon/blob/master/project.cpp#L43) does not work properly too. Maybe this is due to Qt5 or Gnome.
2. Your icon theme used other names for the icons. Check do you have the icons listed in the [MainWindow::initActions](https://github.com/flacon/flacon/blob/master/gui/mainwindow.cpp#L779) (icons placed in the /usr/share/icons/<theme_name> directories).


Cheers!

**Comment by albertaparicio** [comment]
Hi again Alexander,
I have checked it, and my icon theme (Numix Circle) is located in /usr/share/icons/ with all the other themes in my computer. I have looked at the themes' folders and the icons listed in MainWindow::initActions are in there.

I think the issue must be in QIcon::themeName and Project::getIcon. I'll try to debug Flacon and see if these functions are working.

Thank you

**Comment by albertaparicio** [comment]
Dear Alexander,

I have tried to build Flacon with the master version, and it builds fine, with correct icons.

Thank you

**Comment by SokoloffA** [comment]
I'm glad.
