### ISSUE TITLE
Add an option to change a sample rate (96 kHz -> 44.1 kHz)

### ISSUE THREAD

**Issue by qwertier** [flacon/flacon#40]
Hello, 
FLAC audio often has sample rates 96 kHZ and 48 kHz.
I always convert to OGG. I found that Flacon doesn't have an option to resample tracks.
What is very desirable to most of users is to have an option "resample to" in OGG encoding configuration
which allows to change a sample rate.
For example, when set "resample to" with "44.1", then when convert from FLAC to OGG,
we'll have always
FLAC 96 kHZ -> OGG 44.1 kHz

**Comment by qwertier** [comment]
Unfortunately, as the issue was reported more than 9 months ago, there was no any responds about...
I've stuck with the issue again, when I found that one of cue+flac recordings had 192KHz. 
I tried a hack, adding to the oggenc field

`/usr/bin/oggenc --resample 44100`

The program started to claim that it couldn't find the encoder.
Then I tried a workaround:

```
#!/bin/bash

if [ $# -eq 1 ]
then
    oggenc --resample 44100 "$1"
fi
if [ $# -eq 2 ]
then
    oggenc --resample 44100 "$1" "$2"
fi
...
```

Flacon started working normally, and I saw intermediate "*.wav" files it was creating, but at the end I didn't see any OGG files in the directories!
So, I can conclude that without "Add cmd params to encoder" field Flacon is useless as a 'lossless to lossy' converter!

**Comment by SokoloffA** [comment]
I'm sorry for the long silence. It's a shame for me. 

I got plans to add a resampling, but unfortunately the program doesn't have it now.
While you can use a script like this:

```
#!/bin/sh
oggenc --resample 44100 "$@"
```

**Comment by SokoloffA** [comment]
Done in the 5.0.0 release.

**Comment by qwertier** [comment]
> Done in the 5.0.0 release.
I've just looked through the newest 5.1.0 version (2019-02-24) and didn't found any resampling options!
Can you, please, point me out the place in the program options, 
where I can set resampling for the following: FLAC 96 kHZ => OGG 44.1 kHZ .
Thank you!

**Comment by ranperry** [comment]
"FLAC 96 kHZ => OGG 44.1 kHZ"

That is not resampling. This is converting from one format to another.
Resampling in Flacon is done via Settings > Preferences > General >
Resampling

**Comment by qwertier** [comment]
> Resampling in Flacon is done via Settings > Preferences > General > Resampling

I don't see such an option in the app's Preferences window!
I've installed the app using ppa repo.

**Comment by SokoloffA** [comment]
![foobar](https://user-images.githubusercontent.com/854935/53300649-5c1b8e80-385b-11e9-8bbe-2af5c8ba7d8c.png)

**Comment by qwertier** [comment]
Thanks, I've figured out what's going on. By default the screen size is smaller, and it does not contain extra features that you added in 5.0 release. (see screenshot) I had to maximize the window to see new options! 
I think, you should to mark this as a bug and add a code to the app to forcely resize the Preferences window...

![image](https://user-images.githubusercontent.com/21102319/53301582-30010d00-385d-11e9-8b72-322a98a9710f.png)

**Comment by SokoloffA** [comment]
I agree it's a bug. An example of how a feature becomes a bug. I save the size of the dialog and it led to an error.

**Comment by SokoloffA** [comment]
>I think, you should mark this as a bug and add a code to the app to resize forcely the Preferences window...

Fixed https://github.com/flacon/flacon/commit/fc47b6b8369c37bd1c8cd806d9fd7bd8a0dbfdfe
