### ISSUE TITLE
Add an option to recursively scan subdirectories of a folder

### ISSUE THREAD

**Issue by aeTIos** [flacon/flacon#43]
I have downloaded a torrent with about 60 albums, all in .cue format. It is a bit of a pain to add all the files by hand, as you can probably understand... I'd like to have Flacon be able to add a folder and all its subdirectories and files.

**Comment by bassstorm** [comment]
Just a hint: try drag'n'drop for that, works like a charm.

**Comment by SokoloffA** [comment]
Flacon has such feature, third button on toolbar.
http://i.imgur.com/LcQTGuy.png

**Comment by aeTIos** [comment]
Odd! I'd swear I tried it and it didn't work.... I'll try again. Closing for now.
