### ISSUE TITLE
Ubuntu 17.04 launchpad repository missing dependencies

### ISSUE THREAD

**Issue by subiol** [flacon/flacon#44]
I was using Flacon without problem on Ubuntu 16.10, and after installing Ubuntu 17.04 Flacon will not install because of missing dependencies. It says it is missing "mac" or "monkeys-audio" packages.

I have checked the flacon launchpad repository and, on top of the "flacon" package, it made available the "mac" package but only up until Ubuntu 16.10 yakkety. The package "mac" for Ubuntu 17.04 zesty is missing. There is zesty "flacon" package version but not zesty "mac".

**Comment by SokoloffA** [comment]
I'm sorry, I forgot about third-party packages. 

Today I published packages for mac and ttaenc.

**Comment by subiol** [comment]
Everything working now. Thanks.

**Comment by SokoloffA** [comment]
I'm not use Ubuntu, so I forgot about third-party packages again. I'm sorry!
I published packages for mac, mp3gain and ttaenc.
