### ISSUE TITLE
I Cannnot use "Get Data from CDDB" it's greyed out?

### ISSUE THREAD

**Issue by phd21** [flacon/flacon#45]
Hi Flacon people,

Excellent application, thank you for providing it.

If I add an album file, something.flac,  I cannot use "Get Data from CDDB" it's greyed out? Am I missing something?

Regards,
Phil
phd21

**Comment by SokoloffA** [comment]
Thanks!

The CUE file should contain DISKID tag. If this tag is missing, field "Disk ID" is empty and "Get Data from CDDB" is greyed out.

If your CUE contains this tag send me your CUE file.

**Comment by phd21** [comment]
Hi Flacon people, SokoloffA,

I did not have a "cue" file, only the actual "something.flac" audio file... So, if this requires the "cue" file then that is why this did not work. 

Thank you for replying quickly...

**Comment by SokoloffA** [comment]
Yes, my program takes an input 2 files, an audio file for the entire disk and the CUE file with information about lengths of every tracks.
