### ISSUE TITLE
Should Debian Stretch (v9) use http://download.opensuse.org/repositories/home:/Sokoloff/Debian_8.0

### ISSUE THREAD

**Issue by jbn-github** [flacon/flacon#46]
Debian GNU/Linux "Stretch" (version 9) was recently released. I noticed that http://download.opensuse.org/repositories/home:/Sokoloff/Debian_7.0 and http://download.opensuse.org/repositories/home:/Sokoloff/Debian_8.0 exist.

Should versions 8 and 9 of Debian GNU/Linux use http://download.opensuse.org/repositories/home:/Sokoloff/Debian_8.0?

I wasn't sure which Flacon repo directory to use because I didn't know if https://flacon.github.io/download/#stable-unstable-and-testing was up to date.

Thanks for working on Flacon.

**Comment by SokoloffA** [comment]
I don't know about compatible Debian 9 and 8. Now https://build.opensuse.org/project/show/home:Sokoloff contains the latest version. I made a new release and planned to prepare it for Debian 9 too. But OBS support only Debian 7 and 8. If I forget, kick me after some time.

**Comment by jbn-github** [comment]
Per your recommendation, I thought I'd write again to bring this issue to your attention.

I see that http://download.opensuse.org/repositories/home:/Sokoloff/Debian_8.0 exists and not http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0.

It looks like the URL to point Debian GNU/Linux Intel and AMD users to has changed to `http://widehat.opensuse.org/repositories/home:/Sokoloff/Debian_8.0/` but I don't know if that's intentional or permanent. I noticed that (after some effort) I was redirected to the widehat.opensuse.org URL so I thought I'd bring it up here since it seems related.

**Comment by SokoloffA** [comment]
I have successfully built packages for Debian 9.
![https://build.opensuse.org/project/show/home:Sokoloff](https://i.imgur.com/NaWiJmJ.png)
But I don't see the repository not on [download.opensuse.or](http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0/) or [http://widehat.opensuse.org](http://widehat.opensuse.org/repositories/home:/Sokoloff/Debian_9.0/) here. 
Perhaps need some time for publishing.

**Comment by jbn-github** [comment]
I've added the Debian 9.0 key per "wget http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0/Release.key -O- | apt-key add -". This took a long time to download but it eventually did work.

Then when I "apt-get upgrade" I see a lot of Ign lines and an error:

Ign:15 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ InRelease
Ign:16 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Release
Ign:17 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Packages
Ign:18 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en_US
Ign:19 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en
Ign:20 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:21 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:17 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Packages
Ign:18 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en_US
Ign:19 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en
Ign:20 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:21 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:17 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Packages
Ign:18 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en_US
Ign:19 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en
Ign:20 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:21 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:17 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Packages
Ign:18 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en_US
Ign:19 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en
Ign:20 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:21 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:17 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Packages
Ign:18 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en_US
Ign:19 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en
Ign:20 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:21 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Err:17 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Packages
  Connection failed
Ign:18 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en_US
Ign:19 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Translation-en
Ign:20 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Ign:21 http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Contents (deb)
Reading package lists... Done                               
W: The repository 'http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://provo-mirror.opensuse.org/repositories/home:/Sokoloff/Debian_9.0/Packages  Connection failed
E: Some index files failed to download. They have been ignored, or old ones used instead.

The entire content of my /etc/apt/sources.list.d/flacon.list is:
deb http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0 ./

Any tips?

**Comment by SokoloffA** [comment]
I installed Debian in a virtual machine, everything worked well. Perhaps it was a troubles on the OBS server.

**Comment by jbn-github** [comment]
This works now without problems. I think there was some trouble on the OBS server.

Thanks!
