### ISSUE TITLE
start button disabled

### ISSUE THREAD

**Issue by sylvainfaivre** [flacon/flacon#47]
Hi,
I'm trying to use flacon 3.0.0 on Ubuntu.
I add the cue file, the audio tracks are displayed, the tags are ok, but the "start conversion process" is grayed. What am I missing here ?
I tried with flac files and mp3 files, got the same result.

**Comment by SokoloffA** [comment]
I apologize for the long silence, I'm on vacation now. And have some problems with the Internet.

Mp3 is not supported as an input format.

About FLAC please geve me some more information:
1. Have you installed flac? Check *"Main menu - Settings - Preferences - Programs"*
2. Do you have displayed the name of the audio file? http://i.imgur.com/YOBkwG6.png
3. Do you see a yellow triangle with an error? http://i.imgur.com/Vei4G3y.png On mouse hover it will show the error message. What message is displayed.

**Comment by sylvainfaivre** [comment]
Hi, I'm sorry, I completely forgot about this. I found another way to split the FLAC file and deleted it, so I cannot report back on this. 
I'm closing this report. Sorry again.
