### ISSUE TITLE
Songs cut off

### ISSUE THREAD

**Issue by kuriot** [flacon/flacon#48]
Hello.

On latest version of Flacon from the [PPA](https://launchpad.net/~flacon/+archive/ubuntu/ppa) I've noticed a strange problem. If I add to list several albums and convert them then some songs on an album (it's very random and different each time) are cut off. If I do album by album (so that only on in list at time of conversion) then everything is fine. 

I've tried only with flac image+cue > flac tracks. It's on Ubuntu 16.04.

**Comment by SokoloffA** [comment]
Hello. I'll try to reproduce and fix it it.

**Comment by SokoloffA** [comment]
@kuriot 
Some songs, or last song on albums?

**Comment by kuriot** [comment]
Usually one song. Not always the last, may be any on album.

**Comment by SokoloffA** [comment]
I fixed it in the new version. If the problem persists, you are free to reopen the issue.
