### ISSUE TITLE
mac version conflict in ubuntu 14.04

### ISSUE THREAD

**Issue by Sadi58** [flacon/flacon#5]
When I installed this great tool yesterday on Ubuntu 14.04 64-bit, it also downloaded the required packages "cuetools", "libuchardet0" and "mac" in addition to the main "flacon" package.

I then received the following error messages:

dpkg: error processing archive /var/cache/apt/archives/mac_3.99-u4-b5-s7-1trusty_amd64.deb (--unpack):
trying to overwrite '/usr/bin/mac', which is also in package monkeys-audio 4.11.1~trusty1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
/var/cache/apt/archives/mac_3.99-u4-b5-s7-1trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

However, "flacon" seemed working well after the installation because "mac" was already installed.

I think this must be a bug related with the design of the deb package: 

If another "mac" exists already, this deb package should either skip it quietly or overwrite if the one that will be installed is a higher version.

BTW, my current "mac" version ("Monkey's Audio Console Front End" from the "monkeys-audio" package) is 4.11

Leaving the installation in that state, however, resulted in "Broken Package" error. When I uninstalled the "monkeys-audio" package, this problem was resolved, but this time "flacon" didn't work properly (when I pointed to the "cue" file, it refused to recognize the "ape" file in the same location and just got stuck there) until I manually replaced "mac" version 3.99 (from the "flacon" ppa) with "mac" version 4.11 (from the "monkeys-audio" package in ubuntu repositories).

I have a working configuration now, but I just wanted to let you know.

**Comment by abdulhaleembaram** [comment]
I like.
I rate ★★★★★

**Comment by SokoloffA** [comment]
What the name of the package which installed the previous mac?

**Comment by Sadi58** [comment]
The previous version of mac was installed by monkeys-audio 4.11.1~trusty1, which I no longer have.
I now have Flacon version 1.2.0 installed and working without any problems with mac version 3.99-u4-b5-s7 from official Ubuntu repositories.

**Comment by SokoloffA** [comment]
Hm, as  know Ubuntu hasn't package for mac.
http://packages.ubuntu.com/search?searchon=contents&keywords=mac&mode=exactfilename&suite=trusty&arch=any
29 сент. 2015 г. 20:51 пользователь "Sadi Yumuşak" <notifications@github.com>
написал:

**Comment by Sadi58** [comment]
Sorry, it must be from your ppa. I have no idea where monkeys-audio 4.11.1~trusty1 package came from 1.5 years ago, but it doesn't exist now. So the problem is over it seems.

**Comment by SokoloffA** [comment]
I added monkeys-audio as alternative.
