### ISSUE TITLE
Error 1009

### ISSUE THREAD

**Issue by gsidphgsnbgijf** [flacon/flacon#50]
Hi,
I'm trying to use flacon, but it doesn't work... The track results as queued (i'm not sure of the word, because i'm using falcon in italian). I run Falcon in terminal and the result is 

[Decoder] Error: 1009

I hope you can help me!

Regards

**Comment by SokoloffA** [comment]
Check whether you have the necessary programs (main menu Settings->Preferences->Programs). 
What is the format of input audio file? Send me your CUE file. Send me information about the audio file, run one of the following commands:
```
mediainfo YOUR_INPUT_AUDIO_FILE
```
or
```
shninfo YOUR_INPUT_AUDIO_FILE
```

P.S.
You can run flacon in English like:
```
LC_MESSAGES=C flacon
```

**Comment by gsidphgsnbgijf** [comment]
Hola, thank you for your reply!  I install all the programs. I found that Flacon runs perfectly with FLAC input, but not with APE. I cannot run mediainfo nor shninfo...

**Comment by SokoloffA** [comment]
Run the following command 
```
mac YOUR_APE_FILE -v
```

**Comment by gsidphgsnbgijf** [comment]
Nothing happens... Maybe I'm doing something wrong using terminal, I'm not so used to it. Oh, I forgot to tell you that my OS is Linux Mint 17, (64 bit).

**Comment by SokoloffA** [comment]
Step by step instructions.
For example I have a file **SuperAlbum.ape** in **/home/sokoloff/tmp/flacon** *(of course you will have other file names and directories.)*

1. Go to dir with .APE file and check
```
[sokoloff@sokoloff-home ~]$ cd /home/sokoloff/tmp/flacon
[sokoloff@sokoloff-home flacon]$ pwd
/home/sokoloff/tmp/flacon
[sokoloff@sokoloff-home flacon]$ ls
SuperAlbum.ape
[sokoloff@sokoloff-home flacon]$
```
2. Check is **mac** program installed and what version of it
```
[sokoloff@sokoloff-home flacon]$ mac -h
-- Monkey's Audio Console Front End (v 3.99-u4-b5-s7) (c) Matthew T. Ashland --
Proper Usage: [EXE] [Input File] [Output File] [Mode]

Modes: 
    Compress (fast): '-c1000'
    Compress (normal): '-c2000'
    Compress (high): '-c3000'
    Compress (extra high): '-c4000'
    Compress (insane): '-c5000'
    Decompress: '-d'
    Verify: '-v'
    Quick verify: '-q'
    Convert: '-nXXXX'

Examples:
    Compress: mac.exe "Metallica - One.wav" "Metallica - One.ape" -c2000
    Decompress: mac.exe "Metallica - One.ape" "Metallica - One.wav" -d
    Verify: mac.exe "Metallica - One.ape" -v
    Quick verify: mac.exe "Metallica - One.ape" -q
    (note: int filenames must be put inside of quotations)
[sokoloff@sokoloff-home flacon]$
```

3. Validate .APE file
```
[sokoloff@sokoloff-home flacon]$ mac SuperAlbum.ape -v
-- Monkey's Audio Console Front End (v 3.99-u4-b5-s7) (c) Matthew T. Ashland --
Verifying...
Progress: 100.0% (0.0 seconds remaining, 26.9 seconds total)          
Success...
[sokoloff@sokoloff-home flacon]$
```

4. Try to convert .APE to WAV
```
[sokoloff@sokoloff-home flacon]$ mac SuperAlbum.ape SuperAlbum.wav -d
-- Monkey's Audio Console Front End (v 3.99-u4-b5-s7) (c) Matthew T. Ashland --
Decompressing...
Progress: 100.0% (0.0 seconds remaining, 27.6 seconds total)          
Success...
[sokoloff@sokoloff-home flacon]$ ls
SuperAlbum.ape  SuperAlbum.wav
[sokoloff@sokoloff-home flacon]$ 
```

**Comment by gsidphgsnbgijf** [comment]
Step 1: ok
Step 2: ok, everything is like your example.
Step 3: 
mauro@mauro /mnt/6C099E40675DBA1B/musica/Mozart/Complete Keyboard Works - Bart van Oort, fortepiano/CD 12 $ mac Disc12.ape -v
--- Monkey's Audio Console Front End (v 3.99) (c) Matthew T. Ashland ---
Verifying...

Error: 1009

(Always the same error...)

Step 4:

mauro@mauro /mnt/6C099E40675DBA1B/musica/Mozart/Complete Keyboard Works - Bart van Oort, fortepiano/CD 12 $ mac Disc12.ape disc12.wav -d
--- Monkey's Audio Console Front End (v 3.99) (c) Matthew T. Ashland ---
Decompressing...

Error: 1009

(Always the same error...)

**Comment by SokoloffA** [comment]
Looks like your APE file is broken.

**Comment by gsidphgsnbgijf** [comment]
Something strange is happening....
Indeed, I can use Flacon with others APE files... So apparently, it is broken. But, I could convert it with xrecode (and wine). Moreover, Flacon works if i convert APE to Flac with Soundconverter. It seems that is something in these APEs (I've got many with the same problem) that Flacon can't manage...

**Comment by SokoloffA** [comment]
There are 2 variants: 
1. Your file is brocken, but xrecode forgives some errors. For example, players, plays broken files using interpolation of the data. In this case, the mac behaves correctly for a lossless format, the program guaranty absolute quality (bit to bit).

2. Your file is correct, maybe contains modern features. So this is a bug in the mac. Will be better to send bugreport to mac authors. On [mac website](http://www.etree.org/shnutils/shntool/support/formats/ape/unix/) I dont found links to the bugtracker. The source archive contains the AUTHORS file with the following contents.
```
Matthew T. Ashland <email @ monkeysaudio.com> : Original author of Monkey's Audio Codec

Frank Klemm : First port to linux (with makefile)

SuperMMX <SuperMMX AT GMail DOT com> : Package the source, include the frontend and shared lib,.
         porting to Big Endian platform and adding other non-win32 enhancement.

Jason Jordan <shnutils@freeshell.org> : maintainer of the shntool-enabled versions 3.99-u4-b5-sN
         (pipe decoding/encoding; miscellaneous enhancements; patch aggregation; bug fixes)
```
Try to send your file to them. 


P. S. Upload the file on dropbox or something. I'll look, but I'm not familiar with code of mac, so can't guarantee anything. It would be better if you send a bug report to authors of mac.

**Comment by gsidphgsnbgijf** [comment]
Oh, there's a misunderstanding. I do not use Mac, but Linux Mint 17 (64 bit).

**Comment by SokoloffA** [comment]
Yes there's a misunderstanding :) I'm talking not about the Aplle's computers, but about the program with name *Monkey’s Audio converter/compressor*, abbreviated as mac. Agree confusing name.
 * windows version - http://www.monkeysaudio.com/index.html 
 * unix version - http://etree.org/shnutils/shntool/support/formats/ape/unix Just now site is unavailable, but I hope is temporary problems.
