### ISSUE TITLE
Converting CUE to FLAC stops on last file

### ISSUE THREAD

**Issue by TehTotalPwnage** [flacon/flacon#52]
When I input a CUE file and ask the program to output FLAC files, the program will successfully convert all tracks prior to the last one in the CUE file. Once it reaches the last file, the program just halts at "Extracting 99%".

If I look inside of the output folder, all of the previous files are in FLAC format and play through properly. The last file that's stuck on "Extracting 99%" is in WAV format and playable all the way through. It seems to be a bug with parsing the last file where the extraction seems to "hang" for no clear reason even though it's clearly extracted properly.

I was able to duplicate this bug with a second pair of CUE and TTA files. I haven't tested this on any other output formats.

![flacon_783](https://user-images.githubusercontent.com/4282201/30518548-f05726f0-9b35-11e7-9110-383256e213fb.png)

**Comment by SokoloffA** [comment]
Run the program from terminal, you might see messages that clarify the problem.

I rewrote converter in the development branch. It should works better, I hope:).
It would be nice if you try the new version and report if you still have the error. You can run flacon without installing.

If you have skills, you can build the project from sources. This [page](https://github.com/flacon/flacon/wiki/How-to-build) may be useful to you.
```
git clone https://github.com/flacon/flacon.git 
cd flacon 
mkdir build 
cd build 
cmake ..
make 
```

If you haven't such skill, say me what distro you are use and I try to build program for you.

**Comment by TehTotalPwnage** [comment]
Hi! Thanks for getting back to this issue in such a timely manner.

I managed to build flacon from source and test again, but it appears that the same issue comes up:
![flacon_784](https://user-images.githubusercontent.com/4282201/30519363-6c5911c4-9b49-11e7-837c-87135e11a590.png)
It's quite odd, nothing is showing up in the Terminal to indicate that there was an error with any of the processes. The processing just halts.

**Comment by SokoloffA** [comment]
Maybe your file is broken. Try to run in terminal:
```
ttaenc -d path_to file/SCFS-0301.tta
```
Else, is your have enough space on disk?

In any case, it is a defect in my program, it should show a sensible error message. Send me the audio and CUE files, if you don't want to publicly, you can mail to sokoloff.a@gmail.com

**Comment by SokoloffA** [comment]
I was able to reproduce the bug. 
As workaround decode procedures TTA to WAV (```ttaenc -d path_to_file/SCFS-0301.tta```), and split WAV file in the flacon.

**Comment by SokoloffA** [comment]
I fixed it in the development branch. Please, check is it works for you.

**Comment by TehTotalPwnage** [comment]
Just pulled and built the newest commit. The issue seems to be fixed now.
