### ISSUE TITLE
Auto extract to same directory as cue

### ISSUE THREAD

**Issue by roy1776** [flacon/flacon#53]
First, thank you for this program.  Is it possible to set flacon up so files are automatically extracted to the same directory as the cue-flac files?  I've forgotten to choose the directory several times and ended up having to moving the files back to the original directory.  Again, thank you for this program.  Has saved me a lot of command line typing.

**Comment by SokoloffA** [comment]
If you clear the field "Result Files: Directory", result files will be created in the directory with source **audio file**. This isn't quite what you're asking, but in most cases, CUE and audio files placed in same directory.

**Comment by roy1776** [comment]
Thank You!  That is exactly what I wanted.
