### ISSUE TITLE
Segmentation fault under Slackware -current: all flacon releases after 2.1.1

### ISSUE THREAD

**Issue by andrew-strong** [flacon/flacon#56]
Under the 64bit development version of Slackware flacon all versions compile ok but after version 2.1.1 all show a segmentation fault from the command line and do not load at all from the gui.

I am no gdb expert but perhaps the following is useful:

andrew@illium~$ gdb flacon
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from flacon...done.
(gdb) r
Starting program: /usr/bin/flacon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000049cc17 in AudioFormat::registerFormat(AudioFormat const&) ()
(gdb) bt
#0  0x000000000049cc17 in AudioFormat::registerFormat(AudioFormat const&) ()
#1  0x00000000004bca36 in __do_global_ctors_aux ()
#2  0x0000000000711fb0 in  ()
#3  0x0000000000000000 in  ()
(gdb) bt full
#0  0x000000000049cc17 in AudioFormat::registerFormat(AudioFormat const&) ()
#1  0x00000000004bca36 in __do_global_ctors_aux ()
#2  0x0000000000711fb0 in  ()
#3  0x0000000000000000 in  ()
(gdb) 

Please let me know if I can provide more information or testing...

Andrew

**Comment by SokoloffA** [comment]
Was fix a [similar bug](https://github.com/flacon/flacon/commit/8bd603f3c6cd0f1329587a9f9dc23ffaa978cfb3). Try to building the version from the [master branch](https://github.com/flacon/flacon/tree/master).

I plan to release a new version the other day.

**Comment by andrew-strong** [comment]
Indeed this solves the issue. My apologies for not digging a little deeper in the Issues pages and for also not testing the git version.
And thanks for flacon :)
