### ISSUE TITLE
Unable to work with already split albums.

### ISSUE THREAD

**Issue by AdamantGarth** [flacon/flacon#59]
Sometimes there's a need to convert albums that was previously split into individual tracks. Though Flacon does a great job when converts single-file albums, it's unable to handle already split ones, because metadata is not being read. Can you add in-file metadata support, not just CUE-metadata? This would be a great convenience feature.

**Comment by SokoloffA** [comment]
I've been asked several times about this. Unfortunately, it is not easy to do:
1. I don't know how to do it conveniently in the GUI.
2. This will require rewriting a lot of code.

I'll think about it. But in any case, it will not be soon.

**Comment by AdamantGarth** [comment]
If I understood your point about GUI correctly, I think that after the file metadata has been read, Flacon should group all input files by albums, thus already split albums would look the same as single-file ones.

As for code rewriting, yeah, that sucks. Guess I'll have to wait then :)

**Comment by SokoloffA** [comment]
In the release 7.0.0 was redesigned the logic of loading CUE files containing multiple files, for example, 2 sides of an LP. Now they are displayed as a single list, have a single track numbering, and allow you to change album tags in a single operation.
So now you can work with already split albums. Oddly enough, this did not require any changes to the UI.

At the same time, Flacon is not just an audio converter, but a splitter, and you still need a CUE file. But if you used the "Create per track CUE sheet" option, then working with a splitted album is no different from the first one.
