### ISSUE TITLE
Splitting 24 bit 192 khz flac files

### ISSUE THREAD

**Issue by Singtoh** [flacon/flacon#6]
Hello,

I have been looking for a program to split 24 bit 192 khz flac files for a long time. At the moment I have to convert these files to .wav then split them manually with Wavebreaker then convert them back to .flac then do my other routine processing. Flacon seems to handle 24 bit 96 khz files Ok(sometimes fails) but will not split 24 bit 192khz flac files. Is this a bug?? If not, as a feature request could you please make Flacon support spliting 24bit 192khz flacs, or tell me how to fix it so it will work?? Flacon is really handy and easy to use if it would just support 24bit 192khz flacs it would be perfect. With Hi-Rez music becoming the "norm" I think this would be a good feature to have. Thank you very much and I hope to see Flacon support 24bit 192khz flacs soon.

Cheers,

Singtoh

**Comment by xtemp09** [comment]
Flacon fails when splitting a FLAC file created with the latest ffmpeg.

24-bit/192 kHz, ffmpeg version 2.7.1.

The CUE file has been verified with bash-cue-validator-test.sh.

**Comment by SokoloffA** [comment]
@xtemp09 
What error you are recieving? What version of shntools you are using? Perhaps this is [bug in the shntool](https://github.com/flacon/flacon/issues/6#issuecomment-46366126). Try to split with [fixed one](https://www.dropbox.com/s/kewef605zl3f03i/shntool), you can select different binary on the preferences page.

**Comment by xtemp09** [comment]
The symptoms are as venerable Singtoh described in the second post. I'll try the new shntool to check.

Is it a tool that installs separately from Falcon or it is distributed with it? Perhaps, the fixed version should be statically linked to the program if the developer/maintainer falls off the wagon.

**Comment by xtemp09** [comment]
The fixed shntool works fine.

**Comment by SokoloffA** [comment]
@xtemp09 
This is bug in the shntool, so I close issue.

At 18.06.14 I sent an email with a patch to shn developers by email. Unfortunately I have not received any response. Today I sent the letter again.
Let's you kick the developers, maybe then they will wake up.

**Comment by xtemp09** [comment]
The program can't work without this tool. Might I ask why do you not distribute the fixed shntool with Flacon? The project was abandoned, and I can't say for sure that the developers will be back.

**Comment by SokoloffA** [comment]
There are several reasons:
1. I'm not a C programmer, I am a programmer in C++, are two different languages.
2. I have no time to support another one program.

**Comment by awsms** [comment]
> @Singtoh Good news! I found and [fixed the bug](https://github.com/flacon/shntool/commit/4c6fc2e58c830080f6f9112935325ad281b784ff) in the shntool. I sent fix to developers of the shntool. If you want, I can send fixed version of the shntool to you.

do you still have that patch? links are dead
