### ISSUE TITLE
Feature Request - opening cue file defaults to source directory

### ISSUE THREAD

**Issue by virtualviolet** [flacon/flacon#62]
Please could you make the default behaviour of flacon, so that when a user opens a cue file, the directory field in the UI automatically populates with the source directory the cue file was in or at least provide some options in prefs to choose between last directory or cue file source directory...

**Comment by SokoloffA** [comment]
Do I get you right? You run the program from the console like "flacon Album.cue", and you want the resulting files to be created in the same directory. Just clear the *Directory* field in the *"Result files"* group. Now the program will save the results in the directory with the original CUE-file. 

I agree it's not an obvious feature, and I plan to add it to the GUI.

**Comment by virtualviolet** [comment]
Excellent! Yes you do get me 😉 


On 15 Apr 2018, at 15:52, Alexander Sokolov <notifications@github.com> wrote:

Do I get you right? You run the program from the console like "flacon Album.cue", and you want the resulting files to be created in the same directory. Just clear the Directory field in the "Result files" group. Now the program will save the results in the directory with the original CUE-file.

I agree it's not an obvious feature, and I plan to add it to the GUI.

**Comment by SokoloffA** [comment]
Can I close issue?

**Comment by virtualviolet** [comment]
yeah
