### ISSUE TITLE
mp3gain not able to satisfy

### ISSUE THREAD

**Issue by thwaller** [flacon/flacon#64]
In Ubuntu at least, and I believe all Debian, mp3gain is obsoleted. Are there plans to update support for recent changes, or does this require that the obsolete package be installed?

**Comment by SokoloffA** [comment]
Yes, it is a problem. In the future I plan to write my own handler for ReplayGain, but it's required a time. As a workaround, I can upload package for mp3gain to my launchpad PPA.

Is it suit for you?

**Comment by thwaller** [comment]
I can install the package myself no problem. I was unsure if this was known, but your reply tells me you know, so you have answered my question.

I just download and install package from here: https://pkgs.org/download/mp3gain ... if it helps others.

**Comment by SokoloffA** [comment]
I don't use Ubuntu and I was not aware. So thank you for the issue.

**Comment by thwaller** [comment]
Oh, I misunderstood your reply. I am glad you are now aware :)

**Comment by SokoloffA** [comment]
The package is available from my PPA

**Comment by thwaller** [comment]
Which distribution are you pulling from? I am using Ubuntu 18.04, with some deb-multimedia packages and some Debian Sid packages to make things fit. If I see things correctly, Ubuntu dropped mp3gain after 14.04.
https://packages.ubuntu.com/trusty/mp3gain

**Comment by SokoloffA** [comment]
For Xenial, Bionic and Artful ([ppa](https://launchpad.net/~flacon/+archive/ubuntu/ppa/+packages?field.name_filter=mp3gain&field.status_filter=published&field.series_filter=))
I looked at the packages.ubuntu.com and did not found mp3gain package in the main repositories:
* [xenial](https://packages.ubuntu.com/search?suite=xenial&arch=any&searchon=names&keywords=mp3gain)
* [artful](https://packages.ubuntu.com/search?suite=artful&arch=any&searchon=names&keywords=mp3gain)
* [bionic](https://packages.ubuntu.com/search?suite=bionic&arch=any&searchon=names&keywords=mp3gain)

**Comment by thwaller** [comment]
Oh, I am sorry. I misread your statement.
> The package is available from my PPA
Yes, I see it available from your Flacon PPA... not your distro's PPA. Sorry, that was my misunderstanding. But I can confirm it is in the Flacon PPA and also confirm is is not available with xenail, artful or bionic.
