### ISSUE TITLE
feature request: handling of compilations with album performer

### ISSUE THREAD

**Issue by krallenbande** [flacon/flacon#65]
I tried to extract the songs from a compilation album where the album has the performer "Various Artists" and every track its own performer set in the cue file, but the album performer was not used and every song went into its own directory.

Can you please include the handling of the album performer to allow a naming pattern like this:

        album_performer - album_title/track_performer - track_title (year)

Thank you,
Sabine

**Comment by glglwty** [comment]
Specifically, the PERFORMER tag in the global scope of a CUE file needs to be mapped to "ALBUMARTIST" in vorbis comments. It's not one of the [minimal recommended tags](https://xiph.org/vorbis/doc/v-comment.html) but is supported by all players I've ever used.

**Comment by SokoloffA** [comment]
I'm confused about tags. I looked in clementine and foobar.
![clementine](https://user-images.githubusercontent.com/854935/45252289-99976880-b35c-11e8-8fa6-085f2b06b32a.png)

![foobar](https://user-images.githubusercontent.com/854935/45252318-10346600-b35d-11e8-8ab8-3b9735f823cb.png)

```
$ ffprobe track.ogg 
ffprobe version 3.2.4 Copyright (c) 2007-2017 the FFmpeg developers
...
Input #0, ogg, from 'track.ogg':
  Duration: 00:04:07.63, start: 0.000000, bitrate: 229 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 224 kb/s
    Metadata:
      ALBUM           : Album
      album_artist    : Album_artist
      ARTIST          : Artist
      COMPILATION     : 0
      DATE            : -1
      PERFORMER       : Performer
      TITLE           : Title
      TOTALTRACKS     : 11
      track           : 1
      TRACKTOTAL      : 11

```
There are three tag **"Artist"**, **"Performer"** and **"Album artist"**.
**Artist** - is band or singer of the track. 

But what's the difference between **Performer** and **Album artist**?

**Comment by krallenbande** [comment]
Sorry for the long delay. I was on holidays and I'm completely offline in that case…

To the question:

	Artist		You got that already. The band's or the singer's name
	Album Artist	For example you've got a compilation with greatest hits sung by George Michael. If it contains the duet with Aretha Franklin "I knew you were waiting" the Artist would be "George Michael & Aretha Franklin" or as may some write "George Michael; Aretha Franklin", but the Album Artist would just be "George Michael".
			This is also the field to hold "Various Artists" if it is a compilation by such. Very important for sorting purposes imho.

	Performer	I'm not quite sure about this, but I think an example would be a song by George Michael not being played by the normal musicians he worked with but by e. g. "The London Symphonic Orchestra". This may be important for searches.

Hope this helps.

Sabine

**Comment by SokoloffA** [comment]
Done in the 5.0.0 release.
