### ISSUE TITLE
feature request: tags for the album of a set

### ISSUE THREAD

**Issue by krallenbande** [flacon/flacon#66]
When extracting the songs of a 2 disc set I noticed, that the tags for the album the songs came from and the total number of disc in the set were not set int the extracted songs. Can you please add support for them?

For vorbis comments this would be:

        DISCNUMBER=disc_number_the_track_came_from
        TOTALDISCS=number_of_discs_in_the_set

and for id3v:

        TPOS=disc_number_the_track_came_from/number_of_discs_in_the_set

Thank you,
Sabine

**Comment by SokoloffA** [comment]
Done in the 5.0.0 release.

**Comment by eignatenkov** [comment]
@SokoloffA , is it possible to put the disc number into the filename? I can't find the parameter for that

**Comment by SokoloffA** [comment]
This is not possible in the current stable version.  I'm stupid, I forgot that.
Now I have added this feature to the development version https://github.com/flacon/flacon/commit/95b965ad17799c68cd5715b55537ff3e0029a466

If you have skills, you can build the project from sources. This [page](https://github.com/flacon/flacon/wiki/How-to-build) may be useful to you.
```
git clone https://github.com/flacon/flacon.git 
cd flacon 
mkdir build 
cd build 
cmake ..
make 
```

If you haven't such skill, say me what distro you are use and I try to build program for you.
