### ISSUE TITLE
Logo For flacon

### ISSUE THREAD

**Issue by hawk28** [flacon/flacon#69]
Hi , I am a graphic designer, I want to help you in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. What do you think?

**Comment by SokoloffA** [comment]
I apologize for the long silence, I was on vacation.  

That would be perfect. I'm not an artist, I just downloaded the icons from the icon8 site. The program has versions for Linux and macOS. Linux doesn't have a single UI style (different DE and distributions has own). And macOS, has a unified UI and icons. Therefore, I have a wish that the new icons would first look good in macOS.

If you want, you are free to contact me by mail sokoloff.a@gmail.com
