### ISSUE TITLE
Ignoring disc remarks

### ISSUE THREAD

**Issue by niczero** [flacon/flacon#75]
I am using Flacon 4.1.0 from the opensuse Debian 9.0 repo.

I cannot find a way to get flacon to pick up REM fields at the disc level:
```cue
PERFORMER "Michael Bond"
TITLE "Paddington's Finest Hour"
FILE "Paddingtons Finest Hour d1.flac" WAVE
REM DISCID 605aePKvRiNqUAth4gpwWnTIkfI-
REM DATE "2018"
REM GENRE "Audiobook"
REM NARRATOR "Stephen Fry"
  TRACK 01 AUDIO
    TITLE "01"
    INDEX 01 00:00:00
```
The flacon UI has entirely blank fields for Genre, Year, and Disc ID.
If instead I put those same fields at a track scope:
```cue
PERFORMER "Michael Bond"
TITLE "Paddington's Finest Hour"
FILE "Paddingtons Finest Hour d1.flac" WAVE
  TRACK 01 AUDIO
    TITLE "01"
    INDEX 01 00:00:00
    REM DISCID 605aePKvRiNqUAth4gpwWnTIkfI-
    REM DATE "2018"
    REM GENRE "Audiobook"
    REM NARRATOR "Stephen Fry"
```
Then the three values for Genre, Year, and Disc ID are populated perfectly (but only for that track of course).
This is a great puzzle, because the test files I'm looking at ([https://github.com/flacon/flacon/blob/master/tests/testflacon.cpp#L603](testflacon.cpp) are testing fields at the disc level, not the track level.
Any ideas why I can't get the disc attributes to be used?
(While we're here, is there any likelihood of getting a 'narrator' field or equivalent?  If you give the nod I'll register a feature request.)

**Comment by SokoloffA** [comment]
Yes, this is a bug in the program - all disk tags after FILE are ignored.
In the [new version of the program](https://github.com/flacon/flacon/releases) CUE parser rewritten from scratch and does not contain this bug. 

As a workaround move the FILE tag after all REM-tags
```
PERFORMER "Michael Bond"
TITLE "Paddington's Finest Hour"
REM DISCID 605aePKvRiNqUAth4gpwWnTIkfI-
REM DATE "2018"
REM GENRE "Audiobook"
REM NARRATOR "Stephen Fry"
FILE "Paddingtons Finest Hour d1.flac" WAVE
  TRACK 01 AUDIO
    TITLE "01"
    INDEX 01 00:00:00
```

About the NARRATOR. This tag is not described in the CUE standard. What audio formats support this tag? For example, Vorbis Tags does not support it.

In any case will be better to create a separate Issue.

**Comment by niczero** [comment]
Confirmed.  That workaround does the job perfectly.  I'll adapt my code so that no disc attributes come after any FILE line.
thanks
