### ISSUE TITLE
Error on convert

### ISSUE THREAD

**Issue by ghost** [flacon/flacon#78]
Hi, I have this message when I try to convert .cue and .ape to .flac 

`[Decoder]&nbsp;Can't&nbsp;read&nbsp;130888800&nbsp;bytes`

What does it mean ? how to fix it ?

Thanks.

**Comment by SokoloffA** [comment]
Maybe the audio file is corrupted. Check it out:
```
$ mac YOUR_APE_FILE.ape out.wav -d
```

**Comment by SokoloffA** [comment]
No answer, so I close the issue.
