### ISSUE TITLE
feature request: option to add cover as metadata to individual FLAC files

### ISSUE THREAD

**Issue by filippobistaffa** [flacon/flacon#80]
As title says, it could be useful to store the cover to the individual FLAC files as metadata.
I couldn't find any option to enable this, so I think it would be nice to add it.

**Comment by SokoloffA** [comment]
I agree, but some later

**Comment by myaeon-ru** [comment]
Не буду выпендриваться и писать на англиском ) Прога супергуд! пожалуйста добавь возможностей выбирыть при конвертации битрейты. Я бы прям с удовольствие потер все остальное если бы не одно но:
вот скажем я беру wv и у человека битрейт 192КГц, ну не могу я у себя на рессивере, ровно как и большинство послушать на +- современных ЦАПах выше 96КГц. Хочу сконвертнуть но ни в wav ни во flac нет такой возможности. Вообще, как я понимаю параметры у енкодеров достаточно обширные. В чем причина их такой скудности в настройках программы? Ок, если нет времени может хотя бы пальцем ткнешь где в коде можно самостоятельно "наговнокодить" ))))))))) относительно flac

**Comment by SokoloffA** [comment]
>пожалуйста добавь возможностей выбирыть при конвертации битрейты.

Все украдено до вас.
Такая фишка была добавлена в версии 5.0.0. В настройках выставляешь максимальные битрейт и дискретизацию
![image](https://user-images.githubusercontent.com/854935/53575555-da8d6e80-3b82-11e9-86d6-be334b10def4.png)
Если частота и битрейт в оригинале равны или меньше,  остаются как есть. Если больше ограничиваются.

>как я понимаю параметры у енкодеров достаточно обширные. В чем причина их такой скудности в настройках программы?

Идея программы быть простой и не канифолить пользователю мозги. Большинство хочет быстро и просто получить стандартные файлы для прослушивания. Запустил, выбрал CUE, нажал старт - получил готовый результат в директории с музыкой. 

Основной функционал я покрываю, уровень компрессии выбрать можно, теги проставляются, replaygain считается, битрейт и дискретизация меняются. А остальные опции довольно мутные. Вот кому нужно *"Allow  encoder  to  generate  non-Subset  files"*, *"Align encoding of multiple CD format files on sector boundaries."* или *"When encoding to flac, ignore the file size headers in WAV and AIFF files"*? Вот лично тебе оно надо? Вообще, что это означает?

Если уж совсем хочется странного, то можно написать скрипт обертку, типа "flac.sh", выбрать его в настройках и переопределять в скрипте что угодно.

**Comment by myaeon-ru** [comment]
Доволен как слон! Спасибо, что ткнули носом
sudo apt purge sweep soundcon* asunder* mp3splt* qjack* && sudo apt autoremove

Даешь flacon  в основной репозиторий!
Прога суперпродумана.

**Comment by frantic1048** [comment]
It's nice to see this feature in flacon. Flacon's cover selection UI is intuitive to use.

For now, I'm using my little script to embed cover art on flacon output FLAC files:

https://github.com/frantic1048/Vanilla/blob/master/bin/bin/fffcoverart.elv

It searches for cover art image under the same folder of each FLAC file, and embeds cover art into FLAC file if there's no cover art found in FLAC file AND external cover art is found.

**Comment by greekstreet** [comment]
Flacon is a great tool for audio converting. This feature will make it even better. I also need this feature. Hope this feature can be added soon.

**Comment by SokoloffA** [comment]
Unfortunately, I don't have much time right now. But the feature looks easy to implement, and I will add this in future releases.

**Comment by landgenoot** [comment]
I tried to get the solution from @frantic1048 to work, but had some issues with regular expressions and elvish.

The following simple command did the trick for me inside a folder.
```
metaflac --import-picture-from=cover.jpg *
```

In order to run it recursively on all subfolders:
```bash
for d in */; do
    cd "$d"
    metaflac --import-picture-from=cover.jpg *
    cd ..
done
```

**Comment by SokoloffA** [comment]
I don't understand why you need recurse. Here are the solutions on bash:
If you don't need recursion, just **nested directories**:
```bash
metaflac --import-picture-from=cover.jpg */*.flac
```
If you need a **full recursion**:
```bash
find -name '*.flac' -exec metaflac --import-picture-from=cover.jpg "{}" \;
```

**Comment by frantic1048** [comment]
> I tried to get the solution from @frantic1048 to work, but had some issues with regular expressions and elvish.

@landgenoot Could you specify what issue you've met ?

**Comment by landgenoot** [comment]
@SokoloffA You are right, my solution is not resursive, but nested.
The problem with your solutions is that is works with one `cover.jpg`, which is not the case if you want to convert one entire music library. Every folder has its own cover.

@frantic1048 `fffcoverart.elv (fd -e flac)` does not work with folder names that contain spaces (for me). 
Results in errors like:
```
?(fail 'Ignored, Non FLAC file:/home/daan/Music/The')
?(fail 'Ignored, Non FLAC file:/home/daan/Music/Complete')
?(fail 'Ignored, Non FLAC file:/home/daan/Music/Bach')
?(fail 'Ignored, Non FLAC file:/home/daan/Music/Collection')
```
Escaping the spaces with backslashes results in RE errors.

**Comment by SokoloffA** [comment]
> does not work with folder names that contain spaces (for me).

This is a known bash issue, bash doesn't work well with spaces in filenames.  Read about the IFS=$'\n'. IMHO will be easier to rewrite on python.

```python
#!/usr/bin/env python3

import os
import subprocess

start = os.path.curdir

def process_file(file):
    if not file.endswith(".flac"):
        return
        
    args = [
        "metaflac",
        "--import-picture-from=cover.jpg",
        file
    ]
    subprocess.check_call(args)


for root, dirnames, filenames in os.walk(start):
    for file in filenames:
        process_file(os.path.join(root, file))
```

**Comment by frantic1048** [comment]
> fffcoverart.elv (fd -e flac) does not work with folder names that contain spaces (for me).

@landgenoot What shell and version are you using?

The example command `fffcoverart.elv (fd -e flac)` in `fffcoverart.elv` is elvish command, means it should be executed in elvish shell.

A pair of `()` is [output capture](https://elv.sh/ref/language.html#output-capture) in elvish. Output capture splits command result by newline.

`fd` in example points to https://github.com/sharkdp/fd . It prints results line by line. Combining with elvish output capture, `fffcoverart.elv (fd -e flac)` is not likely to separate a folder name with spaces into multiple items.

My test outputs are below. The folders with spaces are not splited into multiple items. Those flac files are just empty files. I'm just testing the folder name issue.

```
/tmp/tmp.9xOlu6bxWw> tree .
.
├── Deep Folder
│   └── Folder With Many Spaces
│       ├── a.flac
│       ├── b.flac
│       └── c.flac
└── Folder With Many Spaces
    ├── a.flac
    ├── b.flac
    └── c.flac

3 directories, 6 files
/tmp/tmp.9xOlu6bxWw> fffcoverart.elv (fd -e flac)
?(fail 'Ignored, Non FLAC file:/tmp/tmp.9xOlu6bxWw/Deep Folder/Folder With Many Spaces/a.flac')
?(fail 'Ignored, Non FLAC file:/tmp/tmp.9xOlu6bxWw/Deep Folder/Folder With Many Spaces/b.flac')
?(fail 'Ignored, Non FLAC file:/tmp/tmp.9xOlu6bxWw/Deep Folder/Folder With Many Spaces/c.flac')
?(fail 'Ignored, Non FLAC file:/tmp/tmp.9xOlu6bxWw/Folder With Many Spaces/a.flac')
?(fail 'Ignored, Non FLAC file:/tmp/tmp.9xOlu6bxWw/Folder With Many Spaces/b.flac')
?(fail 'Ignored, Non FLAC file:/tmp/tmp.9xOlu6bxWw/Folder With Many Spaces/c.flac')
/tmp/tmp.9xOlu6bxWw> elvish -version
0.13.1
```
