### ISSUE TITLE
Assertion `tags.count() == mTracks.count()' failed.

### ISSUE THREAD

**Issue by brainchild0** [flacon/flacon#82]
Application exits abnormally with the below message after initiation of "Get Data from CDDB" for a CUE/FLAC file pair discovered in a directory scan.  The problem does not reproduce to other similar pairs from the same scan.  Nothing unusual is apparent about the data except that the first track is missing an "INDEX 00" statement.  Adding such a statement to the file manually does not resolve the problem.

    Assertion `tags.count() == mTracks.count()' failed.

Please send me a message if you need information about the contents of the files.

The audio plays correctly, and metadata is displayed correctly, in Clementine 1.3.1.

Flacon version: 5.0
Flacon distribution: Ubuntu repository
System: Ubuntu: 18.10

**Comment by SokoloffA** [comment]
Please send me the problem CUE file.

**Comment by SokoloffA** [comment]
Bug is confirmed.

**Comment by SokoloffA** [comment]
Closed in release 5.1.0
