### ISSUE TITLE
Feature: dynamic naming of per track cuesheet

### ISSUE THREAD

**Issue by brainchild0** [flacon/flacon#83]
I have tried using Flacon and I have found extremely useful to facilitate an operation that many users had needed but lacked a straightforward tool to do it.

The parallel operations in particular are not always easy to achieve with existing tools even for someone comfortable with scripting and command-line interfaces 

One helpful feature would be a way to customize the naming of cuesheets, when they are generated with the option "Create per track CUE sheet".  It appears that the name is currently statically determined as `%a-%A.cue`.  This template is similar to one in common use, `%a - %A`, and I think that spaces are generally preferred.  Adding spaces to the builtin template may improve usability, but ultimately I would request full support for patterns.

**Comment by SokoloffA** [comment]
Closed in release 5.1.0
