### ISSUE TITLE
feature request: Work with individual track albums

### ISSUE THREAD

**Issue by Rinkke999** [flacon/flacon#84]
Hello!
Thank you so much for your work on this amazing piece of software. It's fast, the audio quality is amazing and it's extremely stable. 
I would have one suggestion though that would make the program absolutely perfect imho: the possibility to work with albums that are already split into individual tracks. 
I dont know much about coding or how much work this would imply, but upon implementation of this feature, I will gladly pay/donate some money to this project :-)
Thanks again for your great work and keep it up. I'm just trying to give some constructive criticism, doesn't mean I am not satisfied, quite the contrary is the case. 
Best wishes
rinkke

**Comment by SokoloffA** [comment]
I've already been [asked to do that](#59). Unfortunately, it is not easy to add this feature to the program. Will be easier to write a new program.

What you do not like the existing converters, like http://soundconverter.org or https://github.com/dfaust/soundkonverter

**Comment by SokoloffA** [comment]
Please see the [FAQ](https://github.com/flacon/flacon/wiki/Frequently-Asked-Questions)
