### ISSUE TITLE
Feature/documentation request: document external programs

### ISSUE THREAD

**Issue by SynedraAcus** [flacon/flacon#85]
I am trying to convert a FLAC+CUE file to a bunch of MP3s, but it fails with the following output (CUE parses alright, though):

```
File /home/morozov/Music/Ирина Богушевская - Неполное собрание сочинений/Книга песен/Ирина Богушевская - Книга песен.flac is not a supported audio file.   Verify that all required programs are installed and in your preferences.: [Decoder] Can't start '': No such file or directory
```

Judging by Settings->Preferences->Programs, I'm missing some external program that should parse FLAC, but I have no idea what it could be. Installed everything from sources according to the wiki page. It would be useful if a list of compatible/recommended programs for each filetype was available somewhere.

EDIT: `sudo apt-get install flac lame` was enough for FLAC-to-MP3 conversion, but I still have no idea what's gonna be necessary for other formats.

**Comment by SokoloffA** [comment]
The full list of all necessary programs you can see at the preferences dialog "Main menu - Settings - Preferences - Programs" ("Главное меню - Настройка - Настройки - Программы").

It's strange, flacon package for the Debian/Ubuntu should be install all required programs:
```
Depends: ${shlibs:Depends}, ${misc:Depends}, flac, mac | monkeys-audio                                                                          
Recommends: vorbis-tools, wavpack, lame, vorbisgain, mp3gain, ttaenc, faac, opus-tools 
```

Did you install program from my PPA or build it from the sources?

**Comment by SynedraAcus** [comment]
I was building from sources and these programs were not installed on my system during flacon installation. Can't say anything about the PPA.

Eventually I've understood that Programs menu shows the actual names of the programs it requires, not something like "any program that supports this or that interface". Guess this issue could be closed.

**Comment by SokoloffA** [comment]
>Guess this issue could be closed.
