### ISSUE TITLE
flacon doesn't handle cue files when a track has more than INDEX 00 + 01

### ISSUE THREAD

**Issue by krallenbande** [flacon/flacon#86]
Hi,

I just found the second cd with an INDEX higher than 01 – and I'm sure there are more out there. As you can see in the snapshot, it causes an issue which doesn't let you extract the songs.

![Screenshot from 2019-03-10 19-19-06](https://user-images.githubusercontent.com/38839609/54089619-1a1a3e80-436b-11e9-8e0b-753ba2243318.png)

The snippet is an excerpt from the cue file:

```
---snip---
  TRACK 05 AUDIO
    TITLE "Groove On"
    PERFORMER "Thompson Twins"
    REM COMPOSER ""
    INDEX 00 14:57:17
    INDEX 01 14:57:18
  TRACK 06 AUDIO
    TITLE "Strange Jane"
    PERFORMER "Thompson Twins"
    REM COMPOSER ""
    INDEX 00 18:51:70
    INDEX 01 18:51:73
    INDEX 02 22:50:54
---snip---
```

As you can see track 6 contains one extra index and both, track 5 + 6 are affected in flacon.

I remember other cds having more indices. It was used to jump forward and backward inside a song – usually long songs with different parts –, but if you e. g. used random play, you could be sure every song was played as a whole.

I hope, this isn't hard to fix…

**Comment by SokoloffA** [comment]
I fixed the bug. Does the audio file has CD quality or HI-res?

**Comment by krallenbande** [comment]
Thank you, I will check it out, when it's in the repo.

All cue-flac-files I tested so far were standard cd-audio files.

**Comment by SokoloffA** [comment]
I hope I will make a release in the coming days.
