### ISSUE TITLE
unable to install flacon in linux mint 19.1 tessa

### ISSUE THREAD

**Issue by jayy1455** [flacon/flacon#87]
after to write in terminal > sudo add-apt-repository ppa:flacon/ppa

it says : gpg: failure to receive from the key server: Connection terminated by expiry of the waiting time
thanks for help !!

**Comment by SokoloffA** [comment]
I think your problem is similar to this issue #81. Read it, I hope this helps.

**Comment by SokoloffA** [comment]
Oh now!  "Connection terminated by expiry of the waiting." This looks like a network problems on the [launchpad server](https://launchpad.net/~flacon/+archive/ubuntu/ppa). Please try again later.

**Comment by jayy1455** [comment]
Ok thank you.
