### ISSUE TITLE
Conversion Error

### ISSUE THREAD

**Issue by Faust30000** [flacon/flacon#90]
OS: Linux Mint 19.1 Cinnamon x64
Flacon 5.1.0
Error appears when converting ape [Decoder] Can't read 52816512 bytes.
When converting another file error [Decoder] Can't skip to start of track.
Ape file in order, audio players read it without any problems. It was also possible to convert it without problems with the program gCue2Tracks. Why another program could convert, and Flacon could not? The problem is not in the file.

**Comment by SokoloffA** [comment]
Please send me problem APE and CUE files. If you don't want publicly, email me at sokoloff.a@gmail.com

**Comment by Faust30000** [comment]
APE https://cloud.mail.ru/public/4Xxr/PdVMaFDSh
CUE https://cloud.mail.ru/public/Dr13/1C2Gs8aAY

**Comment by SokoloffA** [comment]
У меня этот диск без проблем сконвертировался. 
Судя по альбому, ты говоришь по русски. Может свяжешься со мной по мылу sokoloff.a@gmail.com и выясним почему у тебя не работает на русском?

**Comment by SokoloffA** [comment]
The problem was with an older version of the mac program. I updated the program, now the conversion works fine.
