### ISSUE TITLE
unable to install flacon in linux mint 19.1  

### ISSUE THREAD

**Issue by jayy1455** [flacon/flacon#91]
Hi..sorry to repost but the previous conversation was closed, so I post again.
I've been waiting and it still doesn't work..(always the same issue)

[after to write in terminal > sudo add-apt-repository ppa:flacon/ppa
it says : gpg: failure to receive from the key server: Connection terminated by expiry of the waiting time] 

on the other hand, yesterday, on a laptop, I managed to install it on a distribution based on Xenial (16.04) (lxle)...I don't understand...

**Comment by SokoloffA** [comment]
It looks like a network problem on your computer. 
I installed Linux Mint 19.1 Cinnamon and updated the keys without any problems. 

Please check the firewall settings. 

In the extreme case it is possible to download [the deb packages for flacon and mac](https://launchpad.net/~flacon/+archive/ubuntu/ppa/+packages), and to install them using dpkg.

**Comment by jayy1455** [comment]
Great... it worked !!! 
as you suggested, the problem came from my firewall settings. 
Thanks  a lot.
