### ISSUE TITLE
Doesn't decode .ape files without proprietary software

### ISSUE THREAD

**Issue by ethus3h** [flacon/flacon#92]
Hi, flacon seems to require the proprietary "mac" tool to decode .ape files, even when ffmpeg is installed with a working free .ape decoder. It should use the ffmpeg decoder when it's available, and not suggest proprietary software. Thanks!

**Comment by SokoloffA** [comment]
A few years ago I was experimenting with ffmpeg. The results are disappointing.
1. If you redirect ffmpeg output to a pipe, ffmpeg writes an incorrect ChunkSize in the WAV header.
2. If you do not specify an output bitrate, ffmpeg will automatically downscale HD audio to to 16 bits. The guys from ffmpeg said it's not a bug. 
3. In some situations, ffmpeg skips data. I opened the [bug](https://trac.ffmpeg.org/ticket/6937) 16 months ago, it's still open.

With this attitude to sound quality, I can't trust the program. This may not be critical for video playback, but it is not suitable for high-quality audio conversion.
