### ISSUE TITLE
flacon (audio file splitter and converter) installs ok, but won't run/start

### ISSUE THREAD

**Issue by scoostraw** [flacon/flacon#93]
The program installs ok but will not launch.  The icon on the task bar begins to appear but then just vanishes.

OSX El Capitan 10.11.6

**Comment by SokoloffA** [comment]
I released the new version and prepared dmg for old MacOS. Please try the [Flacon_5.5.1-LegacyOS.dmg](https://github.com/flacon/flacon/releases/download/v5.5.1/Flacon_5.5.1-LegacyOS.dmg) and let me know about results.
