### ISSUE TITLE
Can't convert from ape to flac

### ISSUE THREAD

**Issue by rulet** [flacon/flacon#94]
Не конвертирует во flac. Вот скриншот ошибки https://fex.net/s/tcdoeko
Вот zip-архив с CDImage.ape и .cue файлами https://fex.net/s/spry4kz
Вот что происходит в терминале:

flacon
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
[Decoder] Error: 1009
[Decoder] Error: 1009
Splitter error for track  1 :  "[Decoder] Can't read 6178704 bytes"
QThread::start: Thread termination error: Нет такого процесса
[Decoder] Can't read 6178704 bytes
Encoding time 1 sec

mac CDImage.ape CDImage.wav -d
--- Monkey's Audio Console Front End (v 3.99) (c) Matthew T. Ashland ---
Decompressing...

Error: 1009

foobar2000 конвертирует без проблем. В чем может быть причина?

**Comment by SokoloffA** [comment]
Проблема скорее всего в [старой версии mac](https://github.com/flacon/flacon/issues/90). У тебя 3.99, обнови до 4.11.

**Comment by rulet** [comment]
Дело в том что я из твоей репы для Debian 9, описанной здесь https://flacon.github.io/download/, устанавливал flacon, а ищ нее вместе с flacon устанавливается Monkey's Audio Console Front End (v 3.99). При попытке поверх плоставить mac 4.11 вот что пишет:

r@prime:~$ sudo dpkg -i monkeys-audio_4.11-u4-b5-s7-dmo3_amd64.deb 
[sudo] пароль для r: 
Выбор ранее не выбранного пакета monkeys-audio.
(Чтение базы данных … на данный момент установлено 298957 файлов и каталогов.)
Подготовка к распаковке monkeys-audio_4.11-u4-b5-s7-dmo3_amd64.deb …
Распаковывается monkeys-audio (4.11-u4-b5-s7-dmo3) …
dpkg: ошибка при обработке архива monkeys-audio_4.11-u4-b5-s7-dmo3_amd64.deb (--install):
 попытка перезаписать «/usr/bin/mac», который уже имеется в пакете mac 3.99-u4-b5-s7-4
При обработке следующих пакетов произошли ошибки:
 monkeys-audio_4.11-u4-b5-s7-dmo3_amd64.deb
r@prime:~$

**Comment by SokoloffA** [comment]
Я собрал пакет mac 4.11 для Debian 9, просто обнови mac. 
Или удали mac и потом поставь monkeys-audio.

**Comment by rulet** [comment]
Удалил flacon вместе с mac, затем попробовал установить 4,11:

sudo dpkg -i monkeys-audio_4.11-u4-b5-s7-dmo3_amd64.deb 
[sudo] пароль для r: 
Попробуйте ещё раз.
[sudo] пароль для r: 
Выбор ранее не выбранного пакета monkeys-audio.
(Чтение базы данных … на данный момент установлено 298834 файла и каталога.)
Подготовка к распаковке monkeys-audio_4.11-u4-b5-s7-dmo3_amd64.deb …
Распаковывается monkeys-audio (4.11-u4-b5-s7-dmo3) …
dpkg: зависимости пакетов не позволяют настроить пакет monkeys-audio:
 monkeys-audio зависит от libmac2, однако:
  Пакет libmac2 не установлен.

dpkg: ошибка при обработке пакета monkeys-audio (--install):
 проблемы зависимостей — оставляем не настроенным
При обработке следующих пакетов произошли ошибки:
 monkeys-audio
r@prime:~$ sudo apt-get install -f
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Исправление зависимостей… Готово
Пакеты, которые будут УДАЛЕНЫ:
  monkeys-audio
обновлено 0, установлено 0 новых пакетов, для удаления отмечено 1 пакетов, и 0 пакетов не обновлено.
не установлено до конца или удалено 1 пакетов.
После данной операции, объём занятого дискового пространства уменьшится на 34,8 kB.
Хотите продолжить? [Д/н]

**Comment by SokoloffA** [comment]
>Удалил flacon вместе с mac(вместе с репозиторием), затем попробовал установить 4,11:

Эх как ты жестко. Добавь репозиторий и поставь flacon по новой, в репозитории уже новая версия mac-а. https://build.opensuse.org/package/binaries/home:Sokoloff/mac/Debian_9.0

**Comment by rulet** [comment]
Хмм... т.е. нужно обновить репозиторий? Попробую.

**Comment by SokoloffA** [comment]
Раз пошла такая пьянка, я обновил и flacon до 5.4.0.

**Comment by rulet** [comment]
Хм... я успел еще предыдущую поставить т.е. 5.1.0 из репы. Вобщем тот образ cue на этот раз сконвертировало и разбило на файлы(и flac и mp3) нормально. Спасибо. А чем версия 5.4.0 отличается от 5.1.0?

**Comment by SokoloffA** [comment]
> Хм... я успел еще предыдущую поставить т.е. 5.1.0 из репы.

ну сделай apt install flacon оно поставит новую версию.

>А чем версия 5.4.0 отличается от 5.1.0? 

Основное - обработка CUE файлов с индексами больше 01 и можно использовать номер диска в имени треков, ну и мелкие улучшения. Вот полный лог http://flacon.github.io/changelog/

**Comment by rulet** [comment]
Ok, спасибо.
