### ISSUE TITLE
Flacon 5.4.0 not working on Debian 9

### ISSUE THREAD

**Issue by jazbina** [flacon/flacon#96]
It just stop. This is what I get when starting from terminal. `QIODevice::write (QProcess): device not open
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 768, resource id: 7494606, major code: 40 (TranslateCoords), minor code: 0
QIODevice::write (QProcess): device not open
`
<a href="https://i.imgur.com/KxbsWbn.png">
  <img src="https://imgur.com/KxbsWbnl.png" />
</a>

**Comment by SokoloffA** [comment]
I apologize for the long silence.

1. The program shows an warning sign (a yellow triangle with an exclamation point). Place the mouse cursor over the sign, you will see a tooltip describing the problem. Please send me this warning text. 

2. Also show me your configuration file ~/.config/flacon/flacon.conf
