### ISSUE TITLE
automatic file names not always windows safe

### ISSUE THREAD

**Issue by brainchild0** [flacon/flacon#99]
Flacon currently generates file names that are not safe for Windows file systems

According to an [article provided by Microsoft](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#file-and-directory-names), certain restrictions apply to Windows file names, which Flacon appears not fully to respect.  In particular, I have observed that Flacon generates file names that include `<`, `>`, and `..`.  These particular sequences are merely ones I have noticed during casual use, not an exhaustive set of proscribed ones currently in use.

Note that in my use case, the files are generated on a Linux system, and then are transferred to a Windows store.  In case Flacon is currently generating different file names depending on the platform, I would suggest a solution in which Flacon generates the same results regardless of the platform where it is run.  

It seems that Windows is more particular about file names than other platforms, so in order not to encumber users of other platforms unnecessarily, perhaps Flacon should support a toggle option that determines whether generation of file names follows the stricter Windows rules.  Some users may not want Flacon to follow these rules, but please note that many users will have limited interest in preserving punctuation, whereas many users will want  generated music files to moved seamlessly across platforms, including NAS devices and removable media.  Mostly, music players will display titles based on metadata, with file names serving the purpose of facilitating a user's management of files when  accessed without the aid of a metadata-aware tool.  

As such, file names that very closely represent the titles in the metadata are of secondary importance to files that can be safely stored and copied by casual users without obstacles.

**Comment by SokoloffA** [comment]
I [tweaked](https://github.com/flacon/flacon/commit/914d64269eef3816b7b16c94e52ccabbf42f9b19) the code. I think file names should always be safe. 



> Flacon generates file names that include `<`, `>`, and `..`. 

Why did you talk about the '..' symbol? I don't see it in the MS document, and I successfully created a file with two dots in Windows 10.

P.S.
It's a pity to lose the double quote character.

**Comment by brainchild0** [comment]
> Why did you talk about the '..' symbol? I don't see it in the MS document, and I successfully created a file with two dots in Windows 10.

Yes, you're right.  The document makes no reference to `..`, which appears to be allowed as long as the name has additional characters.

However, testing over my SMB share, I find that any name that ends in `.` is renamed to an arbitrary string of letters, digits, and hyphens.  This affects directory names that have no extension but might represent an album name whose title string ends in `.`.
 
> P.S.
> It's a pity to lose the double quote character.

Quotations of any kind in file names complicate processing by scripts or command line.  My inclination is to lose both single and double quote characters.  For these characters, one possibility is simply to drop them rather than replacing by hyphens or quote characters of a different kind.

**Comment by SokoloffA** [comment]
As I know, all file systems allow single quotes, so I want to see single quotes in filenames. In any case, now flacon don't allow double quotes in the filenames, so the following code will work
```
IFS=$'\n'; for f in `ls *.flac`; do ls -l "$f"; done
```


> In fact, dropping a character rather than replacing it might even be the cleanest solution for other characters as well

I think some symbols better to replace, and other better to remove. I propose replace instead remove because we can have phrases  like "Mercury/Deacon" and is better to have "Mercury-Deacon" than "MercuryDeacon".  Here's my suggestion:

| Character | Action |
| --------   | -------- |
| Characters from 1 through 31, except TAB and NEW LINE  | remove |
| TAB (\t) | replace to " " (space) |
| NEW LINE (\n) | replace to " " (space) |
| / | replace to - (dash) |
| \ | replace to - (dash) |
| : | replace to - (dash) |
| * | replace to - (dash) |
| ? | replace to . (dot) |
| < | replace to [ |
| > | replace to ] |
| " | replace to ' (single quote) |

**Comment by brainchild0** [comment]
> I think some symbols better to replace, and other better to remove.

That is what I meant to suggest.  

Single quotes   have special meanings in shells, and in some other applications.  Occasionally, applications and scripting workflows break when files contain them.  Developers tend to be sloppy about testing for file names that contain any quotes, either because of an incorrect assumption that the file system does not allow them or because of failure to imagine that anyone would place them in a file name.   In general practice, file names are  rarely chosen so as to contain any quotes, even when the file system permits them.  

Also, I suggest special handling of dots, since   they also have special meaning in file names, which is to separate base name from extension.

Finally, I think that neither dot nor dash should be used as a replacement target.  Dash is most often used to separate fields in naming templates, so the automatically generated dashes are easy to confuse with field separators.  Underscore might be a better choice.  Dots of course may not be a good choice for reason already stated.

**Comment by SokoloffA** [comment]
The problems about you write are sh/bash problems. Other languages have no problem with special characters in file names. In shell, even a space in the file name causes problems. 

Basically, the program is designed for GUI guys. I myself belong to the people who organize the collection by directory and file names. And I like to have filenames that match the tags as much as possible. If I could I would leave all characters except"/". So I'm not prepared to use such aggressive replacement as you suggest.

Different file systems have [different limits](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits). I don't use smart handling of too long names. If an error occurs during the conversion, the user sees a error message and can correct the situation manually. I do

**Comment by brainchild0** [comment]
These thoughts  are sound.

You may still want to use replacement targets other than dot and dash.  I find that underscore is a common choice for the cases in which you are using dash.  And what is the reason for your preference for dots as the target for question mark?  Is it the similar function in text, as to terminate a sentence?

**Comment by SokoloffA** [comment]
In 5.4.0 the [replacement function](https://github.com/flacon/flacon/blob/fe8726a7616dbc6b4da35136e4d908c88a55e49b/types.cpp#L317
) is primitive, it replaces everything with _.

In most cases, I don't care which symbol to use for the replacement. Let's use underscore. 

The question about the **slashes**. I think that AC-DC looks better than AC_DC.

With **question mark** harder. I thought so, most often a sign "?" means the end of the sentence replace it with a period makes sense. But after googling I somewhat changed my mind:
1. In most situations "?" at the end of the title. We can be simply removed question.
2. The second popular, when question mark is before the bracket, like *"(Who?) Keeps Changing Your Mind"* of South Street Player. We can remove question, too.
3. The question in the middle of the title. We can imagine title like *"Do you love me? I love you"*
But I have not found such examples. So we can just ignore these cases, and remove question mark.

So,  my new suggestion.

if character at the middle of text 

| Character | Action |
| --------   | -------- |
| Characters from 1 through 31, except TAB and NEW LINE  | remove |
| TAB (\t) | replace to " " (space) |
| NEW LINE (\n) | replace to " " (space) |
| / | replace to - (dash) |
| \ | replace to - (dash) |
| : | replace to _ (underscore) |
| * | replace to _ (underscore) |
| ? | remove |
| < | replace to [ |
| > | replace to ] |
| " | replace to ' (single quote) |

If any of the above characters is at the end of the text, we delete it. Except double quote mark, we replaced it on single quote.

Additionally, we handle the situation if the name equal ".." or ".". We replace them with "__" and "_" respectively.

**Comment by brainchild0** [comment]
We can consider two distinct  approaches to the question.  One is to provide file names that look as what a user might choose when naming a file, possibly including considerable mutation away from the   metadata used to generate them.  The other is to provide file names that evoke familiarity  with  the   metadata, as much as possible   resembling that text.

In either case, it is unlikely that a file would not be recognized properly by the owner.  In either case, the user will not deal directly the file name during regular use, when a metadata-aware application is in use.

Which to choose is a matter of preference.  But for my taste, considering metadata is preserved despite the file name, a file name is more useful if it looks more like other file names.

You appear to agree with my preference to some degree:

> In most cases, I don't care which symbol to use for the replacement. Let's use underscore.

But you also depart away from it, to give a set of special cases.

I suppose the question to consider is the reason why you do care about certain cases.  Understanding the answer will help to evaluate what rules to use finally.

The proposal you have given is somewhat complicated.  Of course we expect no major difficulty in  the implementation or maintenance of the code.  But I have concerns that the effect of so many rules will not be as predictable or consistent as you would like.  You are considering   quite a few different cases, anticipating where and why a particular character is used.  The  greater the count of distinct rules you include, the more likely a boundary case would emerge that does not satisfy your intention.

For example, the substitution of angular braces for square ones seems sound on the surface, but is it possible that   an inequality operator will be used at some point?  It may seem frivolous to suggest such an unlikely boundary case, but it is useful to decide what level of tolerance you have for unwanted effects in such a condition.  Every boundary case is harmless... until it occurs.

When I consider the current behavior that you are seeking to replace, I consider a behavior that is simple, reliable, and effective, and I see little reason to change it.

Aside from adding any characters that must be included and  currently are not, the only change I suggest is replacing the period.  This suggestion follows from my preference for generating file names that look like   names one is likely to choose when naming files.  But your preference seems to be different.

**Comment by SokoloffA** [comment]
>We can consider two distinct approaches to the question. One is to provide file names that look as what a user might choose when naming a file, possibly including considerable mutation away from the metadata used to generate them. The other is to provide file names that evoke familiarity with the metadata, as much as possible resembling that text.
... In either case, the user will not deal directly the file name during regular use, when a metadata-aware application is in use.

I'm a user what "deal directly the file name during regular use". I use the Clementine in file mode. And every day I see the names of the directories for artists and albums. And I know guys that select directory in the foobar. So I like to have file names that evoke familiarity with the metadata, as much as possible resembling that text.

I'm not planning to write artificial intelligence for it:) Just making the replacements a bit more appropriate. Not big changes, this question no so important. The program is more than 7 years old, and I have no issues about unreadable names in the bug tracker. Before your post, I even wasn't worried about the replacement function at all. Function returns a safe file name and this enough. But after your post, I thought that making the function bit smarter is a good idea. 

> dots have special meaning in file names, which is to separate base name from extension. ... 
> I suggest is replacing the period.

Dots have special meaning 40 years ago in the DOS, now it is a standard symbol. We have packages like *flacon_5.4.0-1_amd64.deb*, libraries like *libFLAC.so.8.3.0*, we have binary like *bison.yacc* or *telnet.netkit*. 
I've written a lot of bash scripts, but I've never had a problem with dot in scripts. Spaces in the file name cause more problems. Other languages have no problems with file names at all. 

Therefore, I am against the replacement dot. The dot is quite often used in song names.

> You appear to agree with my preference to some degree ... But you also depart away from it, to give a set of special cases.

We have a misunderstanding. Let me explain why I'm proposing such replacements.

1. **Tab** and **new line** can be used instead of a space, so we replace "\t" and "\n" with a space.

2. **Slashes** occurs in names (example AC/DC). In my opinion the AC-DC looks better than AC DC, AC_DC or ACDC. Therefore, we replace "/" and "\\" with "-".

3. A **question mark** occurs either at the end of name or before parentheses. The ```Why.flac``` looks better than ```Why_.flac```, and ```(Who) Keeps Changing Your Mind.flac``` is better then ```(Who_) Keeps Changing Your Mind.flac``` so we remove the question mark at all.

4. Replace the **double quote** with a single quote, because this is the closest.

5. **Characters from 1 through 31** (except TAB and NEW LINE) is a garbage, and they can't be in names. Delete them.

6. **":", "*", "<", ">"** I can't remember the songs with such symbols, perhaps they don't exist, so isn't important what to use instead  them. Using "<" or ">" as inequality operator is more likely than the using HTML tag in a album/song name, but I can't think of a solution for inequality operator. So I suggested "["and "]" as the most similar. But I don't care, let's replace them all with underscores.

> The greater the count of distinct rules you include, the more likely a boundary case would emerge that does not satisfy your intention.

Like I said, it's not that important. Stupid method satisfied all for many years, so the boundary cases has no matter. If we increase the chance of hitting, is already good.

I hope I was able to clarify my point.

**Comment by brainchild0** [comment]
> Like I said, it's not that important. Stupid method satisfied all for many years, so the boundary cases has no matter. If we increase the chance of hitting, is already good.
> 
> I hope I was able to clarify my point.

I think that your intention is fine, and that the proposal you have given satisfies your intention as well as any.  I have no improvements to offer at this time.

**Comment by brainchild0** [comment]
I tested the new version.  Mostly the results were much better.  There was only one point at which the functionality may have regressed.  One of the tracks in the my collection could not be extracted properly ("I can't rename file", "File name too long").  The target name appearing in the error message is 268 characters including extension.  I believe that this is 3 characters longer than the maximum allowed by Linux.  Without the `.opus` suffix, the name may have been valid.

The maximum length of a file's base name is 255 minus the length of the extension (in this case 4) minus 1 (for the `.`).  Is this the current intention?

In my view, it would be better to reduce the length a little further in case a suffix get used, as might happen for backups or conflicts during synchronization operations.  So perhaps truncating another 10 or even 15 characters is a good idea.

Note of course that truncation can in principle occur at the level of the field, in addition to the level of the file name derived from the template.  Such might be useful if the album name is very long and most of the truncation is affecting the track name.

**Comment by brainchild0** [comment]
Furthering the above, I recently attempted use of the generated file collection with a popular cloud storage solution.  The software apparently attempts to add a suffix to file names when storing them, creating a failure for files with names close in length to the maximum allowed by the system.  This operation might be classified as a flaw in the storage solution, but also points to the general consideration that users might be helped by a configurable option further limiting the allowed lengths for names of generated files beyond the limits appropriate for storage on the local system.

**Comment by SokoloffA** [comment]
I was thinking about the problem of long names. I don't know which is better, automatically truncate the names, or show a warning about long names.

In automatically truncating, there are restrictions:
1. We can't trim the band name, otherwise 2 albums will fit in different directories.
2. We can't trim the album name, otherwise the tracks will end up in different directories.
3. We can't trim the year tag, otherwise the sorting will go wrong, and it's has no sense (year is too short).

So we can truncate only the name of the song. 
Or blunt algorithm - trim the end of the file name, of course, extension will remain.

**Comment by brainchild0** [comment]
You raise many accurate observations.

One assumption that may be unneeded is that if a field name is truncated in a file name, then it must be similarly truncated in a folder name.  Whereas folder names and file names must be truncated deterministically across all tracks as applied to some naming template, such truncation need not occur identically in multiple locations within the template.  

Another assumption that may be unneeded is that it is impossible to truncate  any field that is shared across multiple tracks.


For example, I find no objection to the following result:

```
This is a very long band name_ Why was I so stupid to choose such a long name/This is a very long - Some Album - 01 - Some song.wav  
This is a very long band name_ Why was I so stupid to choose such a long name/This is a very long - Some Album - 02 - Another song.wav
This is a very long band name_ Why was I so stupid to choose such a long name/This is a very long - An album might also have a ver - 01 - The next song.wav
```
...and so on.

The user benefits from no truncation in the folder name, where the lack of additional fields provides more space for the one that is included.  Equally, the field truncation in the file names are acceptable as long as their result is identical for each field in each name.

Let's consider the remaining constraints.

Naturally, three characters for track number will satisfy all but the extremely paranoid, and four characters for year is hardly a subject of discussion.

For other fields, a general solution would be including the maximum character count into the template definition, but requiring such detail will test the patience of most users.

Unfortunately, without such information provided by the user, and with the requirement of reproducible results regardless of whether multiple inputs are processed separately or in the same input set, the only solution may be the following:

For each path component (e.g. directory or file) in the template:
1.  For each literal characters in the template, allocate one character in the target name.
1.  For the above numeric fields, allocate the prescribed character count.
1.  Allocate some number of characters to allow for file extension, and for later manipulation  by other applications.
1.  Find the sum of the  characters allocated as described above.
1.  For the remaining fields, the ones that are variable length, compute the maximum length of each by subtracting the above sum from the maximum allowed file size for the file system and then integer-dividing (i.e. rounding down) by the number of variable-length fields.

The most glaring weakness of the above is that if one field is so short that it needs no truncation, it is still allocated the same number of allowed characters as another field that might be much longer. 

I definitely feel that support should be provided for safe file names, rather than simply shifting responsibility to the user in the form of an error or warning.

**Comment by brainchild0** [comment]
You could extend the template syntax to support the following notation for maximum field length, similar to `printf` templates:

```
%230a/%y - %220A/%60a - %y - %60A - %2n - %100t
```

But most users will probably not want to be forced to select sizes for each field, and will want an algorithm that works in other cases.

Also, for text that does not fill the space, no padding is needed. For track numbers, though, zero padding is normally desired.  Whether to further extend the syntax using the form   in  `%02`, as in `printf`, or simply to  apply statically zero padding to relevant fields, would be another decision.

**Comment by SokoloffA** [comment]
I don't like the idea of extending the template syntax. 
 
1. Note that many FS have a byte limit. This means that in UTF-8 the English name can be 2 times longer than the localized one. Forcing the user to count the number of English and local letters is crazy.
2. We have a limit on the total string length if one tag is short, the other can be longer. But limitation in the template is static.
3. And most important. This situation should be considered as force majeur. In my experience, such long names are very very rare, I did not meet it at all. (Just curious, what disk were you encoding when you got the 268 characters problem?)

Template syntax is not easy for the user. I don't want to complicate it more. I think automatic truncation will be enough. 

I propose such an algorithm:
For each path component (e.g. directory or file) in the template:
1. We set full tags in the template as now. If the result name is less than 250 bytes (5 bytes for reserve), return it. In the most of cases, this will be so.
2. We try to shorten the tag "track name" by number of extra characters. If truncated "track name" is longer than 50 characters, we return it. Else we cut the tag to 50 characters and go to the next step.
3. We try to shorten the tag "album name" by number of extra characters. If truncated "album name" is longer than 50 characters, we return it. Else we cut the tag to 50 characters and go to the next step.
4. We try to shorten the tag "artist" by number of extra characters.

**Comment by brainchild0** [comment]
> 1. We set full tags in the template as now. If the result name is less than 250 bytes (5 bytes for reserve), return it. In the most of cases, this will be so.
> 2. We try to shorten the tag "track name" by number of extra characters. If truncated "track name" is longer than 50 characters, we return it. Else we cut the tag to 50 characters and go to the next step.
> 3. We try to shorten the tag "album name" by number of extra characters. If truncated "album name" is longer than 50 characters, we return it. Else we cut the tag to 50 characters and go to the next step.
> 4. We try to shorten the tag "artist" by number of extra characters.

In such a scheme, the resulting expression of the album and artist is determined by the names of the tracks in the input set.  If the user separately processes albums from the same artist, only one having long track names, then the artist field may have different final values.


Also note, as I said, the idea about the length in the template is that  gibing it would be optional.  I agree that it should not be required.  But the entire feature is not necessary..  

What I think is necessary is that somehow the final value for each field is independent of the values of the other fields.

**Comment by SokoloffA** [comment]
If we make the length spec are optional, we return to current situation. What to do if user hasn't specify the length?

Do you really think this is a real problem? The long tags will cause problems in MP3 players, and music stores, so record labels limit the length of tags. In my opinion, in real life, a user will not meet such long tags. So, I think the simplest solution will be enough. 
If the length of the name exceeds 250 bytes, just cut last symbols, and reduce name to 250 bytes. Of course the file extension remains at the end.

**Comment by brainchild0** [comment]
I'm sorry if I was unclear. 

I tried to suggest that two options are available:

  -   **Option 1:**   Use static rules to reduce the length of files.
  -   **Option 2:**   As above, _but also_ provide flexibility for advanced users to specify custom rules in the template.

If you feel inclined for a very simple solution, it is your decision, as you are the maintainer.  Some CDDB tags have very long values, especially for classical music, because the album title includes details about the specific performers or performance.  But this convention is a special case.
